/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.enumrules.EnumRulesUiTestLanguage with org.eclipse.xtext.common.Terminals

import "classpath:/org/eclipse/xtext/enumrules/enums.ecore"
generate enumRulesUiTestLanguage "http://www.eclipse.org/2009/xtext/ui/common/tests/EnumRulesTest"
 
Model:
  'existing' existing=ExistingEnum ('generated' generated=GeneratedEnum)? | 'generated' generated=GeneratedEnum
;

enum ExistingEnum:
  SameName | OverriddenLiteral = "overridden" | DifferentName
;

enum GeneratedEnum:
  SameName | DifferentName = "DifferentLiteral"
;