<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="assignmentFinderTest"
    nsURI="http://www.eclipse.org/2009/tmf/xtext/assignmentfindertestlanguage" nsPrefix="assignmentFinderTest">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keywordVal" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//KeywordVal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminalVal" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//TerminalVal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumVal" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//EnumVal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keywordBool" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//KeywordBool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminalBool" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//TerminalBool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumBool" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//EnumBool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mixedBool" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//MixedBool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containmentRef" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//ContainmentRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossRef" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//CrossRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeywordVal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kw" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TerminalVal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="term" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumVal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="en" eType="ecore:EEnum platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//EnumN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumN">
    <eLiterals name="lit1" literal="lit1"/>
    <eLiterals name="lit2" literal="lit2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeywordBool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kw" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TerminalBool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="term" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumBool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="en" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MixedBool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainmentRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ctx" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//ContainmentRefN"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainmentRefN">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrossRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossRef" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/AssignmentFinderTestLanguage.ecore#//CrossRef"/>
  </eClassifiers>
</ecore:EPackage>
