/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.xtext.ecoreInference.Bug285140TestLanguage with org.eclipse.xtext.testlanguages.ActionTestLanguage
 
import "http://www.eclipse.org/2008/tmf/xtext/ActionLang" as actionLang 
 
Model returns actionLang::Model:
	Child ({actionLang::Parent.left=current} right=Child)?;
 