/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.xtext.ecoreInference.DataTypeRuleWithEnumResultTestLanguage 
	with org.eclipse.xtext.enumrules.EnumRulesTestLanguage

import 'http://www.eclipse.org/2009/tmf/xtext/EnumRulesTest'
/* SuppressWarnings[external] */
import 'classpath:/org/eclipse/xtext/enumrules/enums.ecore'
 
Model:
  'model' existing=ExistingEnumAsDT
;

ExistingEnumAsDT returns ExistingEnum:
  'e'
;
