/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.contentassist.Bug291022TestLanguage
 	with org.eclipse.xtext.common.Terminals

generate bug291022TestLanguage "http://www.eclipse.org/xtext/ui/common/tests/2009/bug291022TestLanguage"

RootModel returns ModelElement:
  ( {RootModel} name=ID (type=[ModelElement])? 
    (
      '{'
        elements+=ModelAttribute*
      '}'
    )?
  )?
;
  
ModelElement:
  firstReference=[ModelElement] (':' name=ID)? (secondReference=[ModelElement])? 
  (
      ';'
    | '{' elements+=ModelAttribute* '}'
  )   
;

ModelAttribute:
  ModelElement | Attribute
;

Attribute:
  feature=[ModelElement] '=' value=STRING
;
