/*******************************************************************************
 * Copyright (c) 2012 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.contentassist.Bug381381TestLanguage
 	with org.eclipse.xtext.common.Terminals

generate bug381381TestLanguage "http://www.eclipse.org/xtext/ui/common/tests/2012/bug381381TestLanguage"

Model:
	stmt=CopyFieldNameToVariableStmt;
	
	
CopyFieldNameToVariableStmt:
  'FIELD-NAME-TO-VARIABLE' ((',' 'SCREEN' '=' '(' line=INT ',' column=INT ')') &
                            (',' 'VAR' '=' name=ID) &
                            (',' 'TYPE' '=' 'REPLACE')?);