/*******************************************************************************
 * Copyright (c) 2009, 2020 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.contentassist.CrossReferenceProposalTestLanguage
 	with org.eclipse.xtext.common.Terminals

generate crossReferenceProposalTest "http://www.eclipse.org/xtext/ui/common/tests/2009/crossReferenceProposalTest"

Model :
        (elements+=Class)*;

Class :
        ((superClass=[Class|'Object']|superClass=[Class]|superClass=[Class|ComplexName]) '<-')? name=(ID|ComplexName) '{' '}';

ComplexName:
	'::' ID
;