/*******************************************************************************
 * Copyright (c) 2017 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.contentassist.GH341TestLanguage
 	with org.eclipse.xtext.common.Terminals

generate gh341TestLanguage "http://www.eclipse.org/xtext/ui/common/tests/2012/gh341TestLanguage"

Model:
	elements+=(Works | Broken | Third)*;

Element: Works | Broken | Third;

Works:
	"works" name=ID (ids+=ID ("." ids+=ID)* ";")* (refs+=[Works|ID] ("." refs+=[Works|ID])* "X" ";")*;

Broken:
	"broken" name=ID Fragment (refs+=[Broken|ID] ("." refs+=[Broken|ID])* "X" ";")*;

Third:
	DEFINE STREAM name=ID
;
fragment STREAM*: 'stream';
fragment DEFINE*: 'define';
fragment Fragment *:
	(ids+=ID ("." ids+=ID)* ";")*;