/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.contentassist.LookAheadContentAssistTestLanguage
 	with org.eclipse.xtext.common.Terminals

generate lookAheadContentAssistTest "http://www.eclipse.org/xtext/ui/common/tests/2009/lookAheadContentAssistTest"

Model : {Model} (
		'(' attribute+=Attribute* attribute+=Pair* ')'
	|	'[' attribute+=Attribute+ attribute+=Pair* ']'
	|	'<' attribute+=Attribute* attribute+=Pair+ '>'
	|	'{' attribute+=Attribute+ attribute+=Pair+ '}'
	);

Attribute:
        value=ID;

Pair:
        name=ID "=" value=ID;


//Model : '(' (attribute+=IdAttribute* | attribute+=StringAttribute*) (attribute+=Pair)* ')';
//
//Attribute:
//		IdAttribute | StringAttribute;
//	
//IdAttribute:
//        value=ID;
//
//StringAttribute:
//        value=STRING;
//        
//Pair:
//        name=ID "=" value=ID;

