/*******************************************************************************
 * Copyright (c) 2015, 2017 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.contentassist.ParametersTestLanguageEx 
	with org.eclipse.xtext.ui.tests.editor.contentassist.ParametersTestLanguage

import "http://www.eclipse.org/2015/tmf/xtext/parameters"
 
@Override 
ParserRuleParameters returns ParserRuleParameters: 
	super::ParserRuleParameters
;

@Override 
Scenario1<Param> returns Scenario:
	super::Scenario1<Param>
;
