/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.contentassist.Bug291022TestLanguage
 	with org.eclipse.xtext.common.Terminals

generate bug291022TestLanguage "http://www.eclipse.org/xtext/ui/common/tests/2009/bug291022TestLanguage"

RootModel returns ModelElement:
  ( {RootModel} name=ID (type=[ModelElement])? 
    (
      '{'
        elements+=ModelAttribute*
      '}'
    )?
  )?
;
  
ModelElement:
  firstReference=[ModelElement] (':' name=ID)? (secondReference=[ModelElement])? 
  (
      ';'
    | '{' elements+=ModelAttribute* '}'
  )   
;

ModelAttribute:
  ModelElement | Attribute
;

Attribute:
  feature=[ModelElement] '=' value=STRING
;
