/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.contentassist.Bug288760TestLanguage hidden(WS, ML_COMMENT)

import "http://www.eclipse.org/emf/2002/Ecore" as ecore
generate bug288760TestLanguage "http://www.eclipse.org/xtext/ui/common/tests/2009/bug288760TestLanguage"

WorkflowElement:
	  name=START_TAG (attributes+=Attribute)* END_TAG_SHORT 
	| name=START_TAG (attributes+=Attribute)* GT
		(children+=WorkflowElement)*
	  end=END_TAG
;
	
Attribute:
	name=ID EQ value=STRING
;

terminal ML_COMMENT: '<!--' -> '-->' ;

terminal START_TAG: LT ID ;

terminal LT: '<' ;

terminal GT: '>' ;

terminal EQ: '=' ;

terminal END_TAG_SHORT: '/>' ;

terminal END_TAG_START: '</' ;

terminal END_TAG: END_TAG_START ID GT;

terminal ID  		: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

terminal INT returns ecore::EInt: ('0'..'9')+;

terminal STRING	: 
			'"' ( '\\' ('b'|'t'|'n'|'f'|'r'|'"'|"'"|'\\') | !('\\'|'"') )* '"' |
			"'" ( '\\' ('b'|'t'|'n'|'f'|'r'|'"'|"'"|'\\') | !('\\'|"'") )* "'"
		; 

terminal WS			: (' '|'\t'|'\r'|'\n')+;

terminal ANY_OTHER: .;
