/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.contentassist.ContentAssistCustomizingTestLanguage
 	with org.eclipse.xtext.common.Terminals

generate contentAssistCustomizingTest "http://www.eclipse.org/xtext/ui/common/tests/2010/contentAssistCustomizingTest"

Model :
    types+=Type*
;

Type:
	name=FQN ('extends' superType=TypeRef)? ';'
;

TypeRef:
	type=[Type|FQN]
;

FQN:
	ID ('.' ID)*
;