/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.contentassist.LookAheadContentAssistTestLanguage
 	with org.eclipse.xtext.common.Terminals

generate lookAheadContentAssistTest "http://www.eclipse.org/xtext/ui/common/tests/2009/lookAheadContentAssistTest"

Model : 
		'(' attribute+=Attribute* attribute+=Pair* ')'
	|	'[' attribute+=Attribute+ attribute+=Pair* ']'
	|	'<' attribute+=Attribute* attribute+=Pair+ '>'
	|	'{' attribute+=Attribute+ attribute+=Pair+ '}';

Attribute:
        value=ID;

Pair:
        name=ID "=" value=ID;


//Model : '(' (attribute+=IdAttribute* | attribute+=StringAttribute*) (attribute+=Pair)* ')';
//
//Attribute:
//		IdAttribute | StringAttribute;
//	
//IdAttribute:
//        value=ID;
//
//StringAttribute:
//        value=STRING;
//        
//Pair:
//        name=ID "=" value=ID;

