/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.contentassist.UnorderedGroupsTestLanguage
 	with org.eclipse.xtext.common.Terminals

generate unorderedGroupsTest "http://www.eclipse.org/xtext/ui/tests/2010/UnorderedGroupsTest"

Model :
    (
	    visibility=('public'|'private'|'protected')?
	  & static?='static'?
	  & synchronized?='synchronized'?
	  & (abstract?='abstract' | final?='final')?
	)
	'class' name=ID '{' '}'
;
  
