/*******************************************************************************
* Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*
*******************************************************************************/
grammar org.eclipse.xtext.testlanguages.ReferenceGrammarUiTestLanguage with org.eclipse.xtext.common.Terminals

generate referenceGrammarUi "http://www.eclipse.org/xtext/ui/common/tests/ReferenceGrammar"
	
Spielplatz :
	 ( "spielplatz" groesse = INT ( beschreibung = STRING ) ? "{" ( kinder += Kind | erzieher += Erwachsener | spielzeuge += Spielzeug | familie += Familie ) * "}" ) ? ;

Person :
	 Kind | Erwachsener ;

Kind :
	 "kind" "(" name = ID age = INT ")" ;

Erwachsener :
	 "erwachsener" "(" name = ID age = INT ")" ;

Spielzeug :
	 "spielzeug" "(" name = ID farbe = Farbe ")" ;

Farbe :
	 wert=("ROT" | "BLAU" | "GELB" | "GRÜN") ;

Familie :
 	"familie" "(" name=("keyword" | STRING | ID)  mutter=[Erwachsener] vater=[Erwachsener] kinder+=[Kind] ("," kinder+=[Kind])* ")" ;
