/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.testlanguages.TreeTestLanguage with org.eclipse.xtext.common.Terminals

generate treeTestLanguage "http://www.eclipse.org/2008/xtext/ui/common/tests/TreeTestLanguage" 
 
Model:
  (children+=Node)*;

Node:
  name=ID
  '(' attrib=STRING ')'
  '{'(children+=Node)*'};';


