/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.parser.antlr.Bug299237TestLanguage with org.eclipse.xtext.common.Terminals

generate bug299237Test "http://eclipse.org/xtext/Bug299237TestLanguage"

Model: 
    "model" name=ID ";"
;