/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
language org.eclipse.xtext.parser.keywords.KeywordsTestLanguage

generate KeywordsTestLanguage "http://www.eclipse.org/2009/tmf/xtext/KeywordsTestLanguage"
 
Model:
  first?="foo\\bar" | second?="foo\\" | third?="\\bar" | forth?="\\"; 
