package bootstrap;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class MainSite {
  public CharSequence header() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("<html lang=\"en\">");
    _builder.newLine();
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("<meta charset=\"utf-8\">");
    _builder.newLine();
    _builder.append("<title>Eclipse Xtend</title>");
    _builder.newLine();
    _builder.append("<meta name=\"description\"");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("content=\"Eclipse Xtend is a statically-typed programming language running on the JVM.\">");
    _builder.newLine();
    _builder.append("<meta name=\"author\" content=\"Sven Efftinge\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->");
    _builder.newLine();
    _builder.append("<!--[if lt IE 9]>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<![endif]-->");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<!-- Le styles -->");
    _builder.newLine();
    _builder.append("<!-- <link href=\"bootstrap.css\" rel=\"stylesheet\"> -->");
    _builder.newLine();
    _builder.append("<link rel=\"stylesheet\" href=\"http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css\">");
    _builder.newLine();
    _builder.append("<style type=\"text/css\">");
    _builder.newLine();
    _builder.append("body {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("padding-top: 40px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("section {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("padding-top: 40px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("div#maincontainer>section {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("padding-top: 90px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append("</style>");
    _builder.newLine();
    _builder.append("<link href=\"google-code-prettify/prettify.css\" type=\"text/css\"");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("rel=\"stylesheet\" />");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\" src=\"google-code-prettify/prettify.js\"></script>");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\" src=\"google-code-prettify/lang-xtend.js\"></script>");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\" src=\"jquery-1.7.1.min.js\"></script>");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\" src=\"bootstrap-dropdown.js\"></script>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("var _gaq = _gaq || [];");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("_gaq.push([ \'_setAccount\', \'UA-2429174-4\' ]);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("_gaq.push([ \'_trackPageview\' ]);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("(function() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("var ga = document.createElement(\'script\');");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ga.type = \'text/javascript\';");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ga.async = true;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\'");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append(": \'http://www\')");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("+ \'.google-analytics.com/ga.js\';");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("var s = document.getElementsByTagName(\'script\')[0];");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("s.parentNode.insertBefore(ga, s);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("})();");
    _builder.newLine();
    _builder.append("</script>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<!-- Place this render call where appropriate -->");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("(function() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("var po = document.createElement(\'script\'); po.type = \'text/javascript\'; po.async = true;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("po.src = \'https://apis.google.com/js/plusone.js\';");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(po, s);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("})();");
    _builder.newLine();
    _builder.append("</script>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("$(\'#topbar\').dropdown();");
    _builder.newLine();
    _builder.append("</script>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<!-- Le fav and touch icons -->");
    _builder.newLine();
    _builder.append("<link rel=\"shortcut icon\" href=\"images/favicon.ico\">");
    _builder.newLine();
    _builder.append("<link rel=\"apple-touch-icon\" href=\"images/apple-touch-icon.png\">");
    _builder.newLine();
    _builder.append("<link rel=\"apple-touch-icon\" sizes=\"72x72\"");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("href=\"images/apple-touch-icon-72x72.png\">");
    _builder.newLine();
    _builder.append("<link rel=\"apple-touch-icon\" sizes=\"114x114\"");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("href=\"images/apple-touch-icon-114x114.png\">");
    _builder.newLine();
    _builder.append("</head>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<body onload=\"prettyPrint()\">");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence footer() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t");
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    return _builder;
  }
}
