/*******************************************************************************
 * Copyright (c) 2008, 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.grammarinheritance.ConcreteTestLanguage with org.eclipse.xtext.grammarinheritance.AbstractTestLanguage

generate foo "http://holla"

import "classpath:/org/eclipse/xtext/grammarinheritance/ametamodel.ecore" as mm

RootRule:
	ConcreteParserRule | CallOverridenParserRule | CallExtendedParserRule | OverridableParserRule2;

// call InheritedParserRule
ConcreteParserRule :
	'model' magicNumber=REAL ':' (elements+=InheritedParserRule)*;
	
// override OverridableParserRule and call it
OverridableParserRule returns mm::AType:
	'overriddenelement' name=ID;
	
CallOverridenParserRule:
	call=AbstractCallOverridenParserRule;
	
// override parser rule and change return type
OverridableParserRule2 returns AType2 :
	'overridden other element' name=ID '-' age=INT;
	
// override and extend ExtendableParserRule and call it
ExtendableParserRule returns mm::AType:
	Subrule1 | Subrule2 | Subrule3;
	
Subrule1:
	'subrule1' name=ID sub1=ID;

Subrule2:
	'subrule3' name=ID sub2=STRING;

Subrule3:
	'subrule3' name=ID sub1=INT;
	
CallExtendedParserRule:
	call=AbstractCallExtendedParserRule;
