/*******************************************************************************
 * Copyright (c) 2015 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.grammarinheritance.InheritanceTest3Language
	with org.eclipse.xtext.grammarinheritance.InheritanceTestLanguage
 	
import "http://www.eclipse.org/2009/tmf/xtext/InheritanceTestLanguage"

Model:
	super::Model
;

Element :
	  super::Element
	| {Element} "element" name=super::ID
	| {Element} "element" name=super::STRING
;

terminal ID: 'id';