grammar org.eclipse.xtext.purexbase.PureXbase with org.eclipse.xtext.xbase.Xbase

generate pureXbase "http://www.eclipse.org/xtext/purexbase/PureXbase"
import "http://www.eclipse.org/xtext/xbase/Xbase" as xbase

Model:
	importSection=XImportSection? block=SpecialBlockExpression;
	
SpecialBlockExpression returns xbase::XBlockExpression:
	{xbase::XBlockExpression}
	(expressions+=XExpressionOrVarDeclaration ';'?)*;

FeatureCallID:
	ValidID;