/*
 * Copyright (c) 2016 TypeFox GmbH (http://www.typefox.io) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
grammar org.eclipse.xtext.ide.tests.testlanguage.TestLanguage with org.eclipse.xtext.common.Terminals

generate testLanguage "http://www.eclipse.org/xtext/ide/tests/testlanguage/TestLanguage"

Model:
	types+=TypeDeclaration*;
	
TypeDeclaration:
	'type' name=ID '{'
	   properties+=Property*
	'}';

Property:
    type=Type name=ID
;

Type :
    (TypeReference |
    PrimitiveType) (arrayDiemensions+='['']')*
;

TypeReference:
    typeRef=[Type]
;

PrimitiveType:
    name=('string'|'int'|'boolean')    
;
