/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.enumrules.EnumRulesUiTestLanguage with org.eclipse.xtext.common.Terminals

/* SuppressWarnings[external] */
import "classpath:/org/eclipse/xtext/ui/tests/enumrules/enumsUi.ecore"
generate enumRulesUiTestLanguage "http://www.eclipse.org/2009/xtext/ui/common/tests/EnumRulesTest"
 
Model:
  'existing' existing=ExistingEnum ('generated' generated=GeneratedEnum)? | 'generated' generated=GeneratedEnum
;

enum ExistingEnum:
  SameName | OverriddenLiteral = "overridden" | DifferentName
;

enum GeneratedEnum:
  SameName | DifferentName = "DifferentLiteral"
;