/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parser.unorderedGroups.BacktrackingBug325745TestLanguage with org.eclipse.xtext.common.Terminals

generate backtrackingBug325745TestLanguage "http://www.eclipse.org/2010/tmf/xtext/backtrackingBug325745TestLanguage"

Model:
    {Model}
    (fields+=Element)+
;

Element :
    name=ID
    (dataType=DataType)?
    (expression=Expression)
    '.'
;

DataType :
    (baseType=ID (':=' defaultValue=STRING)?)
;

Expression:
  {Expression}
  ('['? & prefix=STRING?)
  ('['? terms+=SimpleTerm ']'?)* 
  (']'? & postfix=STRING?)
;

SimpleTerm:
  (lineCount=INT
  '*'?
  (charCount=INT)?
  '!'?
  (charSet=ID)?) | refChar=ID
;

