/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parser.unorderedGroups.SimpleBacktrackingBug325745TestLanguage with org.eclipse.xtext.parser.unorderedGroups.BacktrackingBug325745TestLanguage

import "http://www.eclipse.org/2010/tmf/xtext/backtrackingBug325745TestLanguage"
 
DelegateModel returns Model:
	Model
;