/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parser.unorderedGroups.SimpleUnorderedGroupsTestLanguage with org.eclipse.xtext.parser.unorderedGroups.UnorderedGroupsTestLanguage

import "http://www.eclipse.org/2010/tmf/xtext/UnorderedGroupsTestLanguage"
 
DelegateModel returns Model:
	Model
;