/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.resource.EObjectAtOffsetTestLanguage with org.eclipse.xtext.common.Terminals

generate eObjectAtOffsetTestLanguage "http://www.xtext.org/EObjectAtOffsetTestLanguage" 

Model:
	(foos+=Foo | bars+=AbstractBar)*;
	
AbstractBar:
	Bar ({FooBar.bar=current} 'foobar' foo+=[Foo|ID])?;

Bar:
	'bar' name=ID foo+=[Foo|ID] (',' foo+=[Foo|ID])*;
	
Foo:
	'foo' name=ID;
	
