/*******************************************************************************
 * Copyright (c) 2014 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.formatting2.internal.FormatterTestLanguage with org.eclipse.xtext.common.Terminals

generate formattertestlanguage "http://formatter2/formattertestlanguage"

Root:
	IDList | KWList;

IDList:
	{IDList} "idlist" ids+=ID*;

KWList:
	{KWList} "kwlist" kw1?="kw1"? kw2?="kw2"? kw3?="kw3"? kw4?="kw4"? kw5?="kw5"?;

