#!/bin/bash

cat <(cat locations.properties | head -n 1 | sed 's/xtext-lib/xtext-eclipse/') <(cat locations.properties) | cut -d "=" -f2- | while read -r line
do
	directory=$(echo $line | tr -d '\r')
	pushd $directory && git "$@"
	popd
done 

