/*******************************************************************************
 * Copyright (c) 2008, 2017 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.XtextFmtTest with org.eclipse.xtext.common.Terminals hidden(WS, SL_COMMENT)

generate formattertestlanguage "http://simple/formattertestlanguage"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
import "http://www.eclipse.org/2008/Xtext" as xtext

Root:
	"test" (TestLinewrap | TestIndentation);

/* SuppressWarnings[noInstantiation] */
TestLinewrap:
	"linewrap" items+=STRING*;

/* SuppressWarnings[noInstantiation] */
TestIndentation:
	"indentation" "{"
	(sub+=TestIndentation |
	items+=STRING)* "}"?;

enum enum1:
	a | b | c | d;

enum enum2:
	gt='>' | lt='<' | ge='>=' | le='<=';

terminal ID2:
	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;

terminal INT2 returns ecore::EInt:
	('0'..'9')+;

terminal STRING2:
	'"' ('\\' ('b' | 't' | 'n' | 'f' | 'r' | '"' | "'" | '\\') | !('\\' | '"'))* '"' |
	"'" ('\\' ('b' | 't' | 'n' | 'f' | 'r' | '"' | "'" | '\\') | !('\\' | "'"))* "'";

terminal ML_COMMENT2:
	'/*'->'*/';

@Override
terminal ID:
	super;