/*******************************************************************************
 * Copyright (c) 2013 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parser.bug419429.Bug419429 with org.eclipse.xtext.common.Terminals

import "http://www.eclipse.org/emf/2002/Ecore"

EReference:
	eType=[EClassifier]
;