/*
 * generated by Xtext
 */
package org.eclipse.xtext.parser.encoding.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.encoding.parser.antlr.internal.InternalEncodingTestLanguageParser;
import org.eclipse.xtext.parser.encoding.services.EncodingTestLanguageGrammarAccess;

public class EncodingTestLanguageParser extends AbstractAntlrParser {

	@Inject
	private EncodingTestLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	

	@Override
	protected InternalEncodingTestLanguageParser createParser(XtextTokenStream stream) {
		return new InternalEncodingTestLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public EncodingTestLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EncodingTestLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
