<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bug311337" nsURI="http://xtext.org/testlanguages/bug311337"
    nsPrefix="bug311337">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="def" upperBound="-1" eType="#//Definition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Definition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" upperBound="-1"
        eType="#//Child" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" upperBound="-1" eType="#//Reference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Child">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//Definition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refChild" eType="#//Child"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedRef" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Reference"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
