/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.serializer.HiddenTokenSequencerTestLanguage with org.eclipse.xtext.common.Terminals

generate hiddentokensequencertest "http://www.eclipse.org/2009/tmf/xtext/hiddentokensequencertestlanguage"

Model:
	domainModel = DomainModel
;

/* SuppressWarnings[noInstantiation] */
DomainModel:
	'entities'
		(entities+=Entity)*
	'end'
;

Entity:
	name = ID
	description = STRING
;