<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="LookaheadLang" nsURI="http://www.eclipse.org/2008/xtext/LookaheadLang" nsPrefix="LookaheadLang">
  <eClassifiers xsi:type="ecore:EClass" name="E" eSuperTypes="//B"/>
  <eClassifiers xsi:type="ecore:EClass" name="B" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="D" eSuperTypes="//B"/>
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EReference" name="x" eType="//B" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C" eSuperTypes="//B">
    <eStructuralFeatures xsi:type="ecore:EReference" name="y" eType="//D" containment="true" resolveProxies="false"/>
  </eClassifiers>
</ecore:EPackage>
