<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestLang" nsURI="http://www.eclipse.org/2008/xtext/TestLang" nsPrefix="TestLang">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TerminalElement" eSuperTypes="//ReducibleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringFeature">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChoiceElement" eSuperTypes="//AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionalKeyword">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReducibleElement" abstract="true" eSuperTypes="//AbstractElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiFeature" upperBound="-1" eType="//AbstractElement" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReducibleComposite" eSuperTypes="//ReducibleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionFeature" upperBound="-1" eType="//TerminalElement" containment="true" resolveProxies="false"/>
  </eClassifiers>
</ecore:EPackage>
