/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.testlanguages.ActionTestLanguage2 with org.eclipse.xtext.common.Terminals
 
generate actionLang2 "http://www.eclipse.org/2008/tmf/xtext/ActionLang2" 
 
// see https://www.eclipse.org/forums/index.php/mv/msg/798729/1407452/#msg_1407452
ORing :
	Value ({ORing.disjuncts+=current} '|' disjuncts+=Value)*;

Value :
	value='a';
  
 