<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xtype" nsURI="http://www.eclipse.org/xtext/xbase/Xtype" nsPrefix="xtype">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="XFunctionTypeRef" eSuperTypes="platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmSpecializedTypeReference">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paramTypes" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmType"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceContext" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XComputedTypeReference" eSuperTypes="platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmSpecializedTypeReference">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeProvider" eType="#//IJvmTypeReferenceProvider"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IJvmTypeReferenceProvider" instanceClassName="org.eclipse.xtext.xbase.typing.IJvmTypeReferenceProvider"
      serializable="false">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XImportSection">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importDeclarations" upperBound="-1"
        eType="#//XImportDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XImportDeclaration">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eOperations name="getImportedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;p>Returns the name that has been imported.&lt;/p>&#xA;&lt;p>For types and wildcard import declarations returns a qualified type name, e.g. java.lang.String.&lt;/p>&#xA;&lt;p>For member import declarations returns a qualified member name, e.g. java.lang.String.valueOf.&lt;/p>&#xA;&lt;p>"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getImportedTypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wildcard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedType" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmDeclaredType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memberName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
