<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xtype"
    nsURI="http://www.eclipse.org/xtext/xbase/Xtype" nsPrefix="xtype">
  <eClassifiers xsi:type="ecore:EClass" name="XFunctionTypeRef" eSuperTypes="../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="paramTypes" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        changeable="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        changeable="false" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
