/*******************************************************************************
 * Copyright (c) 2009, 2016 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.xtext.ecoreInference.DataTypeRuleWithEnumResultTestLanguage 
	with org.eclipse.xtext.enumrules.EnumRulesTestLanguage

import 'http://www.eclipse.org/2009/tmf/xtext/EnumRulesTest'
/* SuppressWarnings[external] */
import 'classpath:/org/eclipse/xtext/enumrules/enums.ecore'
 
@Override 
Model:
  'model' existing=ExistingEnumAsDT
;

ExistingEnumAsDT returns ExistingEnum:
  'e'
;
