<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test" nsURI="http://test" nsPrefix="test">
  <eClassifiers xsi:type="ecore:EClass" name="Optional">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionalString">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionalInt">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionalBoolean">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionalReference" eType="//Mandatory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionalMultivaluedReference" upperBound="-1" eType="//Mandatory"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mandatory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatoryString" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatoryInt" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatoryBoolean" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryReference" lowerBound="1" eType="//Optional"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryMultivaluedReference" lowerBound="1" upperBound="-1" eType="//Optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectTypes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerObject">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanObject">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
