/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.xtext.ecoreInference.UnassignedRuleCallTestLanguage with org.eclipse.xtext.common.Terminals

generate unassignedRuleCallTestLanguage "http://www.eclipse.org/2009/tmf/xtext/UnassignedRuleCallTest"
 
Model:
  'model' INT+ modelFeatures=ModelFeatures
;

ModelFeatures:
  'feature' name = ID DataTypeRule ';'
;

DataTypeRule:
  INT 'keyword' INT STRING?
;