/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.linking.AbstractIgnoreCaseLinkingTestLanguage with org.eclipse.xtext.common.Terminals

generate ignoreCaseLinkingTest "http://eclipse.org/xtext/ignoreCaseLinkingTestLanguage"

Model:
	elements += Element+
;

Element:
    name=ID reference=[Element]? '{'
    	elements += Element*
    '}'
;
	
