/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.linking.Bug289059TestLanguage with org.eclipse.xtext.common.Terminals

generate bug289059Test "http://eclipse.org/xtext/Bug289059TestLanguage"

Model:
    name=ID 
	enabled=UnassignedAction?
	reference=[Model]?
;
	
UnassignedAction:
	{UnassignedAction} "enabled";
	