/*******************************************************************************
 * Copyright (c) 2010, 2016 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.linking.IgnoreCaseNamespacesTestLanguage with org.eclipse.xtext.linking.AbstractIgnoreCaseLinkingTestLanguage

generate ignoreCaseNamespacesTest "http://eclipse.org/xtext/ignoreCaseNamespacesTestLanguage"

@Override 
Model:
	imports += Import*
	elements += Element+
;

Import:
	importedNamespace = STRING
;
