/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.linking.LangATestLanguage with org.eclipse.xtext.common.Terminals

generate langATestLanguage "http://eclipse.org/xtext/langATestLanguage"

Main : 
	imports+=Import*
	types+=Type*;
	
Import :
	'import' uri=STRING;
	
Type :
	'type' name=ID ('extends' ^extends=[Type])? ('implements' implements+=[Type] (',' implements+=[Type])*)?;