/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
 
language org.eclipse.xtext.parsetree.reconstr.ComplexReconstrTest
generate complexrewritetest "http://complex/rewrite/test"

Op returns Expression: 
	Term ({Add.addOperands+=current} '+' addOperands+=Term | {Minus.minusOperands+=current} '-' minusOperands+=Term)*;
	
Term returns Expression:
	Atom | Parens ;
	
Atom: 
	name=ID;

Parens returns Expression: 
	'(' Op ')' em='!'?;

/* TODO not working yet
StrangeStuff :
	'->' (foo=ID)? ({OtherStuff.strangeStuff=current} ',' bla=ID)? ({OtherStuff2.stuff=current} ',' bla2=ID)?;
*/


