/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.reconstr.SerializationErrorTestLanguage with org.eclipse.xtext.common.Terminals

generate serializationerror "http://www.eclipse.org/2009/tmf/xtext/serializationerror"

Model:
	test=Test | test=Parenthesis;
	
Parenthesis returns Test:
	"(" Test ")";

Test:
	TwoRequired | TwoOptions;

TwoRequired:
	"tworequired" one=ID two=ID;

TwoOptions:
	"twooptions" ("one" one=ID | "two" two=ID);
