/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
language org.eclipse.xtext.parsetree.reconstr.SimpleReconstrTest
generate simplerewritetest "http://simple/rewrite/test"

Op returns Expression: 
	Term ({Op.values+=current} values+=Term)*;
	
Term returns Expression:
	Atom | TwoNumbers | ManyStrings | Parens;
	
Atom: 
	name=ID;

Parens returns Expression: 
	'(' Op ')' em='!'?;
	
TwoNumbers:
	num1=INT num2=INT;
	
ManyStrings: '=' (str1+=STRING)* str2+=STRING; 



