/*******************************************************************************
 * Copyright (c) 2014 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.formatting2.regionaccess.internal.RegionAccessTestLanguage
with org.eclipse.xtext.common.Terminals

generate regionaccesstestlanguage "http://simple/regionaccesstestlanguage"

Root:
	"test" (Simple | Delegation | Unassigned | PrefixedUnassigned);

Simple:
	"1" name=ID;

Delegation:
	"2" delegate=Delegate;

Unassigned:
	"3" Delegate;

PrefixedUnassigned:
	"4" delegate=PrefixedDelegate;

PrefixedDelegate:
	"prefix" Delegate;

Delegate:
	name=ID;