/*******************************************************************************
 * Copyright (c) 2008, 2017 itemis AG and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0 
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.testlanguages.ContentAssistTestLanguage with org.eclipse.xtext.common.Terminals

generate contentAssistTestLanguage "http://www.eclipse.org/2008/xtext/ui/common/tests/ContentAssist"

Start :
    /* SuppressWarnings[all] */
    "abstract rules"
    	(rules += AbstractRule)+
    "end"
;

AbstractRule : FirstAbstractRuleChild | SecondAbstractRuleChild;

FirstAbstractRuleChild :
  name=ID '(' (elements+=AbstractRule)+ ')' ';';
  
SecondAbstractRuleChild:
  name=ID 'rule' ':' rule=AbstractRuleCall ';';
  
AbstractRuleCall:
  rule=[AbstractRule];
