/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.unassignedtext.UnassignedTextTestLanguage with org.eclipse.xtext.common.Terminals

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

generate unassignedtext "http://simple/unassignedtext"

Model:
	CaseInsensitiveKeywordRule | PluralRule | MultiRule | DatatypeRule | CommonTerminalsRule; 

CaseInsensitiveKeywordRule:
	CaseInsensitiveKeyword val=INT;

terminal CaseInsensitiveKeyword: 
	('k'|'K')('e'|'E')('y'|'Y')('w'|'W')('o'|'O')('r'|'R')('d'|'D');
	
	
PluralRule:
	'contents:' count=INT Plural;
	
terminal Plural:
	'item' | 'items';


MultiRule:
	'multi' val=INT Multi Multi Multi;

terminal Multi:
	'a' 'b'? 'c'+ 'd'* ('e' | 'f') (('g'|'h') | 'i'+) Multi2 '0'..'9' '0'..'9'+;
	
terminal Multi2:
	'j';


DatatypeRule:
	'datatype' val=INT Datatype;

Datatype returns ecore::EString:
	'str' | INT | Datatype2;
	
Datatype2 returns ecore::EString:
	STRING;
	

CommonTerminalsRule:
	'terminals' ID INT STRING val=ID;
