/*
 * generated by Xtext
 */
grammar DebugInternalInheritanceTest2Language ;

// Rule Model
ruleModel :
	'model' RULE_ID '{' ruleElement* ruleFQN '}'
;

// Rule Element
ruleElement :
	'element' RULE_ID
;

// Rule FQN
ruleFQN :
	RULE_ID (
		'.' RULE_ID
	)*
;

RULE_ID :
	'a' .. 'z'+
;

RULE_INT :
	'0' .. '9'+
;

RULE_STRING :
	'"' (
		'\\' . |
		~ (
			'\\' |
			'"'
		)
	)* '"' |
	'\'' (
		'\\' . |
		~ (
			'\\' |
			'\''
		)
	)* '\''
;

RULE_ML_COMMENT :
	'/*' (
		options { greedy = false ; } : .
	)* '*/' { skip(); }
;

RULE_SL_COMMENT :
	'//' ~ (
		'\n' |
		'\r'
	)* (
		'\r'? '\n'
	)? { skip(); }
;

RULE_WS :
	(
		' ' |
		'\t' |
		'\r' |
		'\n'
	)+ { skip(); }
;

RULE_ANY_OTHER :
	.
;