<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="assignmentFinderTest" nsURI="http://www.eclipse.org/2009/tmf/xtext/assignmentfindertestlanguage"
    nsPrefix="assignmentFinderTest">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keywordVal" eType="#//KeywordVal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminalVal" eType="#//TerminalVal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumVal" eType="#//EnumVal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keywordBool" eType="#//KeywordBool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminalBool" eType="#//TerminalBool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumBool" eType="#//EnumBool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mixedBool" eType="#//MixedBool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mixedValue" eType="#//MixedValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containmentRef" eType="#//ContainmentRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossRef" eType="#//CrossRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeywordVal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kw" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TerminalVal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="term" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumVal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="en" eType="#//TestEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestEnum">
    <eLiterals name="lit1" literal="lit1"/>
    <eLiterals name="lit2" value="1" literal="lit2"/>
    <eLiterals name="lit3" value="2" literal="lit3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeywordBool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kw" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TerminalBool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="term" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumBool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="en" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MixedBool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MixedValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="#//TestEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainmentRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ctx" eType="#//ContainmentRefN"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainmentRefN">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val2" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrossRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossRef" eType="#//CrossRef"/>
  </eClassifiers>
</ecore:EPackage>
