<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="syntacticsequencertest" nsURI="http://www.eclipse.org/2009/tmf/xtext/syntacticsequencertestlanguage"
    nsPrefix="syntacticsequencertest">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="x1" eType="#//MandatoryKeywords"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x2" eType="#//Exp0" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x3" eType="#//Exp1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x4" eType="#//Exp2" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x5" eType="#//SingleCrossReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x6" eType="#//BooleanAlternative"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x7" eType="#//UnassignedDatatype"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x8" eType="#//OptionalSingleTransition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x9" eType="#//OptionalManyTransition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x10" eType="#//MandatoryManyTransition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x11" eType="#//AlternativeTransition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x12" eType="#//BooleanValues"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x13" eType="#//LongAlternative"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x14" eType="#//ActionOnly"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x15" eType="#//FragmentCallerType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryKeywords">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val2" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val3" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exp0"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exp1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exp2"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleCrossReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref1" eType="#//SingleCrossReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref2" eType="#//SingleCrossReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref3" eType="#//SingleCrossReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref4" eType="#//SingleCrossReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanAlternative">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bool" eType="#//BooleanAlternativeLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanAlternativeLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTrue" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnassignedDatatype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionalSingleTransition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionalManyTransition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryManyTransition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeTransition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val2" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val3" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LongAlternative">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foo" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val1" unique="false" upperBound="-1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val2" unique="false" upperBound="-1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val3" unique="false" upperBound="-1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val4" unique="false" upperBound="-1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val5" unique="false" upperBound="-1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val6" unique="false" upperBound="-1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val7" unique="false" upperBound="-1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val8" unique="false" upperBound="-1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionOnly"/>
  <eClassifiers xsi:type="ecore:EClass" name="FragmentCallerType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fragVal" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Add0" eSuperTypes="#//Exp0">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Exp0" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Exp0"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Val0" eSuperTypes="#//Exp0">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Add1" eSuperTypes="#//Exp1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Exp1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Exp1"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Val1" eSuperTypes="#//Exp1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Add2" eSuperTypes="#//Exp2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Exp2" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Exp2"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mult2" eSuperTypes="#//Exp2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Exp2" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Exp2"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Val2" eSuperTypes="#//Exp2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
