/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.transientvalues.TransientValuesTest with org.eclipse.xtext.common.Terminals

generate transientvaluestest "http://simple/transientvaluestest"

Root:
	"test" (TestRequired | TestOptional | TestList);
	
TestRequired: 
	"required" required1=INT required2=INT;
	
TestOptional:
	"optional" opt1=INT? (":" opt2=INT)?;
	
TestList:
	"list" item+=INT*;
