
/*
 * generated by Xtext
 */
package org.eclipse.xtext.resource.metamodel;

import org.eclipse.xtext.Constants;
import org.eclipse.xtext.service.DefaultRuntimeModule;

import com.google.inject.Binder;
import com.google.inject.name.Names;

/**
 * Manual modifications go to {org.eclipse.xtext.resource.metamodel.MultiValueFeatureTestLanguageRuntimeModule}
 */
public abstract class AbstractMultiValueFeatureTestLanguageRuntimeModule extends DefaultRuntimeModule {
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(String.class).annotatedWith(Names.named(Constants.LANGUAGE_NAME)).toInstance(
			"org.eclipse.xtext.resource.metamodel.MultiValueFeatureTestLanguage");
	}

	public Class<? extends org.eclipse.xtext.IGrammarAccess> bindIGrammarAccess() {
		return org.eclipse.xtext.resource.metamodel.services.MultiValueFeatureTestLanguageGrammarAccess.class;
	}

	public Class<? extends org.eclipse.xtext.parser.packrat.IPackratParser> bindIPackratParser() {
		return org.eclipse.xtext.resource.metamodel.parser.packrat.MultiValueFeatureTestLanguagePackratParser.class;
	}

	public Class<? extends org.eclipse.xtext.parsetree.reconstr.IParseTreeConstructor> bindIParseTreeConstructor() {
		return org.eclipse.xtext.resource.metamodel.parseTreeConstruction.MultiValueFeatureTestLanguageParsetreeConstructor.class;
	}

	public Class<? extends org.eclipse.xtext.parser.antlr.Lexer> bindLexer() {
		return org.eclipse.xtext.resource.metamodel.parser.antlr.internal.InternalMultiValueFeatureTestLanguageLexer.class;
	}

	public Class<? extends org.eclipse.xtext.parser.antlr.IAntlrParser> bindIAntlrParser() {
		return org.eclipse.xtext.resource.metamodel.parser.antlr.MultiValueFeatureTestLanguageParser.class;
	}

	public Class<? extends org.eclipse.xtext.parser.antlr.ITokenDefProvider> bindITokenDefProvider() {
		return org.eclipse.xtext.parser.antlr.AntlrTokenDefProvider.class;
	}

	public Class<? extends org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider> bindIAntlrTokenFileProvider() {
		return org.eclipse.xtext.resource.metamodel.parser.antlr.MultiValueFeatureTestLanguageAntlrTokenFileProvider.class;
	}

	public Class<? extends org.eclipse.xtext.parser.ITokenToStringConverter> bindITokenToStringConverter() {
		return org.eclipse.xtext.parser.antlr.AntlrTokenToStringConverter.class;
	}
}
