/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.metamodelreferencing.tests.MultiGenMMTestLanguage with org.eclipse.xtext.common.Terminals

generate simpleTest "http://eclipse.org/xtext/tests/SimpleTest"
generate otherTest "http://eclipse.org/xtext/tests/OtherTest" as other

Foo : 
	name=ID (nameRefs+=NameRef)*;

NameRef returns other::FooBar : 
	name=STRING;