/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.lexer.IgnoreCaseLexerTestLanguage hidden(WS, SL_COMMENT) 
generate ignoreCaseTestLanguage "http://www.eclipse.org/2008/tmf/xtext/IgnoreCaseLexerTest" 
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

Model :
	"case" "foo"? value="CaSe"; 

terminal WS         : (' '|'\t'|'\r'|'\n')+;
terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;