<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bug250313" nsURI="http://org.eclipse.xtext.valueconverter.Bug250313" nsPrefix="bug250313">
  <eClassifiers xsi:type="ecore:EClass" name="Ref2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref2">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
