<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecorePerPlatformPlugin"
    nsURI="http://www.eclipse.org/2011/tmf/xtext/ecorePerPlatformPlugin" nsPrefix="ecorePerPlatformPlugin">
  <eClassifiers xsi:type="ecore:EClass" name="ExtendsPluginEObject" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObjectReference1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObjectReference2" eType="ecore:EClass EcorePerNsURI.ecore#//ExtendsNsURIEObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObjectReference3" eType="#//ExtendsPluginEObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObjectReference4" eType="ecore:EClass EcorePerPlatformResource.ecore#//ExtendsResourceEObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObjectContainment" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendsEAttribute" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
</ecore:EPackage>
