/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.metamodelreferencing.tests.MetamodelRefTestLanguage with org.eclipse.xtext.common.Terminals

import "http://www.eclipse.org/2008/Xtext" as xtext
generate anotherSimpleTest "http://eclipse.org/xtext/tests/AnotherSimpleTest"

Foo : 
	name=ID (nameRefs+=NameRef)*;

NameRef returns xtext::RuleCall : 
	rule=[xtext::ParserRule];
	
MyRule returns xtext::ParserRule :
    name=ID;