/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.metamodelreferencing.tests.MultiGenMMTestLanguage with org.eclipse.xtext.common.Terminals

generate simpleTest "http://eclipse.org/xtext/tests/SimpleTest"
generate otherTest "http://eclipse.org/xtext/tests/OtherTest" as other

Foo : 
	name=ID (nameRefs+=NameRef)*;

NameRef returns other::FooBar : 
	name=STRING;