/*******************************************************************************
 * Copyright (c) 2013 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.enumrules.MultiRuleEnumTestLanguage with org.eclipse.xtext.common.Terminals

generate multiRuleenums "http://www.eclipse.org/2009/tmf/xtext/MultiRuleEnums"
 
Model:
  'someEnum' a=EnumRuleA b=EnumRuleB c=EnumRuleC
;

enum EnumRuleA returns MyEnum:
  A | B | C
;

enum EnumRuleB returns MyEnum:
  C | D | E
;

enum EnumRuleC returns MyEnum:
  A | D | B
;

