/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.reconstr.Bug302128TestLanguage with org.eclipse.xtext.common.Terminals

generate bug302128 "http://www.eclipse.org/2009/tmf/xtext/tests/bug302123"

Model :
    (elements+=Element)*;

Element: name=Variable (value=Value)?;

Variable: ID (('.'|'-') ID)*;

terminal Value: ('='|'+='|'-=') -> '\n';
terminal SL_COMMENT: '#' !('\n'|'\r')* ('\r'? '\n')?;
