/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.reconstr.HiddenTokensMergerTestLanguage with org.eclipse.xtext.common.Terminals

generate hiddentokenmergertest "http://www.eclipse.org/2009/tmf/xtext/hiddentokensmerger"

Model:
	DatatypeBug286557 | EnumBug | Commentable | ValueList | RefList | SingleRef|  AppendToFileEnd | Action1;

DatatypeBug286557:
	'#1' name=FQN ('ref' ref=[DatatypeBug286557|FQN])? ";";
	
FQN: ID ('.' ID)*;

EnumBug:
	'#2' 'kw1' return=EnumBugEnum name=ID;
	
enum EnumBugEnum: array="array" | object="object" | resultSet="resultSet" | iterator="iterator";	

Commentable:
	'#3' item+=CommentableItem*;
	
CommentableItem:
	'item' id=ID;

ValueList:
	'#4' ids+=FQN*;
	
RefList:
	'#5' objs+=RefObj* 'refs' refs+=[RefObj|FQN]*;
	
RefObj:
	name=FQN;
	
SingleRef:
	'#6' obj=RefObj 'ref' ref=[RefObj|FQN];
	
// see https://bugs.eclipse.org/bugs/show_bug.cgi?id=297938
AppendToFileEnd:
	'#7' items+=AppendToFileEndItem*;

AppendToFileEndItem:
	'class' name=ID 'endclass';
	
Action1:
	'#8' {Action1} name=ID actions2+=Action1Sub1 actions2+=Action1Sub2;
	
Action1Sub1:
	{Action1Sub} "sub1";
	
Action1Sub2:
	{Action1SubClass} "sub2";  