/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.reconstr.TreeConstTestLanguage
   with org.eclipse.xtext.common.Terminals

generate treeConstTest "http://www.eclipse.org/2010/tmf/xtext/TreeConstTest"
 
Model: name=ID;