/*******************************************************************************
 * Copyright (c) 2015 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.parser.indentation.IndentationAwareTestLanguage with org.eclipse.xtext.common.Terminals

generate indentationAwareTestLanguage "http://www.eclipse.org/2015/tmf/xtext/indentation"
 
Tree: {Tree}
	nodes+=TreeNode*
;

TreeNode:
	name=ID
	(INDENT
		children+=TreeNode*
	DEDENT)?
;

terminal SL_COMMENT 	: '//' !('\n'|'\r')*;

terminal INDENT: 'synthetic:INDENT';
terminal DEDENT: 'synthetic:DEDENT';
