/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.ui.integration.tests.editor.bracketmatching.BmTestLanguage with org.eclipse.xtext.common.Terminals

generate bracketmatching "http://xtext.org/ui/integartion/tests/bracketmatching"

File :
	(expression+=Expression)*;
	
Expression :
  SExpression |
  Atom |
  "[" Expression "]";
	
SExpression:
    {SExpression}
    ("("
      element+=Expression* 
    ")" |
    "begin"
      element+=Expression* 
    "end"
    );
    
Atom :
  value=VALUE;
  
VALUE : ID|INT|STRING;