/*******************************************************************************
 * Copyright (c) 2008, 2017 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parser.assignments.Bug288432TestLanguage with org.eclipse.xtext.common.Terminals

generate bug288432Test "http://www.eclipse.org/2008/tmf/xtext/Bug288432Test"

Body :
	('(' parameter+=(Parameter) (',' parameter+=(Parameter))* ')')?
	'body'
	content=(Content|ParameterRef)
	(foo+=Foo)+
	/* SuppressWarnings[SpacesInKeyword] */
	'end body';
	
Foo:
	fooValue = STRING;
	
Content :
	'content' MyElement 
	/* SuppressWarnings[SpacesInKeyword] */
	'end content' ;
	
MyElement :
	'element' bar=(MyInt|ParameterRef);   
	
ParameterObject :
	MyInt | Content | ParameterRef    ; 

Parameter:
	name=ID
	(value=[ParameterObject])?;

ParameterRef:
	parameter=[Parameter];

MyInt :
	int=INT;
