/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parser.terminalrules.Bug292245TestLanguage

import "http://www.eclipse.org/emf/2002/Ecore" as ecore
generate bug292245TestLanguage "http://www.eclipse.org/2008/tmf/xtext/Bug292245TestLanguage"
 
Model hidden(WS) : ('FIX' (fix+=Fix)+
               |'ERROR' (error+=Error)+
               |'TICK' (tick+=Apostrophe)+
               )*;

Error hidden() : APOSTROPHE_CHAR Graphical APOSTROPHE_CHAR;
Fix   hidden() : APOSTROPHE_CHAR Graphical APOSTROPHE_CHAR Rehide;

Apostrophe hidden(WS) : APOSTROPHE_CHAR;
terminal APOSTROPHE_CHAR : "'";

Rehide hidden(WS) : "^"?; //some unused char

Graphical : CHAR | WS;
terminal CHAR : 'A'..'Z' | '0'..'9';
terminal WS : (' '|'\t'|'\r'|'\n')+ ;
 