/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parser.terminalrules.Bug317840TestLanguage with org.eclipse.xtext.common.Terminals

generate bug317840TestLanguage "http://www.eclipse.org/2010/tmf/xtext/Bug317840TestLanguage"
 
Model:
	elements+=Element*
;

Element:
	"element" first=Named second=Named? (third+=Named forth+=Named)*
;

Named:
	name = NAME
;

NAME hidden():
	ID ('.' ID)*
;


 