/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.parser.terminalrules.EcoreTerminalsTestLanguage hidden(WS)

import "http://www.eclipse.org/emf/2002/Ecore" as ecore
generate ecoreTerminalsTestLanguage "http://www.eclipse.org/2008/tmf/xtext/ECoreTerminalsTest"

Model:
	('int' intValues+=EINT
	| 'double' doubleValues+=EDOUBLE
	| 'date' dateValues+=EDATE)*;

terminal EDOUBLE returns ecore::EDouble:
	('.' ('0'..'9')+ | ('0'..'9')+ '.' ('0'..'9')*) (('E'|'e') ('-' | '+'?) ('0'..'9')+)?;

// the default ecore date format is  "yyyy-MM-dd'T'HH:mm:ss'.'SSSZ"
terminal EDATE returns ecore::EDate:
	('0'..'9')('0'..'9')('0'..'9')('0'..'9')'-'('0'..'9')('0'..'9')'-'('0'..'9')('0'..'9')
	'T'('0'..'9')('0'..'9')':'('0'..'9')('0'..'9')':'('0'..'9')('0'..'9')'.'('0'..'9')('0'..'9')('0'..'9')
	('+'|'-')('0'..'9')('0'..'9')('0'..'9')('0'..'9');

terminal EINT returns ecore::EInt:
	'-'? ('0'..'9')+;
	
terminal WS: 
	(' '|'\t'|'\r'|'\n')+;