<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test"
    nsURI="hrrp://www.xtext.org/ui/tests/referenceDescriptionTest" nsPrefix="test">
  <eClassifiers xsi:type="ecore:EClass" name="Referrer" eSuperTypes="#//Referenced">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Referenced"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Referenced"/>
</ecore:EPackage>
