<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lookaheadLang" nsURI="http://www.eclipse.org/2008/xtext/LookaheadLang"
    nsPrefix="lookaheadLang">
  <eClassifiers xsi:type="ecore:EClass" name="Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//Alts" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alts">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LookAhead0" eSuperTypes="#//Alts"/>
  <eClassifiers xsi:type="ecore:EClass" name="LookAhead1" eSuperTypes="#//Alts">
    <eStructuralFeatures xsi:type="ecore:EReference" name="y" eType="#//LookAhead2"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LookAhead2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LookAhead3" eSuperTypes="#//Alts">
    <eStructuralFeatures xsi:type="ecore:EReference" name="z" eType="#//LookAhead4"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LookAhead4">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
