/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.parser.encoding.EncodingTestLanguage hidden(WS)

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

generate encodingTest "http://www.eclipse.org/2010/tmf/xtext/parser/EncodingTest"

Model:
	(words+=Word)*;
	
Word:
	value=LEXEME;
	
terminal LEXEME : ('a'..'z' | 'A'..'Z' | '0'..'9' | 'ä' | 'ö' | 'ü' | 'ß' | 'Ä' | 'Ö' | 'Ü' )*;

terminal WS	: (' '|'\t'|'\r'|'\n')+;

terminal ANY_OTHER: .;