/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
language org.eclipse.xtext.parsetree.formatter.FormatterTestLanguage
generate formattertestlanguage "http://simple/formattertestlanguage"

Root:
	"test" (TestLinewrap | TestIndentation);
	
Line:
	type+=ID name+=ID ";";
	
TestLinewrap:
	"linewrap" items+=Line*;
	
TestIndentation:
	"indentation" "{" (sub+=TestIndentation | items+=Line)* "}"; 
