/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.formatter.FormatterTestLanguage with org.eclipse.xtext.common.Terminals

generate formattertestlanguage "http://simple/formattertestlanguage"

Root:
	"test" (TestLinewrap | TestIndentation);
	
Line:
	(Decl | Assign | Meth) ";";
	
Decl:	
	type+=ID name+=ID;
	
Assign:
	var=ID op=("="|"+=") "[" (val+=INT ("," val+=INT)*)? "]";
	
Meth:
	"void" name=ID "(" (param+=Param ("," param+=Param)*)? ")";
	
Param:
	name+=ID ":" type+=ID;
	
TestLinewrap:
	"linewrap" items+=Line*;
	
TestIndentation:
	"indentation" "{" (sub+=TestIndentation | items+=Line)* "}" semi?=";"?; 
