/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parser.terminalrules.Bug297105TestLanguage with org.eclipse.xtext.common.Terminals

import "http://www.eclipse.org/emf/2002/Ecore" as ecore
generate bug297105TestLanguage "http://www.eclipse.org/2008/tmf/xtext/Bug297105TestLanguage"
 
Model: 
    expressions += Expression* 
;

Expression : left=Literal '+' right=Literal; 

Literal : RealLiteral | IntLiteral;
IntLiteral : value = IntValue ;
RealLiteral : value = RealValue;

IntValue : INT ;
RealValue : Real ;

Real hidden(): INT ? '.' (EXT_INT | INT);
terminal EXT_INT: INT ('e'|'E')('-'|'+') INT;

 