/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
language org.eclipse.xtext.metamodelreferencing.tests.MetamodelRefTestLanguage

import 				"http://www.eclipse.org/2008/Xtext" 		as xtext
generate anotherSimpleTest "http://eclipse.org/xtext/tests/AnotherSimpleTest"

Foo : 
	name=ID (nameRefs+=NameRef)*;

NameRef returns xtext::RuleCall : 
	rule=[ParserRule];
	
MyRule returns xtext::ParserRule :
    name=ID;