/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.linking.Bug287988TestLanguage with org.eclipse.xtext.common.Terminals

generate bug287988Test "http://eclipse.org/xtext/Bug287988TestLanguage"

Model:
    ('actions' attributes+=BaseAttribute*)
  | ('simple' attributes+=SimpleAttribute*)
  | ('rulecall' attributes+=RuleCallAttribute*)
  | ('rulecall2' attributes+=RuleCallAttribute2*)
  | ('rulecall3' attributes+=RuleCallAttribute3*)
  | ('inlinedActions' attributes+=ActionAttribute*);

BaseAttribute:
  (Attribute|Master) ("ref" typeRef=[BaseAttribute]|type=ID) name=ID ";";

Attribute:
  {Attribute} "attribute";

Master:
  {Master} "master";
  
ActionAttribute returns BaseAttribute:
  ({Attribute} "attribute"|{Master} "master") ("ref" typeRef=[BaseAttribute]|type=ID) name=ID ";";
 
SimpleAttribute returns Attribute:
  ("ref" typeRef=[BaseAttribute]|type=ID) name=ID ";";
  
RuleCallAttribute returns Attribute:
  CallMe name=ID ";";

CallMe returns Attribute:
  ("ref" typeRef=[BaseAttribute]|type=ID);

RuleCallAttribute2 returns Attribute:
  CallMe2 ("ref" typeRef=[BaseAttribute]|type=ID) ";";

CallMe2 returns Attribute:
  name=ID;
  
RuleCallAttribute3 returns Attribute:
  CallMe3 ("ref" typeRef=[BaseAttribute]|type=ID) ";";

CallMe3 returns Attribute:
  "call" "me" CallMe4;
  
CallMe4 returns Attribute:
  name=ID;