/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.linking.IgnoreCaseNamespacesTestLanguage with org.eclipse.xtext.linking.AbstractIgnoreCaseLinkingTestLanguage

generate ignoreCaseNamespacesTest "http://eclipse.org/xtext/ignoreCaseNamespacesTestLanguage"

Model:
	imports += Import*
	elements += Element+
;

Import:
	importedNamespace = STRING
;
