/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
abstract language org.eclipse.xtext.inheritance.AbstractBaseLanguage

lexing :

MY_SPECIAL1 : "'special1'";
MY_SPECIAL2 returns ecore::EJavaObject: "'special2'";