/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
language org.eclipse.xtext.inheritance.ConcreteSubLanguage extends org.eclipse.xtext.inheritance.AbstractBaseLanguage

Model : s1=MY_SPECIAL1 s2=MY_SPECIAL2 s3=MY_SPECIAL3;

lexing:

MY_SPECIAL3 : "'special3'";
