/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.validation;

import org.eclipse.xtext.xbase.testlanguages.validation.AbstractXImportSectionTestLangValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class XImportSectionTestLangValidator extends AbstractXImportSectionTestLangValidator {
}
