/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.parser.antlr.Bug289515TestLanguage with org.eclipse.xtext.common.Terminals

generate bug289515Test "http://eclipse.org/xtext/Bug289515TestLanguage"

Model: 
    '1' value="%" 
  | '2' value='%' 
  | '3' value="\\%" 
  | '4' value='\\%' 
  | '5' value="%%" 
  | '6' value='%%';
	