/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.parser.antlr.Bug289524ExTestLanguage with org.eclipse.xtext.common.Terminals

generate bug289524ExTest "http://eclipse.org/xtext/Bug289524ExTestLanguage"

Model: {Model} "Model" (refs+=ModelElement)*;
ModelElement: {ModelElement} ( containments+=Contained | "reference" refs+=[Contained]  ("$" refs+=[Contained])* )+;
Contained: "containment" name=ID;