/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.resource.EObjectAtOffsetTestLanguage with org.eclipse.xtext.common.Terminals

generate eObjectAtOffsetTestLanguage "http://www.xtext.org/EObjectAtOffsetTestLanguage" 

Model:
	(foos+=Foo | bars+=AbstractBar)*;
	
AbstractBar:
	'zonk'? INT? Bar ({FooBar.bar=current} 'foobar' foo+=[Foo|QualifiedNameWithOtherDelim])? foo+=[Foo|QualifiedNameWithOtherDelim]?;

Bar:
	'bar' name=ID foo+=[Foo|QualifiedNameWithOtherDelim] (',' foo+=[Foo|QualifiedNameWithOtherDelim])*;
	
Foo:
	'foo' name=QualifiedNameWithOtherDelim;

QualifiedNameWithOtherDelim :
	QualifiedName ('=' QualifiedName)*
;

QualifiedName :
	ID ('.' ID)*
;
