/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.resource.LocationProviderTestLanguage with org.eclipse.xtext.common.Terminals

generate locationprovidertest "http://www.xtext.org/locationProviderTestLaguage"

Model :
	(elements+=Element)*
	(components+=Component)*;
	
Element :
	"element" name=ID ("singleref" singleref=[Element])? ("multiref" multirefs+=[Element])*;
	
Component :
	(Bus | Processor)
	('modes' (mode+=Mode |
		transition+=Transition)+
	)?
	'end' ';'
;

Bus:
	'bus' name = ID
	(port+=Port)*
;

Processor:
	'processor' name = ID
	(data+=Data)*
;

Mode :
	'mode' name = ID ';'
;

Transition:
	name=ID ':' source=[Mode] '->' destination=[Mode] ';'
;

Port:
	'port' name = ID ';'
;

Data:
	'data' name = ID ';'
;
	