<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore2xtext"
    nsURI="http://www.eclipse.org/xtext/ecore2xtext" nsPrefix="ecore2xtext">
  <eClassifiers xsi:type="ecore:EClass" name="Abstract" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concrete0" eSuperTypes="#//Abstract"/>
  <eClassifiers xsi:type="ecore:EClass" name="Concrete1" eSuperTypes="#//Abstract"/>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Abstract" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//INT" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concrete0" eType="#//Concrete0"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="INT" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiamondInheritance" eSuperTypes="#//Concrete0 #//Concrete1"/>
</ecore:EPackage>
