/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui.tests.enumrules.ide;


/**
 * Use this class to register ide components.
 */
public class EnumRulesUiTestLanguageIdeModule extends AbstractEnumRulesUiTestLanguageIdeModule {
}
