/*******************************************************************************
 * Copyright (c) 2013 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parser.bug419429.Bug419429 with org.eclipse.xtext.common.Terminals

import "http://www.eclipse.org/emf/2002/Ecore"

EReference:
	eType=[EClassifier]
;