grammar org.eclipse.xtext.junit4.parameterized.ParameterizedXtextRunner 

generate pkg "http://org.eclipse.xtext.junit4.parameterized.ParameterizedXtextRunner"

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

	// XPECT plain
	// XPECT plain

	// XPECT string --> My long String expectation
	/* XPECT string ---
 		My long String expectation  
	---	*/
	
	/* XPECT csv ---
		aaa, bbb, ccc, ddd, eee, fff, ggg, hhh, iii, jjj, kkk, lll,
		mmm, nnn, ooo, ppp, qqq, rrr
	---	*/
	
	/* XPECT lines ---
	aaa bbb ccc
	foo bar baz
	xxx yyy zzz
	---	*/
	
	// XPECT select1 from fo|o to b|az --> o='val' bar='val1' b
	// XPECT select2 from fo|o to b|az --> o='val' bar='val1' b

Root:
	foo='val' bar='val1' baz='xxx'
;