/*
* generated by Xtext
*/
grammar InternalEpatchTestLanguage;

options {
	superClass=AbstractInternalAntlrParser;
	
}

@lexer::header {
package org.eclipse.xtext.parser.epatch.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.eclipse.xtext.parser.epatch.parser.antlr.internal; 

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.xtext.parsetree.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.eclipse.xtext.conversion.ValueConverterException;
import org.eclipse.xtext.parser.epatch.services.EpatchTestLanguageGrammarAccess;

}

@parser::members {

 	private EpatchTestLanguageGrammarAccess grammarAccess;
 	
    public InternalEpatchTestLanguageParser(TokenStream input, IAstFactory factory, EpatchTestLanguageGrammarAccess grammarAccess) {
        this(input);
        this.factory = factory;
        registerRules(grammarAccess.getGrammar());
        this.grammarAccess = grammarAccess;
    }
    
    @Override
    protected String getFirstRuleName() {
    	return "EPatch";	
   	}
   	
   	@Override
   	protected EpatchTestLanguageGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}
}

@rulecatch { 
    catch (RecognitionException re) { 
        recover(input,re); 
        appendSkippedTokens();
    } 
}




// Entry rule entryRuleEPatch
entryRuleEPatch returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getEPatchRule(), currentNode); }
	 iv_ruleEPatch=ruleEPatch 
	 { $current=$iv_ruleEPatch.current; } 
	 EOF 
;

// Rule EPatch
ruleEPatch returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(	otherlv_0='epatch' 
    {
    	createLeafNode(otherlv_0, grammarAccess.getEPatchAccess().getEpatchKeyword_0(), null);
    }
(
(
		lv_name_1_0=RULE_ID
		{
			createLeafNode(lv_name_1_0, grammarAccess.getEPatchAccess().getNameIDTerminalRuleCall_1_0(), "name"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getEPatchRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"name",
	        		lv_name_1_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_2='{' 
    {
    	createLeafNode(otherlv_2, grammarAccess.getEPatchAccess().getLeftCurlyBracketKeyword_2(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getEPatchAccess().getImportsImportParserRuleCall_3_0(), currentNode); 
	    }
		lv_imports_3_0=ruleImport		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getEPatchRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"imports",
	        		lv_imports_3_0, 
	        		"Import", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)*(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getEPatchAccess().getResourcesNamedResourceParserRuleCall_4_0(), currentNode); 
	    }
		lv_resources_4_0=ruleNamedResource		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getEPatchRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"resources",
	        		lv_resources_4_0, 
	        		"NamedResource", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)*(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getEPatchAccess().getObjectsObjectRefParserRuleCall_5_0(), currentNode); 
	    }
		lv_objects_5_0=ruleObjectRef		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getEPatchRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"objects",
	        		lv_objects_5_0, 
	        		"ObjectRef", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)*	otherlv_6='}' 
    {
    	createLeafNode(otherlv_6, grammarAccess.getEPatchAccess().getRightCurlyBracketKeyword_6(), null);
    }
)
;





// Entry rule entryRuleImport
entryRuleImport returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getImportRule(), currentNode); }
	 iv_ruleImport=ruleImport 
	 { $current=$iv_ruleImport.current; } 
	 EOF 
;

// Rule Import
ruleImport returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(
    { 
        currentNode=createCompositeNode(grammarAccess.getImportAccess().getModelImportParserRuleCall_0(), currentNode); 
    }
    this_ModelImport_0=ruleModelImport
    { 
        $current = $this_ModelImport_0.current; 
        currentNode = currentNode.getParent();
    }

    |
    { 
        currentNode=createCompositeNode(grammarAccess.getImportAccess().getJavaImportParserRuleCall_1(), currentNode); 
    }
    this_JavaImport_1=ruleJavaImport
    { 
        $current = $this_JavaImport_1.current; 
        currentNode = currentNode.getParent();
    }

    |
    { 
        currentNode=createCompositeNode(grammarAccess.getImportAccess().getExtensionImportParserRuleCall_2(), currentNode); 
    }
    this_ExtensionImport_2=ruleExtensionImport
    { 
        $current = $this_ExtensionImport_2.current; 
        currentNode = currentNode.getParent();
    }
)
;





// Entry rule entryRuleModelImport
entryRuleModelImport returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getModelImportRule(), currentNode); }
	 iv_ruleModelImport=ruleModelImport 
	 { $current=$iv_ruleModelImport.current; } 
	 EOF 
;

// Rule ModelImport
ruleModelImport returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(
    { 
        currentNode=createCompositeNode(grammarAccess.getModelImportAccess().getResourceImportParserRuleCall_0(), currentNode); 
    }
    this_ResourceImport_0=ruleResourceImport
    { 
        $current = $this_ResourceImport_0.current; 
        currentNode = currentNode.getParent();
    }

    |
    { 
        currentNode=createCompositeNode(grammarAccess.getModelImportAccess().getEPackageImportParserRuleCall_1(), currentNode); 
    }
    this_EPackageImport_1=ruleEPackageImport
    { 
        $current = $this_EPackageImport_1.current; 
        currentNode = currentNode.getParent();
    }
)
;





// Entry rule entryRuleResourceImport
entryRuleResourceImport returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getResourceImportRule(), currentNode); }
	 iv_ruleResourceImport=ruleResourceImport 
	 { $current=$iv_ruleResourceImport.current; } 
	 EOF 
;

// Rule ResourceImport
ruleResourceImport returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(	otherlv_0='import' 
    {
    	createLeafNode(otherlv_0, grammarAccess.getResourceImportAccess().getImportKeyword_0(), null);
    }
(
(
		lv_name_1_0=RULE_ID
		{
			createLeafNode(lv_name_1_0, grammarAccess.getResourceImportAccess().getNameIDTerminalRuleCall_1_0(), "name"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getResourceImportRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"name",
	        		lv_name_1_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_2='uri' 
    {
    	createLeafNode(otherlv_2, grammarAccess.getResourceImportAccess().getUriKeyword_2(), null);
    }
(
(
		lv_uri_3_0=RULE_STRING
		{
			createLeafNode(lv_uri_3_0, grammarAccess.getResourceImportAccess().getUriSTRINGTerminalRuleCall_3_0(), "uri"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getResourceImportRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"uri",
	        		lv_uri_3_0, 
	        		"STRING", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
))
;





// Entry rule entryRuleEPackageImport
entryRuleEPackageImport returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getEPackageImportRule(), currentNode); }
	 iv_ruleEPackageImport=ruleEPackageImport 
	 { $current=$iv_ruleEPackageImport.current; } 
	 EOF 
;

// Rule EPackageImport
ruleEPackageImport returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(	otherlv_0='import' 
    {
    	createLeafNode(otherlv_0, grammarAccess.getEPackageImportAccess().getImportKeyword_0(), null);
    }
(
(
		lv_name_1_0=RULE_ID
		{
			createLeafNode(lv_name_1_0, grammarAccess.getEPackageImportAccess().getNameIDTerminalRuleCall_1_0(), "name"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getEPackageImportRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"name",
	        		lv_name_1_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_2='ns' 
    {
    	createLeafNode(otherlv_2, grammarAccess.getEPackageImportAccess().getNsKeyword_2(), null);
    }
(
(
		lv_nsURI_3_0=RULE_STRING
		{
			createLeafNode(lv_nsURI_3_0, grammarAccess.getEPackageImportAccess().getNsURISTRINGTerminalRuleCall_3_0(), "nsURI"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getEPackageImportRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"nsURI",
	        		lv_nsURI_3_0, 
	        		"STRING", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
))
;





// Entry rule entryRuleJavaImport
entryRuleJavaImport returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getJavaImportRule(), currentNode); }
	 iv_ruleJavaImport=ruleJavaImport 
	 { $current=$iv_ruleJavaImport.current; } 
	 EOF 
;

// Rule JavaImport
ruleJavaImport returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(	otherlv_0='import' 
    {
    	createLeafNode(otherlv_0, grammarAccess.getJavaImportAccess().getImportKeyword_0(), null);
    }
	otherlv_1='java' 
    {
    	createLeafNode(otherlv_1, grammarAccess.getJavaImportAccess().getJavaKeyword_1(), null);
    }
(
(
		lv_path_2_0=RULE_ID
		{
			createLeafNode(lv_path_2_0, grammarAccess.getJavaImportAccess().getPathIDTerminalRuleCall_2_0(), "path"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getJavaImportRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"path",
	        		lv_path_2_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)(	otherlv_3='.' 
    {
    	createLeafNode(otherlv_3, grammarAccess.getJavaImportAccess().getFullStopKeyword_3_0(), null);
    }
(
(
		lv_path_4_0=RULE_ID
		{
			createLeafNode(lv_path_4_0, grammarAccess.getJavaImportAccess().getPathIDTerminalRuleCall_3_1_0(), "path"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getJavaImportRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"path",
	        		lv_path_4_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
))*)
;





// Entry rule entryRuleExtensionImport
entryRuleExtensionImport returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getExtensionImportRule(), currentNode); }
	 iv_ruleExtensionImport=ruleExtensionImport 
	 { $current=$iv_ruleExtensionImport.current; } 
	 EOF 
;

// Rule ExtensionImport
ruleExtensionImport returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(	otherlv_0='import' 
    {
    	createLeafNode(otherlv_0, grammarAccess.getExtensionImportAccess().getImportKeyword_0(), null);
    }
	otherlv_1='extension' 
    {
    	createLeafNode(otherlv_1, grammarAccess.getExtensionImportAccess().getExtensionKeyword_1(), null);
    }
(
(
		lv_path_2_0=RULE_ID
		{
			createLeafNode(lv_path_2_0, grammarAccess.getExtensionImportAccess().getPathIDTerminalRuleCall_2_0(), "path"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getExtensionImportRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"path",
	        		lv_path_2_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)(	otherlv_3='::' 
    {
    	createLeafNode(otherlv_3, grammarAccess.getExtensionImportAccess().getColonColonKeyword_3_0(), null);
    }
(
(
		lv_path_4_0=RULE_ID
		{
			createLeafNode(lv_path_4_0, grammarAccess.getExtensionImportAccess().getPathIDTerminalRuleCall_3_1_0(), "path"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getExtensionImportRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"path",
	        		lv_path_4_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
))*)
;





// Entry rule entryRuleNamedResource
entryRuleNamedResource returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getNamedResourceRule(), currentNode); }
	 iv_ruleNamedResource=ruleNamedResource 
	 { $current=$iv_ruleNamedResource.current; } 
	 EOF 
;

// Rule NamedResource
ruleNamedResource returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(	otherlv_0='resource' 
    {
    	createLeafNode(otherlv_0, grammarAccess.getNamedResourceAccess().getResourceKeyword_0(), null);
    }
(
(
		lv_name_1_0=RULE_ID
		{
			createLeafNode(lv_name_1_0, grammarAccess.getNamedResourceAccess().getNameIDTerminalRuleCall_1_0(), "name"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getNamedResourceRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"name",
	        		lv_name_1_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_2='{' 
    {
    	createLeafNode(otherlv_2, grammarAccess.getNamedResourceAccess().getLeftCurlyBracketKeyword_2(), null);
    }
	otherlv_3='left' 
    {
    	createLeafNode(otherlv_3, grammarAccess.getNamedResourceAccess().getLeftKeyword_3(), null);
    }
((	otherlv_4='uri' 
    {
    	createLeafNode(otherlv_4, grammarAccess.getNamedResourceAccess().getUriKeyword_4_0_0(), null);
    }
(
(
		lv_leftUri_5_0=RULE_STRING
		{
			createLeafNode(lv_leftUri_5_0, grammarAccess.getNamedResourceAccess().getLeftUriSTRINGTerminalRuleCall_4_0_1_0(), "leftUri"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getNamedResourceRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"leftUri",
	        		lv_leftUri_5_0, 
	        		"STRING", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
))
    |(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getNamedResourceAccess().getLeftRootCreatedObjectParserRuleCall_4_1_0(), currentNode); 
	    }
		lv_leftRoot_6_0=ruleCreatedObject		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getNamedResourceRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"leftRoot",
	        		lv_leftRoot_6_0, 
	        		"CreatedObject", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
))	otherlv_7=';' 
    {
    	createLeafNode(otherlv_7, grammarAccess.getNamedResourceAccess().getSemicolonKeyword_5(), null);
    }
	otherlv_8='right' 
    {
    	createLeafNode(otherlv_8, grammarAccess.getNamedResourceAccess().getRightKeyword_6(), null);
    }
((	otherlv_9='uri' 
    {
    	createLeafNode(otherlv_9, grammarAccess.getNamedResourceAccess().getUriKeyword_7_0_0(), null);
    }
(
(
		lv_rightUri_10_0=RULE_STRING
		{
			createLeafNode(lv_rightUri_10_0, grammarAccess.getNamedResourceAccess().getRightUriSTRINGTerminalRuleCall_7_0_1_0(), "rightUri"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getNamedResourceRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"rightUri",
	        		lv_rightUri_10_0, 
	        		"STRING", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
))
    |(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getNamedResourceAccess().getRightRootCreatedObjectParserRuleCall_7_1_0(), currentNode); 
	    }
		lv_rightRoot_11_0=ruleCreatedObject		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getNamedResourceRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"rightRoot",
	        		lv_rightRoot_11_0, 
	        		"CreatedObject", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
))	otherlv_12=';' 
    {
    	createLeafNode(otherlv_12, grammarAccess.getNamedResourceAccess().getSemicolonKeyword_8(), null);
    }
	otherlv_13='}' 
    {
    	createLeafNode(otherlv_13, grammarAccess.getNamedResourceAccess().getRightCurlyBracketKeyword_9(), null);
    }
)
;







// Entry rule entryRuleObjectRef
entryRuleObjectRef returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getObjectRefRule(), currentNode); }
	 iv_ruleObjectRef=ruleObjectRef 
	 { $current=$iv_ruleObjectRef.current; } 
	 EOF 
;

// Rule ObjectRef
ruleObjectRef returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(	otherlv_0='object' 
    {
    	createLeafNode(otherlv_0, grammarAccess.getObjectRefAccess().getObjectKeyword_0(), null);
    }
(
(
		lv_name_1_0=RULE_ID
		{
			createLeafNode(lv_name_1_0, grammarAccess.getObjectRefAccess().getNameIDTerminalRuleCall_1_0(), "name"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectRefRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"name",
	        		lv_name_1_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)?(((
(
		{
			if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectRefRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
        }
	otherlv_2=RULE_ID
	{
		createLeafNode(otherlv_2, grammarAccess.getObjectRefAccess().getLeftResNamedResourceCrossReference_2_0_0_0(), "leftRes"); 
	}

)
)(
(
		lv_leftFrag_3_0=RULE_FRAGMENT
		{
			createLeafNode(lv_leftFrag_3_0, grammarAccess.getObjectRefAccess().getLeftFragFRAGMENTTerminalRuleCall_2_0_1_0(), "leftFrag"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectRefRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"leftFrag",
	        		lv_leftFrag_3_0, 
	        		"FRAGMENT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
))
    |(	otherlv_4='left' 
    {
    	createLeafNode(otherlv_4, grammarAccess.getObjectRefAccess().getLeftKeyword_2_1_0(), null);
    }
(
(
		{
			if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectRefRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
        }
	otherlv_5=RULE_ID
	{
		createLeafNode(otherlv_5, grammarAccess.getObjectRefAccess().getLeftResNamedResourceCrossReference_2_1_1_0(), "leftRes"); 
	}

)
)(
(
		lv_leftFrag_6_0=RULE_FRAGMENT
		{
			createLeafNode(lv_leftFrag_6_0, grammarAccess.getObjectRefAccess().getLeftFragFRAGMENTTerminalRuleCall_2_1_2_0(), "leftFrag"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectRefRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"leftFrag",
	        		lv_leftFrag_6_0, 
	        		"FRAGMENT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_7='right' 
    {
    	createLeafNode(otherlv_7, grammarAccess.getObjectRefAccess().getRightKeyword_2_1_3(), null);
    }
(
(
		{
			if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectRefRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
        }
	otherlv_8=RULE_ID
	{
		createLeafNode(otherlv_8, grammarAccess.getObjectRefAccess().getRightResNamedResourceCrossReference_2_1_4_0(), "rightRes"); 
	}

)
)(
(
		lv_rightFrag_9_0=RULE_FRAGMENT
		{
			createLeafNode(lv_rightFrag_9_0, grammarAccess.getObjectRefAccess().getRightFragFRAGMENTTerminalRuleCall_2_1_5_0(), "rightFrag"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectRefRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"rightFrag",
	        		lv_rightFrag_9_0, 
	        		"FRAGMENT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)))(	otherlv_10='{' 
    {
    	createLeafNode(otherlv_10, grammarAccess.getObjectRefAccess().getLeftCurlyBracketKeyword_3_0(), null);
    }
((
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getObjectRefAccess().getAssignmentsBiSingleAssignmentParserRuleCall_3_1_0_0(), currentNode); 
	    }
		lv_assignments_11_0=ruleBiSingleAssignment		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectRefRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"assignments",
	        		lv_assignments_11_0, 
	        		"BiSingleAssignment", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)
    |(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getObjectRefAccess().getAssignmentsBiListAssignmentParserRuleCall_3_1_1_0(), currentNode); 
	    }
		lv_assignments_12_0=ruleBiListAssignment		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectRefRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"assignments",
	        		lv_assignments_12_0, 
	        		"BiListAssignment", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
))+(	otherlv_13='left' 
    {
    	createLeafNode(otherlv_13, grammarAccess.getObjectRefAccess().getLeftKeyword_3_2_0(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getObjectRefAccess().getLeftMigMigrationParserRuleCall_3_2_1_0(), currentNode); 
	    }
		lv_leftMig_14_0=ruleMigration		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectRefRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"leftMig",
	        		lv_leftMig_14_0, 
	        		"Migration", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
))?(	otherlv_15='right' 
    {
    	createLeafNode(otherlv_15, grammarAccess.getObjectRefAccess().getRightKeyword_3_3_0(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getObjectRefAccess().getRightMigMigrationParserRuleCall_3_3_1_0(), currentNode); 
	    }
		lv_rightMig_16_0=ruleMigration		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectRefRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"rightMig",
	        		lv_rightMig_16_0, 
	        		"Migration", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
))?	otherlv_17='}' 
    {
    	createLeafNode(otherlv_17, grammarAccess.getObjectRefAccess().getRightCurlyBracketKeyword_3_4(), null);
    }
)?)
;







// Entry rule entryRuleBiSingleAssignment
entryRuleBiSingleAssignment returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getBiSingleAssignmentRule(), currentNode); }
	 iv_ruleBiSingleAssignment=ruleBiSingleAssignment 
	 { $current=$iv_ruleBiSingleAssignment.current; } 
	 EOF 
;

// Rule BiSingleAssignment
ruleBiSingleAssignment returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
((
(
		lv_feature_0_0=RULE_ID
		{
			createLeafNode(lv_feature_0_0, grammarAccess.getBiSingleAssignmentAccess().getFeatureIDTerminalRuleCall_0_0(), "feature"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getBiSingleAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"feature",
	        		lv_feature_0_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_1='=' 
    {
    	createLeafNode(otherlv_1, grammarAccess.getBiSingleAssignmentAccess().getEqualsSignKeyword_1(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getBiSingleAssignmentAccess().getLeftValueSingleAssignmentValueParserRuleCall_2_0(), currentNode); 
	    }
		lv_leftValue_2_0=ruleSingleAssignmentValue		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getBiSingleAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"leftValue",
	        		lv_leftValue_2_0, 
	        		"SingleAssignmentValue", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)	otherlv_3='|' 
    {
    	createLeafNode(otherlv_3, grammarAccess.getBiSingleAssignmentAccess().getVerticalLineKeyword_3(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getBiSingleAssignmentAccess().getRightValueSingleAssignmentValueParserRuleCall_4_0(), currentNode); 
	    }
		lv_rightValue_4_0=ruleSingleAssignmentValue		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getBiSingleAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"rightValue",
	        		lv_rightValue_4_0, 
	        		"SingleAssignmentValue", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)	otherlv_5=';' 
    {
    	createLeafNode(otherlv_5, grammarAccess.getBiSingleAssignmentAccess().getSemicolonKeyword_5(), null);
    }
)
;





// Entry rule entryRuleBiListAssignment
entryRuleBiListAssignment returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getBiListAssignmentRule(), currentNode); }
	 iv_ruleBiListAssignment=ruleBiListAssignment 
	 { $current=$iv_ruleBiListAssignment.current; } 
	 EOF 
;

// Rule BiListAssignment
ruleBiListAssignment returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
((
(
		lv_feature_0_0=RULE_ID
		{
			createLeafNode(lv_feature_0_0, grammarAccess.getBiListAssignmentAccess().getFeatureIDTerminalRuleCall_0_0(), "feature"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getBiListAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"feature",
	        		lv_feature_0_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_1='=' 
    {
    	createLeafNode(otherlv_1, grammarAccess.getBiListAssignmentAccess().getEqualsSignKeyword_1(), null);
    }
	otherlv_2='[' 
    {
    	createLeafNode(otherlv_2, grammarAccess.getBiListAssignmentAccess().getLeftSquareBracketKeyword_2(), null);
    }
((
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getBiListAssignmentAccess().getLeftValuesListAssignmentValueParserRuleCall_3_0_0(), currentNode); 
	    }
		lv_leftValues_3_0=ruleListAssignmentValue		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getBiListAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"leftValues",
	        		lv_leftValues_3_0, 
	        		"ListAssignmentValue", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)(	otherlv_4=',' 
    {
    	createLeafNode(otherlv_4, grammarAccess.getBiListAssignmentAccess().getCommaKeyword_3_1_0(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getBiListAssignmentAccess().getLeftValuesListAssignmentValueParserRuleCall_3_1_1_0(), currentNode); 
	    }
		lv_leftValues_5_0=ruleListAssignmentValue		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getBiListAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"leftValues",
	        		lv_leftValues_5_0, 
	        		"ListAssignmentValue", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
))*)?	otherlv_6='|' 
    {
    	createLeafNode(otherlv_6, grammarAccess.getBiListAssignmentAccess().getVerticalLineKeyword_4(), null);
    }
((
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getBiListAssignmentAccess().getRightValuesListAssignmentValueParserRuleCall_5_0_0(), currentNode); 
	    }
		lv_rightValues_7_0=ruleListAssignmentValue		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getBiListAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"rightValues",
	        		lv_rightValues_7_0, 
	        		"ListAssignmentValue", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)(	otherlv_8=',' 
    {
    	createLeafNode(otherlv_8, grammarAccess.getBiListAssignmentAccess().getCommaKeyword_5_1_0(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getBiListAssignmentAccess().getRightValuesListAssignmentValueParserRuleCall_5_1_1_0(), currentNode); 
	    }
		lv_rightValues_9_0=ruleListAssignmentValue		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getBiListAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"rightValues",
	        		lv_rightValues_9_0, 
	        		"ListAssignmentValue", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
))*)?	otherlv_10=']' 
    {
    	createLeafNode(otherlv_10, grammarAccess.getBiListAssignmentAccess().getRightSquareBracketKeyword_6(), null);
    }
	otherlv_11=';' 
    {
    	createLeafNode(otherlv_11, grammarAccess.getBiListAssignmentAccess().getSemicolonKeyword_7(), null);
    }
)
;





// Entry rule entryRuleMonoSingleAssignment
entryRuleMonoSingleAssignment returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getMonoSingleAssignmentRule(), currentNode); }
	 iv_ruleMonoSingleAssignment=ruleMonoSingleAssignment 
	 { $current=$iv_ruleMonoSingleAssignment.current; } 
	 EOF 
;

// Rule MonoSingleAssignment
ruleMonoSingleAssignment returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
((
(
		lv_feature_0_0=RULE_ID
		{
			createLeafNode(lv_feature_0_0, grammarAccess.getMonoSingleAssignmentAccess().getFeatureIDTerminalRuleCall_0_0(), "feature"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getMonoSingleAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"feature",
	        		lv_feature_0_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_1='=' 
    {
    	createLeafNode(otherlv_1, grammarAccess.getMonoSingleAssignmentAccess().getEqualsSignKeyword_1(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getMonoSingleAssignmentAccess().getLeftValueSingleAssignmentValueParserRuleCall_2_0(), currentNode); 
	    }
		lv_leftValue_2_0=ruleSingleAssignmentValue		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getMonoSingleAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"leftValue",
	        		lv_leftValue_2_0, 
	        		"SingleAssignmentValue", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)	otherlv_3=';' 
    {
    	createLeafNode(otherlv_3, grammarAccess.getMonoSingleAssignmentAccess().getSemicolonKeyword_3(), null);
    }
)
;





// Entry rule entryRuleMonoListAssignment
entryRuleMonoListAssignment returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getMonoListAssignmentRule(), currentNode); }
	 iv_ruleMonoListAssignment=ruleMonoListAssignment 
	 { $current=$iv_ruleMonoListAssignment.current; } 
	 EOF 
;

// Rule MonoListAssignment
ruleMonoListAssignment returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
((
(
		lv_feature_0_0=RULE_ID
		{
			createLeafNode(lv_feature_0_0, grammarAccess.getMonoListAssignmentAccess().getFeatureIDTerminalRuleCall_0_0(), "feature"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getMonoListAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"feature",
	        		lv_feature_0_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_1='=' 
    {
    	createLeafNode(otherlv_1, grammarAccess.getMonoListAssignmentAccess().getEqualsSignKeyword_1(), null);
    }
	otherlv_2='[' 
    {
    	createLeafNode(otherlv_2, grammarAccess.getMonoListAssignmentAccess().getLeftSquareBracketKeyword_2(), null);
    }
((
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getMonoListAssignmentAccess().getLeftValuesAssignmentValueParserRuleCall_3_0_0(), currentNode); 
	    }
		lv_leftValues_3_0=ruleAssignmentValue		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getMonoListAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"leftValues",
	        		lv_leftValues_3_0, 
	        		"AssignmentValue", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)(	otherlv_4=',' 
    {
    	createLeafNode(otherlv_4, grammarAccess.getMonoListAssignmentAccess().getCommaKeyword_3_1_0(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getMonoListAssignmentAccess().getLeftValuesAssignmentValueParserRuleCall_3_1_1_0(), currentNode); 
	    }
		lv_leftValues_5_0=ruleAssignmentValue		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getMonoListAssignmentRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"leftValues",
	        		lv_leftValues_5_0, 
	        		"AssignmentValue", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
))*)?	otherlv_6=']' 
    {
    	createLeafNode(otherlv_6, grammarAccess.getMonoListAssignmentAccess().getRightSquareBracketKeyword_4(), null);
    }
	otherlv_7=';' 
    {
    	createLeafNode(otherlv_7, grammarAccess.getMonoListAssignmentAccess().getSemicolonKeyword_5(), null);
    }
)
;





// Entry rule entryRuleAssignmentValue
entryRuleAssignmentValue returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getAssignmentValueRule(), currentNode); }
	 iv_ruleAssignmentValue=ruleAssignmentValue 
	 { $current=$iv_ruleAssignmentValue.current; } 
	 EOF 
;

// Rule AssignmentValue
ruleAssignmentValue returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
((
(
		lv_value_0_0=RULE_STRING
		{
			createLeafNode(lv_value_0_0, grammarAccess.getAssignmentValueAccess().getValueSTRINGTerminalRuleCall_0_0(), "value"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"value",
	        		lv_value_0_0, 
	        		"STRING", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)
    |((
(
		{
			if ($current==null) {
	            $current = factory.create(grammarAccess.getAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
        }
	otherlv_1=RULE_ID
	{
		createLeafNode(otherlv_1, grammarAccess.getAssignmentValueAccess().getRefObjectNamedObjectCrossReference_1_0_0(), "refObject"); 
	}

)
)(	otherlv_2='.' 
    {
    	createLeafNode(otherlv_2, grammarAccess.getAssignmentValueAccess().getFullStopKeyword_1_1_0(), null);
    }
(
(
		lv_refFeature_3_0=RULE_ID
		{
			createLeafNode(lv_refFeature_3_0, grammarAccess.getAssignmentValueAccess().getRefFeatureIDTerminalRuleCall_1_1_1_0(), "refFeature"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"refFeature",
	        		lv_refFeature_3_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)(	otherlv_4='[' 
    {
    	createLeafNode(otherlv_4, grammarAccess.getAssignmentValueAccess().getLeftSquareBracketKeyword_1_1_2_0(), null);
    }
(
(
		lv_refIndex_5_0=RULE_INT
		{
			createLeafNode(lv_refIndex_5_0, grammarAccess.getAssignmentValueAccess().getRefIndexINTTerminalRuleCall_1_1_2_1_0(), "refIndex"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"refIndex",
	        		lv_refIndex_5_0, 
	        		"INT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_6=']' 
    {
    	createLeafNode(otherlv_6, grammarAccess.getAssignmentValueAccess().getRightSquareBracketKeyword_1_1_2_2(), null);
    }
)?)?)
    |(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getAssignmentValueAccess().getNewObjectCreatedObjectParserRuleCall_2_0(), currentNode); 
	    }
		lv_newObject_7_0=ruleCreatedObject		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"newObject",
	        		lv_newObject_7_0, 
	        		"CreatedObject", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)
    |((
(
		{
			if ($current==null) {
	            $current = factory.create(grammarAccess.getAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
        }
	otherlv_8=RULE_ID
	{
		createLeafNode(otherlv_8, grammarAccess.getAssignmentValueAccess().getImportImportCrossReference_3_0_0(), "import"); 
	}

)
)(
(
		lv_impFrag_9_0=RULE_FRAGMENT
		{
			createLeafNode(lv_impFrag_9_0, grammarAccess.getAssignmentValueAccess().getImpFragFRAGMENTTerminalRuleCall_3_1_0(), "impFrag"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"impFrag",
	        		lv_impFrag_9_0, 
	        		"FRAGMENT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)))
;





// Entry rule entryRuleListAssignmentValue
entryRuleListAssignmentValue returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getListAssignmentValueRule(), currentNode); }
	 iv_ruleListAssignmentValue=ruleListAssignmentValue 
	 { $current=$iv_ruleListAssignmentValue.current; } 
	 EOF 
;

// Rule ListAssignmentValue
ruleListAssignmentValue returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
((
(
		lv_index_0_0=RULE_INT
		{
			createLeafNode(lv_index_0_0, grammarAccess.getListAssignmentValueAccess().getIndexINTTerminalRuleCall_0_0(), "index"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getListAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"index",
	        		lv_index_0_0, 
	        		"INT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_1=':' 
    {
    	createLeafNode(otherlv_1, grammarAccess.getListAssignmentValueAccess().getColonKeyword_1(), null);
    }
((	otherlv_2='[' 
    {
    	createLeafNode(otherlv_2, grammarAccess.getListAssignmentValueAccess().getLeftSquareBracketKeyword_2_0_0(), null);
    }
(
(
		lv_refIndex_3_0=RULE_INT
		{
			createLeafNode(lv_refIndex_3_0, grammarAccess.getListAssignmentValueAccess().getRefIndexINTTerminalRuleCall_2_0_1_0(), "refIndex"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getListAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"refIndex",
	        		lv_refIndex_3_0, 
	        		"INT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_4=']' 
    {
    	createLeafNode(otherlv_4, grammarAccess.getListAssignmentValueAccess().getRightSquareBracketKeyword_2_0_2(), null);
    }
)
    |(
(
		lv_value_5_0=RULE_STRING
		{
			createLeafNode(lv_value_5_0, grammarAccess.getListAssignmentValueAccess().getValueSTRINGTerminalRuleCall_2_1_0(), "value"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getListAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"value",
	        		lv_value_5_0, 
	        		"STRING", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)
    |((
(
		{
			if ($current==null) {
	            $current = factory.create(grammarAccess.getListAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
        }
	otherlv_6=RULE_ID
	{
		createLeafNode(otherlv_6, grammarAccess.getListAssignmentValueAccess().getRefObjectNamedObjectCrossReference_2_2_0_0(), "refObject"); 
	}

)
)(	otherlv_7='.' 
    {
    	createLeafNode(otherlv_7, grammarAccess.getListAssignmentValueAccess().getFullStopKeyword_2_2_1_0(), null);
    }
(
(
		lv_refFeature_8_0=RULE_ID
		{
			createLeafNode(lv_refFeature_8_0, grammarAccess.getListAssignmentValueAccess().getRefFeatureIDTerminalRuleCall_2_2_1_1_0(), "refFeature"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getListAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"refFeature",
	        		lv_refFeature_8_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)(	otherlv_9='[' 
    {
    	createLeafNode(otherlv_9, grammarAccess.getListAssignmentValueAccess().getLeftSquareBracketKeyword_2_2_1_2_0(), null);
    }
(
(
		lv_refIndex_10_0=RULE_INT
		{
			createLeafNode(lv_refIndex_10_0, grammarAccess.getListAssignmentValueAccess().getRefIndexINTTerminalRuleCall_2_2_1_2_1_0(), "refIndex"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getListAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"refIndex",
	        		lv_refIndex_10_0, 
	        		"INT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_11=']' 
    {
    	createLeafNode(otherlv_11, grammarAccess.getListAssignmentValueAccess().getRightSquareBracketKeyword_2_2_1_2_2(), null);
    }
)?)?)
    |(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getListAssignmentValueAccess().getNewObjectCreatedObjectParserRuleCall_2_3_0(), currentNode); 
	    }
		lv_newObject_12_0=ruleCreatedObject		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getListAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"newObject",
	        		lv_newObject_12_0, 
	        		"CreatedObject", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)
    |((
(
		{
			if ($current==null) {
	            $current = factory.create(grammarAccess.getListAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
        }
	otherlv_13=RULE_ID
	{
		createLeafNode(otherlv_13, grammarAccess.getListAssignmentValueAccess().getImportImportCrossReference_2_4_0_0(), "import"); 
	}

)
)(
(
		lv_impFrag_14_0=RULE_FRAGMENT
		{
			createLeafNode(lv_impFrag_14_0, grammarAccess.getListAssignmentValueAccess().getImpFragFRAGMENTTerminalRuleCall_2_4_1_0(), "impFrag"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getListAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"impFrag",
	        		lv_impFrag_14_0, 
	        		"FRAGMENT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
))))
;





// Entry rule entryRuleSingleAssignmentValue
entryRuleSingleAssignmentValue returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getSingleAssignmentValueRule(), currentNode); }
	 iv_ruleSingleAssignmentValue=ruleSingleAssignmentValue 
	 { $current=$iv_ruleSingleAssignmentValue.current; } 
	 EOF 
;

// Rule SingleAssignmentValue
ruleSingleAssignmentValue returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
((
(
		lv_keyword_0_0=	'null' 
    {
        createLeafNode(lv_keyword_0_0, grammarAccess.getSingleAssignmentValueAccess().getKeywordNullKeyword_0_0(), "keyword");
    }
 
	    {
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getSingleAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        
	        try {
	       		set($current, "keyword", lv_keyword_0_0, "null", lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)
    |(
(
		lv_value_1_0=RULE_STRING
		{
			createLeafNode(lv_value_1_0, grammarAccess.getSingleAssignmentValueAccess().getValueSTRINGTerminalRuleCall_1_0(), "value"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getSingleAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"value",
	        		lv_value_1_0, 
	        		"STRING", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)
    |((
(
		{
			if ($current==null) {
	            $current = factory.create(grammarAccess.getSingleAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
        }
	otherlv_2=RULE_ID
	{
		createLeafNode(otherlv_2, grammarAccess.getSingleAssignmentValueAccess().getRefObjectNamedObjectCrossReference_2_0_0(), "refObject"); 
	}

)
)(	otherlv_3='.' 
    {
    	createLeafNode(otherlv_3, grammarAccess.getSingleAssignmentValueAccess().getFullStopKeyword_2_1_0(), null);
    }
(
(
		lv_refFeature_4_0=RULE_ID
		{
			createLeafNode(lv_refFeature_4_0, grammarAccess.getSingleAssignmentValueAccess().getRefFeatureIDTerminalRuleCall_2_1_1_0(), "refFeature"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getSingleAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"refFeature",
	        		lv_refFeature_4_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)(	otherlv_5='[' 
    {
    	createLeafNode(otherlv_5, grammarAccess.getSingleAssignmentValueAccess().getLeftSquareBracketKeyword_2_1_2_0(), null);
    }
(
(
		lv_refIndex_6_0=RULE_INT
		{
			createLeafNode(lv_refIndex_6_0, grammarAccess.getSingleAssignmentValueAccess().getRefIndexINTTerminalRuleCall_2_1_2_1_0(), "refIndex"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getSingleAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"refIndex",
	        		lv_refIndex_6_0, 
	        		"INT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_7=']' 
    {
    	createLeafNode(otherlv_7, grammarAccess.getSingleAssignmentValueAccess().getRightSquareBracketKeyword_2_1_2_2(), null);
    }
)?)?)
    |(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getSingleAssignmentValueAccess().getNewObjectCreatedObjectParserRuleCall_3_0(), currentNode); 
	    }
		lv_newObject_8_0=ruleCreatedObject		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getSingleAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"newObject",
	        		lv_newObject_8_0, 
	        		"CreatedObject", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)
    |((
(
		{
			if ($current==null) {
	            $current = factory.create(grammarAccess.getSingleAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
        }
	otherlv_9=RULE_ID
	{
		createLeafNode(otherlv_9, grammarAccess.getSingleAssignmentValueAccess().getImportImportCrossReference_4_0_0(), "import"); 
	}

)
)(
(
		lv_impFrag_10_0=RULE_FRAGMENT
		{
			createLeafNode(lv_impFrag_10_0, grammarAccess.getSingleAssignmentValueAccess().getImpFragFRAGMENTTerminalRuleCall_4_1_0(), "impFrag"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getSingleAssignmentValueRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"impFrag",
	        		lv_impFrag_10_0, 
	        		"FRAGMENT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)))
;





// Entry rule entryRuleCreatedObject
entryRuleCreatedObject returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getCreatedObjectRule(), currentNode); }
	 iv_ruleCreatedObject=ruleCreatedObject 
	 { $current=$iv_ruleCreatedObject.current; } 
	 EOF 
;

// Rule CreatedObject
ruleCreatedObject returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
((
    { 
        currentNode=createCompositeNode(grammarAccess.getCreatedObjectAccess().getObjectNewParserRuleCall_0_0(), currentNode); 
    }
    this_ObjectNew_0=ruleObjectNew
    { 
        $current = $this_ObjectNew_0.current; 
        currentNode = currentNode.getParent();
    }

    |
    { 
        currentNode=createCompositeNode(grammarAccess.getCreatedObjectAccess().getObjectCopyParserRuleCall_0_1(), currentNode); 
    }
    this_ObjectCopy_1=ruleObjectCopy
    { 
        $current = $this_ObjectCopy_1.current; 
        currentNode = currentNode.getParent();
    }
)(
(
		lv_name_2_0=RULE_ID
		{
			createLeafNode(lv_name_2_0, grammarAccess.getCreatedObjectAccess().getNameIDTerminalRuleCall_1_0(), "name"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getCreatedObjectRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"name",
	        		lv_name_2_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)?(	otherlv_3='{' 
    {
    	createLeafNode(otherlv_3, grammarAccess.getCreatedObjectAccess().getLeftCurlyBracketKeyword_2_0(), null);
    }
((
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getCreatedObjectAccess().getAssignmentsMonoSingleAssignmentParserRuleCall_2_1_0_0(), currentNode); 
	    }
		lv_assignments_4_0=ruleMonoSingleAssignment		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getCreatedObjectRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"assignments",
	        		lv_assignments_4_0, 
	        		"MonoSingleAssignment", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)
    |(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getCreatedObjectAccess().getAssignmentsMonoListAssignmentParserRuleCall_2_1_1_0(), currentNode); 
	    }
		lv_assignments_5_0=ruleMonoListAssignment		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getCreatedObjectRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		add(
	       			$current, 
	       			"assignments",
	        		lv_assignments_5_0, 
	        		"MonoListAssignment", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
))+(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getCreatedObjectAccess().getLeftMigMigrationParserRuleCall_2_2_0(), currentNode); 
	    }
		lv_leftMig_6_0=ruleMigration		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getCreatedObjectRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"leftMig",
	        		lv_leftMig_6_0, 
	        		"Migration", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)?	otherlv_7='}' 
    {
    	createLeafNode(otherlv_7, grammarAccess.getCreatedObjectAccess().getRightCurlyBracketKeyword_2_3(), null);
    }
)?)
;





// Entry rule entryRuleObjectNew
entryRuleObjectNew returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getObjectNewRule(), currentNode); }
	 iv_ruleObjectNew=ruleObjectNew 
	 { $current=$iv_ruleObjectNew.current; } 
	 EOF 
;

// Rule ObjectNew
ruleObjectNew returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(	otherlv_0='new' 
    {
    	createLeafNode(otherlv_0, grammarAccess.getObjectNewAccess().getNewKeyword_0(), null);
    }
(
(
		{
			if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectNewRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
        }
	otherlv_1=RULE_ID
	{
		createLeafNode(otherlv_1, grammarAccess.getObjectNewAccess().getImportImportCrossReference_1_0(), "import"); 
	}

)
)(
(
		lv_impFrag_2_0=RULE_FRAGMENT
		{
			createLeafNode(lv_impFrag_2_0, grammarAccess.getObjectNewAccess().getImpFragFRAGMENTTerminalRuleCall_2_0(), "impFrag"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectNewRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"impFrag",
	        		lv_impFrag_2_0, 
	        		"FRAGMENT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
))
;





// Entry rule entryRuleObjectCopy
entryRuleObjectCopy returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getObjectCopyRule(), currentNode); }
	 iv_ruleObjectCopy=ruleObjectCopy 
	 { $current=$iv_ruleObjectCopy.current; } 
	 EOF 
;

// Rule ObjectCopy
ruleObjectCopy returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(	otherlv_0='copy' 
    {
    	createLeafNode(otherlv_0, grammarAccess.getObjectCopyAccess().getCopyKeyword_0(), null);
    }
(
(
		{
			if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectCopyRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
        }
	otherlv_1=RULE_ID
	{
		createLeafNode(otherlv_1, grammarAccess.getObjectCopyAccess().getResourceNamedResourceCrossReference_1_0(), "resource"); 
	}

)
)(
(
		lv_fragment_2_0=RULE_FRAGMENT
		{
			createLeafNode(lv_fragment_2_0, grammarAccess.getObjectCopyAccess().getFragmentFRAGMENTTerminalRuleCall_2_0(), "fragment"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getObjectCopyRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"fragment",
	        		lv_fragment_2_0, 
	        		"FRAGMENT", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
))
;





// Entry rule entryRuleMigration
entryRuleMigration returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getMigrationRule(), currentNode); }
	 iv_ruleMigration=ruleMigration 
	 { $current=$iv_ruleMigration.current; } 
	 EOF 
;

// Rule Migration
ruleMigration returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(	otherlv_0='migrate' 
    {
    	createLeafNode(otherlv_0, grammarAccess.getMigrationAccess().getMigrateKeyword_0(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getMigrationAccess().getFirstExecutableParserRuleCall_1_0(), currentNode); 
	    }
		lv_first_1_0=ruleExecutable		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getMigrationRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"first",
	        		lv_first_1_0, 
	        		"Executable", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)?((	otherlv_2='as' 
    {
    	createLeafNode(otherlv_2, grammarAccess.getMigrationAccess().getAsKeyword_2_0_0(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getMigrationAccess().getAsOpExecutableParserRuleCall_2_0_1_0(), currentNode); 
	    }
		lv_asOp_3_0=ruleExecutable		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getMigrationRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"asOp",
	        		lv_asOp_3_0, 
	        		"Executable", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
))
    |(	otherlv_4='each' 
    {
    	createLeafNode(otherlv_4, grammarAccess.getMigrationAccess().getEachKeyword_2_1_0(), null);
    }
(
(
		{ 
	        currentNode=createCompositeNode(grammarAccess.getMigrationAccess().getEachOpExecutableParserRuleCall_2_1_1_0(), currentNode); 
	    }
		lv_eachOp_5_0=ruleExecutable		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getMigrationRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode.getParent(), $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"eachOp",
	        		lv_eachOp_5_0, 
	        		"Executable", 
	        		currentNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	        currentNode = currentNode.getParent();
	    }

)
)))?	otherlv_6=';' 
    {
    	createLeafNode(otherlv_6, grammarAccess.getMigrationAccess().getSemicolonKeyword_3(), null);
    }
)
;





// Entry rule entryRuleExecutable
entryRuleExecutable returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getExecutableRule(), currentNode); }
	 iv_ruleExecutable=ruleExecutable 
	 { $current=$iv_ruleExecutable.current; } 
	 EOF 
;

// Rule Executable
ruleExecutable returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(
    { 
        currentNode=createCompositeNode(grammarAccess.getExecutableAccess().getJavaExecutableParserRuleCall_0(), currentNode); 
    }
    this_JavaExecutable_0=ruleJavaExecutable
    { 
        $current = $this_JavaExecutable_0.current; 
        currentNode = currentNode.getParent();
    }

    |
    { 
        currentNode=createCompositeNode(grammarAccess.getExecutableAccess().getExpressionExecutableParserRuleCall_1(), currentNode); 
    }
    this_ExpressionExecutable_1=ruleExpressionExecutable
    { 
        $current = $this_ExpressionExecutable_1.current; 
        currentNode = currentNode.getParent();
    }
)
;





// Entry rule entryRuleJavaExecutable
entryRuleJavaExecutable returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getJavaExecutableRule(), currentNode); }
	 iv_ruleJavaExecutable=ruleJavaExecutable 
	 { $current=$iv_ruleJavaExecutable.current; } 
	 EOF 
;

// Rule JavaExecutable
ruleJavaExecutable returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(	otherlv_0='java' 
    {
    	createLeafNode(otherlv_0, grammarAccess.getJavaExecutableAccess().getJavaKeyword_0(), null);
    }
(
(
		lv_method_1_0=RULE_ID
		{
			createLeafNode(lv_method_1_0, grammarAccess.getJavaExecutableAccess().getMethodIDTerminalRuleCall_1_0(), "method"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getJavaExecutableRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"method",
	        		lv_method_1_0, 
	        		"ID", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)	otherlv_2='(' 
    {
    	createLeafNode(otherlv_2, grammarAccess.getJavaExecutableAccess().getLeftParenthesisKeyword_2(), null);
    }
	otherlv_3=')' 
    {
    	createLeafNode(otherlv_3, grammarAccess.getJavaExecutableAccess().getRightParenthesisKeyword_3(), null);
    }
)
;





// Entry rule entryRuleExpressionExecutable
entryRuleExpressionExecutable returns [EObject current=null] 
	:
	{ currentNode = createCompositeNode(grammarAccess.getExpressionExecutableRule(), currentNode); }
	 iv_ruleExpressionExecutable=ruleExpressionExecutable 
	 { $current=$iv_ruleExpressionExecutable.current; } 
	 EOF 
;

// Rule ExpressionExecutable
ruleExpressionExecutable returns [EObject current=null] 
    @init { EObject temp=null; setCurrentLookahead(); resetLookahead(); 
    }
    @after { resetLookahead(); 
    	lastConsumedNode = currentNode;
    }:
(
(
		lv_exprstr_0_0=RULE_STRING
		{
			createLeafNode(lv_exprstr_0_0, grammarAccess.getExpressionExecutableAccess().getExprstrSTRINGTerminalRuleCall_0(), "exprstr"); 
		}
		{
	        if ($current==null) {
	            $current = factory.create(grammarAccess.getExpressionExecutableRule().getType().getClassifier());
	            associateNodeWithAstElement(currentNode, $current);
	        }
	        try {
	       		set(
	       			$current, 
	       			"exprstr",
	        		lv_exprstr_0_0, 
	        		"STRING", 
	        		lastConsumedNode);
	        } catch (ValueConverterException vce) {
				handleValueConverterException(vce);
	        }
	    }

)
)
;





RULE_FRAGMENT : '#' ('a'..'z'|'A'..'Z'|'0'..'9'|'_'|'/'|'['|']'|'{'|'}'|'.'|'@')+;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' ('b'|'t'|'n'|'f'|'r'|'"'|'\''|'\\')|~(('\\'|'"')))* '"'|'\'' ('\\' ('b'|'t'|'n'|'f'|'r'|'"'|'\''|'\\')|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;


