/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.refactoring.RefactoringTestLanguage with org.eclipse.xtext.common.Terminals

generate refactoring "http://www.eclipse.org/xtext/refactoringTestLanguage"

Main : 
	elements+=AbstractElement*;

AbstractElement:
	Element | Import;
	
Import:
	'import' importedNamespace=FQNWithWC; 

Element:
	name=ID ('{' ( contained+=Element | 'ref' referenced+=[Element|FQN] )* '}')?
;

FQN:
	ID ('.' ID)*;
	
FQNWithWC:
	FQN '.*'?;