/*******************************************************************************
 * Copyright (c) 2010, 2017 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.refactoring.ReferringTestLanguage with org.eclipse.xtext.common.Terminals

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

generate referring "http://www.eclipse.org/xtext/referringTestLanguage"

Main: 
	referenced+=AbstractReference*;

AbstractReference:
	Reference | Reference2;

Reference:
	'ref' referenced =[ecore::EObject|FQN];
	
Reference2:
	Named '=' referenced =[ecore::EObject|FQN];

Named:
	name=ID
;
	
FQN:
	ID ('.' ID)*;
	
