<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bug291022TestLanguage"
    nsURI="http://www.eclipse.org/xtext/ui/common/tests/2009/bug291022TestLanguage"
    nsPrefix="bug291022TestLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" eSuperTypes="#//ModelAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstReference" eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondReference" eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//ModelAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootModel" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ModelElement"/>
  </eClassifiers>
</ecore:EPackage>
