<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="actionLang2" nsURI="http://www.eclipse.org/2008/tmf/xtext/ActionLang2"
    nsPrefix="actionLang2">
  <eClassifiers xsi:type="ecore:EClass" name="ORing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="disjuncts" upperBound="-1"
        eType="#//ORing" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//ORing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
