/*******************************************************************************
 * Copyright (c) 2015 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.parser.fragments.FragmentTestLanguageEx with org.eclipse.xtext.parser.fragments.FragmentTestLanguage

import "http://www.eclipse.org/2015/tmf/xtext/fragments"
 
ParserRuleFragmentsEx returns ParserRuleFragments: 
	ParserRuleFragments
;
