<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xbase" nsURI="http://www.eclipse.org/xtext/xbase/Xbase" nsPrefix="xbase">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="XExpression" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XIfExpression" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conditionalExpression"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@since 2.18"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XSwitchExpression" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="switch" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//XCasePart" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParam" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmFormalParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XCasePart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="case" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeGuard" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fallThrough" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XBlockExpression" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//XExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XVariableDeclaration" eSuperTypes="#//XExpression platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmIdentifiableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XAbstractFeatureCall" abstract="true"
      eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eOperations name="getConcreteSyntaxFeatureName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getExplicitArguments" upperBound="-1" eType="#//XExpression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@deprecated Will be removed shortly"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isExplicitOperationCallOrBuilderSyntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getActualReceiver" eType="#//XExpression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;p>Returns the actual receiver of the feature call. The decision will be made according&#xA;to the linking of the feature. May not be used during linking itself.&#xA;&lt;p/>&#xA;&lt;p>Static features, constructor calls (this, super), references to local variables &#xA;or parameters will return &lt;code>null&lt;/code>.&lt;/p>&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getActualArguments" upperBound="-1" eType="#//XExpression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;p>Returns the actual arguments of the feature call. The decision will be made according&#xA;to the linking of the feature. May not be used during linking itself.&#xA;&lt;p/>&#xA;&lt;p>References to local variables, fields &#xA;or parameters will return an empty list. The result is never &lt;code>null&lt;/code>.&lt;/p>&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns &lt;code>true&lt;/code> if the featuer call links to a static field or a static &#xA;operation. Otherwise &lt;code>false&lt;/code>. May not be used during linking."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns &lt;code>true&lt;/code> if the feature was made available by an extension. &#xA;Otherwise &lt;code>false&lt;/code>. May not be used during linking."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isPackageFragment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isTypeLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isOperation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmIdentifiableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitReceiver" eType="#//XExpression"
        transient="true" derived="true" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the implicit receiver of the feature call if any. Otherwise &lt;code>null&lt;/code>.&#xA;May not be used during linking."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invalidFeatureIssueCode"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@deprecated Will be removed shortly"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@deprecated Will be removed shortly"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitFirstArgument"
        eType="#//XExpression" transient="true" derived="true" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the implicit first argument of the feature call if any. Otherwise &lt;code>null&lt;/code>.&#xA;May not be used during linking."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMemberFeatureCall" eSuperTypes="#//XAbstractFeatureCall">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberCallTarget" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberCallArguments" upperBound="-1"
        eType="#//XExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitOperationCall"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullSafe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staticWithDeclaringType"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageFragment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XFeatureCall" eSuperTypes="#//XAbstractFeatureCall">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureCallArguments" upperBound="-1"
        eType="#//XExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitOperationCall"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageFragment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XConstructorCall" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constructor" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmConstructor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//XExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invalidFeatureIssueCode"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitConstructorCall"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymousClassConstructorCall"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XBooleanLiteral" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTrue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XNullLiteral" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XNumberLiteral" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XStringLiteral" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XCollectionLiteral" abstract="true"
      eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//XExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XListLiteral" eSuperTypes="#//XCollectionLiteral">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XSetLiteral" eSuperTypes="#//XCollectionLiteral">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XClosure" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eOperations name="getFormalParameters" upperBound="-1" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmFormalParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredFormalParameters"
        upperBound="-1" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmFormalParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitSyntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitFormalParameters"
        upperBound="-1" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmFormalParameter"
        transient="true" derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XCastedExpression" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XBinaryOperation" eSuperTypes="#//XAbstractFeatureCall">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reassignFirstArgument"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XUnaryOperation" eSuperTypes="#//XAbstractFeatureCall">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XPostfixOperation" eSuperTypes="#//XAbstractFeatureCall">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XForLoopExpression" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forExpression" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eachExpression" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParam" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmFormalParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XBasicForLoopExpression" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eachExpression" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initExpressions" upperBound="-1"
        eType="#//XExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="updateExpressions" upperBound="-1"
        eType="#//XExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XAbstractWhileExpression" abstract="true"
      eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XDoWhileExpression" eSuperTypes="#//XAbstractWhileExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XWhileExpression" eSuperTypes="#//XAbstractWhileExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XTypeLiteral" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrayDimensions" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XInstanceOfExpression" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//XExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XThrowExpression" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XTryCatchFinallyExpression" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finallyExpression" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catchClauses" upperBound="-1"
        eType="#//XCatchClause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//XVariableDeclaration" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@since 2.18"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XCatchClause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParam" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmFormalParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XAssignment" eSuperTypes="#//XAbstractFeatureCall">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignable" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staticWithDeclaringType"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XReturnExpression" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XSynchronizedExpression" eSuperTypes="#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 2.7&#xA;@noextend This interface is not intended to be extended by clients.&#xA;@noimplement This interface is not intended to be implemented by clients."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//XExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
