/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.linking.lazy.LazyLinkingTestLanguage with org.eclipse.xtext.common.Terminals

generate lazyLinking "http://eclipse.org/xtext/lazyLinkingTestLanguage"

Model : 
	types+=Type*;
	
Type :
	'type' name=ID ('extends' ^extends=[Type] '.' parentId=[Property])? ('for' parentId=[Property] 'in' ^extends=[Type])? '{'
		(properties+=Property)* 
		(unresolvedProxyProperty+=UnresolvedProxyProperty)* 
	'}';
	
Property :
	(type+=[Type])+ name=ID ';';
	
UnresolvedProxyProperty :
	'unresolved' (type+=[Type])+ name=ID ';';