<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="subPackage"
    nsURI="http://www.eclipse.org/2009/tmf/xtext/SubTestLanguage" nsPrefix="subPackage">
  <eClassifiers xsi:type="ecore:EClass" name="SubMain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superMains" upperBound="-1"
        eType="ecore:EClass SuperTestLanguage.ecore#//SuperMain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="another" eType="#//AnotherSuperMain"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnotherSuperMain" eSuperTypes="SuperTestLanguage.ecore#//AnotherSuperMain"/>
</ecore:EPackage>
