/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.ui.common.editor.contentassist.Bug288734TestLanguage
 	with org.eclipse.xtext.common.Terminals

generate bug288734TestLanguage "http://www.eclipse.org/xtext/ui/common/tests/2009/bug288734TestLanguage"

Model :
    constants+=TConstant
;
    
TConstant:
    TStringConstant | TIntegerConstant | TBooleanConstant
;
    
TStringConstant :
    (annotations+=TAnnotation)*
    'constant' 'string' name=ID
;

TIntegerConstant:
    (annotations+=TAnnotation)*
    'constant' 'integer' name=ID
;

TBooleanConstant:
    (annotations+=TAnnotation)*
    'constant' 'boolean' name=ID
;

TAnnotation:
    '@desc' description=STRING
; 