/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.ui.common.editor.contentassist.Bug289187TestLanguage
 	with org.eclipse.xtext.common.Terminals

generate bug289187TestLanguage "http://www.eclipse.org/xtext/ui/common/tests/2009/bug289187TestLanguage"

Model:
    classes+=Class*
    ;
    
Class:
    (abstract?='abstract')?
    (transient?='transient')?
    'class' name=ID
        ('extends' superClass=[Class])?
        ('implements' implementedInterfaces+=[Class]
            (',' 'implements' implementedInterfaces+=[Class])*
        )?
    '{'
        ('classNumber' '=' classNumber=INT)?
        ('quid' '=' quid=INT)?
        ('documentation' '=' documentation=STRING)?
        
        attributes+=Attribute*
        operations+=Operation*
    '}'
    ;
    
Attribute:
    (visibility=Visibility)? 'attribute' name=ID
    ;

Operation:
    (visibility=Visibility)? 'operation' name=ID
    ;
    
enum Visibility:
    PRIVATE | PROTECTED | PACKAGE_PRIVATE | PUBLIC;