/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.ui.common.editor.contentassist.Bug286935TestLanguage
 	with org.eclipse.xtext.common.Terminals

generate bug286935TestLanguage "http://www.eclipse.org/tmf/tests/2009/bug286935TestLanguage"

State:
  (
    (isInitial?='init')
  | (isFinal?='final')
  | (stateKind=StateType)
  | (isInitial?='init' stateKind=StateType)
  | (isInitial?='init' stateKind=StateType isFinal?='final')
  )?
  ('state')?
  (stateName=ID)?
  (label=STRING)?
;
enum StateType:
  NORMAL | PSEUDO='cond' | REFERENCE='reference' | TEXTUAL='textual'
;
