/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.XtextFmtTest with org.eclipse.xtext.common.Terminals hidden(WS, SL_COMMENT)

generate formattertestlanguage "http://simple/formattertestlanguage"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
import "http://www.eclipse.org/2008/Xtext" as xtext

Root:
	"test" (TestLinewrap | TestIndentation);

TestLinewrap:
	"linewrap" items+=STRING*;

TestIndentation:
	"indentation" "{"
	(sub+=TestIndentation |
	items+=STRING)* "}"?;

enum enum1:
	a | b | c | d;

enum enum2:
	gt='>' | lt='<' | ge='>=' | le='<=';

terminal ID2:
	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;

terminal INT2 returns ecore::EInt:
	'0'..'9'+;

terminal STRING2:
	'"' ('\\' ('b' | 't' | 'n' | 'f' | 'r' | '"' | "'" | '\\') | !('\\' | '"'))* '"' |
	"'" ('\\' ('b' | 't' | 'n' | 'f' | 'r' | '"' | "'" | '\\') | !('\\' | "'"))* "'";

terminal ML_COMMENT2:
	'/*'->'*/';