/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.linking.ImportUriUiTestLanguage with org.eclipse.xtext.common.Terminals

generate importUriUi "http://eclipse.org/xtext/importUriUiTestLanguage"

Main : 
	imports+=Import*
	types+=Type*;
	
Import :
	'import' importURI=STRING;
	
Type :
	'type' name=ID 'extends' ^extends=[Type];