<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lazylinking"
    nsURI="http://lazylinking/" nsPrefix="lazy">
  <eClassifiers xsi:type="ecore:EClass" name="Foo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="single" eType="#//Bar"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="many" upperBound="-1" eType="#//Bar"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bar"/>
</ecore:EPackage>
