/*******************************************************************************
 * Copyright (c) 2008, 2017 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.linking.lazy.LazyLinkingTestLanguage with org.eclipse.xtext.common.Terminals

import "http://eclipse.org/xtext/lazyLinkingTestLanguage"

Model : 
	types+=Type*;
	
/* 
 * SuppressWarnings[BidirectionalReference]
 * SuppressWarnings[potentialOverride]
 */
Type :
	'type' name=ID ('extends' ^extends=[Type] '.' parentId=[Property])? ('for' parentId=[Property] 'in' ^extends=[Type])? '{'
		(properties+=Property)* 
		(unresolvedProxyProperty+=UnresolvedProxyProperty)* 
	'}';
	
Property :
	(type+=[Type])+ name=ID ';';
	
UnresolvedProxyProperty :
	'unresolved' (type+=[Type])+ name=ID ';';
