<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xtextutil"
    nsURI="http://www.eclipse.org/2008/Xtext/Utilities" nsPrefix="xtextutil">
  <eClassifiers xsi:type="ecore:EClass" name="ResolvedType" eSuperTypes="#//AbstractType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaModel" eType="#//MetaModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenced" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="ecore:EClass ../src-gen/org/eclipse/xtext/xtext.ecore#//AbstractMetamodelDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClassifier" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltinType" eSuperTypes="#//AbstractType"/>
</ecore:EPackage>
