/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.editor.bracketmatching.BmTestLanguage with org.eclipse.xtext.common.Terminals

generate bracketmatching "http://xtext.org/ui/integartion/tests/bracketmatching"

File :
	(expression+=Expression)*;
	
Expression :
  SExpression |
  Atom |
  "[" Expression "]";
	
SExpression:
    {SExpression}
    ("("
      element+=Expression* 
    ")" |
    "begin"
      element+=Expression* 
    "end"
    );
    
Atom :
  value=VALUE;
  
VALUE : ID|INT|STRING;