/*******************************************************************************
 * Copyright (c) 2015, 2016 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.parser.parameters.ParametersTestLanguageEx with org.eclipse.xtext.parser.parameters.ParametersTestLanguage

import "http://www.eclipse.org/2015/tmf/xtext/parameters"
 
@Override 
ParserRuleParameters returns ParserRuleParameters: 
	super::ParserRuleParameters
;

@Override 
Scenario1<Param> returns Scenario:
	super::Scenario1<Param>
;
