/*******************************************************************************
 * Copyright (c) 2015 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.parser.fragments.FragmentTestLanguageEx with org.eclipse.xtext.parser.fragments.FragmentTestLanguage

import "http://www.eclipse.org/2015/tmf/xtext/fragments"
 
ParserRuleFragmentsEx returns ParserRuleFragments: 
	ParserRuleFragments
;
