package generator.xtend;

import generator.xtend.AbstractXtendWebsite;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Download extends AbstractXtendWebsite {
  public String path() {
    return "download.html";
  }
  
  protected boolean isPrettyPrint() {
    return true;
  }
  
  public CharSequence contents() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t\t");
    CharSequence _headline = this.headline("Download");
    _builder.append(_headline, "		");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<div id=\"page\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"inner\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"container clearfix\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<h2>Download Options</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<hr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<!--table one starts-->");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<div class=\"span4\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<div class=\"pricing\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t\t");
    _builder.append("<td></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<td class=\"focus\">Update Sites <span>Use Update Manager in Eclipse</span></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("<a  ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("rel=\"popover\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-content=\"This is an Eclipse update site URL, which you need to paste into the update manager within Eclipse!\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-original-title=\"Right-click and \'Copy Link\'\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"has-popover btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Latest Release</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<a");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t  ");
    _builder.append("rel=\"popover\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-content=\"This is an Eclipse update site URL, which you need to paste into the update manager within Eclipse!\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-original-title=\"Right-click and \'Copy Link\'\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t  ");
    _builder.append("href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/milestones/\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"has-popover btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Latest Milestone</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<a");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t\t");
    _builder.append("rel=\"popover\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-content=\"This is an Eclipse update site URL, which you need to paste into the update manager within Eclipse!\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-original-title=\"Right-click and \'Copy Link\'\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t\t");
    _builder.append("href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/latest/\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"has-popover btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Bleeding Edge!</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<div class=\"span4\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<div class=\"pricing\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t\t");
    _builder.append("<td></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t\t");
    _builder.append("<td class=\"focus\">Full Eclipse <span>Just Download and Unzip</span></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-macosx-cocoa-x86_64.tar.gz\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\" style=\"width: 45%;\">OS X 64 Bit</a>&nbsp;<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-macosx-cocoa.tar.gz\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-linux-gtk-x86_64.tar.gz\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 45%;\">Linux 64 Bit</a>&nbsp;<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-linux-gtk.tar.gz\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-win32-x86_64.zip\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 45%;\">Windows 64 Bit</a>&nbsp;<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-linux-gtk.tar.gz\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<h2>Installation Instructions</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<hr>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t  ");
    _builder.append("<div class=\"span9\">");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t      ");
    _builder.append("Xtend requires Eclipse 3.5 or higher and a Java SDK 5 or higher. Use one of the udpate sites from above to install the full SDK");
    _builder.newLine();
    _builder.append("\t\t\t\t      ");
    _builder.append("into your running Eclipse. If you do not yet have an Eclipse on your machine, you can download one of the pre-packaged distributions on the right.");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t      ");
    _builder.append("Standalone compilation is supported as well, the simplest way to do that is using the Maven plug-in.");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<!--  section -->");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<section id=\"MavenSupport\" style=\"padding-top: 68px; margin-top: -68px;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<h2 style=\"padding-top: 15px;\">Maven Plug-In</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("The <a href=\"#library\">runtime library</a> as well as a plug-in to run the compiler in a Maven build can be be obtained from");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("the following Maven repository: <a href=\"http://build.eclipse.org/common/xtend/maven/\">http://build.eclipse.org/common/xtend/maven/</a>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("Here is the XML for the repository:");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<pre class=\"prettyprint lang-xml linenums\">");
    _builder.newLine();
    _builder.append("&lt;repositories&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;repository&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;id&gt;xtend&lt;/id&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;url&gt;http://build.eclipse.org/common/xtend/maven/&lt;/url&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;/repository&gt;");
    _builder.newLine();
    _builder.append("&lt;/repositories&gt;");
    _builder.newLine();
    _builder.append("&lt;pluginRepositories&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;pluginRepository&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;id&gt;xtend&lt;/id&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;url&gt;http://build.eclipse.org/common/xtend/maven/&lt;/url&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;/pluginRepository&gt;");
    _builder.newLine();
    _builder.append("&lt;/pluginRepositories&gt;</pre>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("And this is the XML for the plug-in:");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<pre class=\"prettyprint lang-xml linenums\">");
    _builder.newLine();
    _builder.append("&lt;plugin&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;groupId&gt;org.eclipse.xtend&lt;/groupId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;artifactId&gt;xtend-maven-plugin&lt;/artifactId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;version&gt;2.3.0&lt;/version&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;executions&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;execution&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;goals&gt;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("&lt;goal&gt;compile&lt;/goal&gt;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("&lt;!-- &lt;goal&gt;testCompile&lt;/goal&gt; --&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;/goals&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;!-- optionally you can configure a different target folder --&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;!--");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;configuration&gt;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("&lt;outputDirectory&gt;xtend-gen&lt;/outputDirectory&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;/configuration&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("--&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;/execution&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;/executions&gt;");
    _builder.newLine();
    _builder.append("&lt;/plugin&gt;</pre>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("As you see the <strong>outputDirectory</strong> can be specified to match the default of the Eclipse plug-in (<strong>xtend-gen</strong>). Of course you can also change the configuration");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("in Eclipse to match the Maven default (<strong>generated-sources</strong>). To do so right-click on the project and select <strong>Properties</strong> or if you prefer a global setting choose <strong>Eclipse-&gt;Preferences</strong>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("In the category <strong>Xtend/Compiler</strong> enter the directory name (see screenshot). It is interpreted as a relative path to the parent of the source folder, which includes the to-be-compiled Xtend file.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<div class=\"thumbnail\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<img src=\"images/configure-compiler-in-eclipse.png\" alt=\"Configuring the compiler in Eclipse\" width=\"680\" height=\"330\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</section>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<section>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<h2 style=\"padding-top: 15px;\">Getting the runtime library via Maven</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("The <a href=\"api/2.3.0/index.html\">runtime library</a> is contained in the same Maven repository as the plug-in : <a href=\"http://build.eclipse.org/common/xtend/maven/\">http://build.eclipse.org/common/xtend/maven/</a>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("The XML for the dependency is :");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<pre class=\"prettyprint lang-xml linenums\">");
    _builder.newLine();
    _builder.append("&lt;dependency&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;groupId&gt;org.eclipse.xtend&lt;/groupId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;artifactId&gt;org.eclipse.xtend.lib&lt;/artifactId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;version&gt;2.3.0&lt;/version&gt;");
    _builder.newLine();
    _builder.append("&lt;/dependency&gt;</pre>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</section>");
    _builder.newLine();
    _builder.append("\t\t\t\t  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
}
