package generator.xtend;

import generator.xtend.AbstractXtendWebsite;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Download extends AbstractXtendWebsite {
  public String path() {
    return "download.html";
  }
  
  protected boolean isPrettyPrint() {
    return true;
  }
  
  public CharSequence contents() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t\t");
    CharSequence _headline = this.headline("Download");
    _builder.append(_headline, "		");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<div id=\"page\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"inner\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"container clearfix\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<h2>Download Options (Current Version is <a href=\"releasenotes_2_4.html\">2.4</a>)</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<hr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<!--table one starts-->");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<div class=\"span4\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<div class=\"pricing\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t\t");
    _builder.append("<td></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<td class=\"focus\">Update Sites <span>Use Update Manager in Eclipse</span></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("<a  ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("rel=\"popover\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-content=\"This is an Eclipse update site URL, which you need to paste into the update manager within Eclipse!\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-original-title=\"Right-click and \'Copy Link\'\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"has-popover btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Latest Release</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<a");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t  ");
    _builder.append("rel=\"popover\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-content=\"This is an Eclipse update site URL, which you need to paste into the update manager within Eclipse!\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-original-title=\"Right-click and \'Copy Link\'\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t  ");
    _builder.append("href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/milestones/\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"has-popover btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Latest Milestone</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<a");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t\t");
    _builder.append("rel=\"popover\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-content=\"This is an Eclipse update site URL, which you need to paste into the update manager within Eclipse!\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("data-original-title=\"Right-click and \'Copy Link\'\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t\t");
    _builder.append("href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/latest/\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"has-popover btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Bleeding Edge!</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<div class=\"span4\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<div class=\"pricing\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t\t");
    _builder.append("<td></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t\t");
    _builder.append("<td class=\"focus\">Full Eclipse <span>Just Download and Unzip</span></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-4.2.2-Xtext-2.4.1-macosx-cocoa-x86_64.tar.gz&r=1\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\" style=\"width: 45%;\">OS X 64 Bit</a>&nbsp;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-4.2.2-Xtext-2.4.1-macosx-cocoa.tar.gz&r=1\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-4.2.2-Xtext-2.4.1-linux-gtk-x86_64.tar.gz&r=1\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 45%;\">Linux 64 Bit</a>&nbsp;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-4.2.2-Xtext-2.4.1-linux-gtk.tar.gz&r=1\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-4.2.2-Xtext-2.4.1-win32-x86_64.zip&r=1\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 45%;\">Windows 64 Bit</a>&nbsp;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-4.2.2-Xtext-2.4.1-win32.zip&r=1\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<h2>Installation Instructions</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<hr>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t  ");
    _builder.append("<div class=\"span9\">");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t      ");
    _builder.append("Xtend requires Eclipse 3.5 or higher and a Java SDK 5 or higher. Use one of the udpate sites from above to install the full SDK");
    _builder.newLine();
    _builder.append("\t\t\t\t      ");
    _builder.append("into your running Eclipse. If you do not yet have an Eclipse on your machine, you can download one of the pre-packaged distributions on the right.");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t      ");
    _builder.append("Standalone compilation is supported as well, the simplest way to do that is using the Maven plug-in.");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<!--  section -->");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<section id=\"Update Site\" style=\"padding-top: 68px; margin-top: -68px;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<h2 style=\"padding-top: 15px;\">Install From Update Site</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("If you already have an Eclipse running you should install the <i>\"Xtend SDK\"</i>-Feature from one of the update sites listed above. To do so");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("within Eclipse choose <i>Help -&gt; Install New Software...</i>. In the upcoming dialog you should paste one of the update site URLS into the ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("field named <i>Work with</i>. Now search for the feature <e>Xtend SDK</e>, select it and click <i>Next</i> and on the next page <i>Finish</i>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<img src=\"images/screenshot-installation.png\" class=\"image_between_p\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("Now the features are being downloaded and installed. Eclipse will ask you for a restart when downloading and installation is done.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</section>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<section id=\"Hello World\" style=\"padding-top: 68px; margin-top: -68px;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<h2 style=\"padding-top: 15px;\">Getting Started</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<img src=\"images/java-perspective.png\" style=\"float : right; margin-left:10px;\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("When you\'ve started Eclipse for the first time, you should see an empty workspace. Switch to the \'Java perspective\'");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("if you are not already in it. Xtend integrates with Java, so you need to create a Java project to get started. In the menu choose ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<i>File -> New -> Java Project</i>. In the upcoming dialog choose any project name you want (e.g. <i>my.project</i>).");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("After clicking <i>Finish</i> Eclipse will create a fresh project with an empty source folder named <i>\'/src\'</i>. ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<h3>A first class</h3>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<img src=\"images/menu new xtend class.png\" class=\"image_between_p\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("To create your first Xtend class select the source folder and press the right mouse button. You should find the entry ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<i>Xtend class</i> in the category <i>New &gt;</i>. If you don\'t see it you might not be in the Java perspective or you need to reset the perspective. To do so right click");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("on the perspective icon on the top right and choose <i>reset</i>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<img src=\"images/new class wizard.png\" class=\"image_between_p\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("In the dialog you should give the class a name, for instance <i>HelloWorld</i>, and put it into some package (we chose <i>my.namespace</i>). Click <i>Finish</i> and");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("an empty class will be created for you.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<h3>The missing lib</h3>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<img src=\"images/xtend lib missing error.png\"  class=\"image_between_p\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("The newly created class will have an error marker, saying that you need to put the library on the classpath. There is a \"quickfix\" which does that for you.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("Put the cursor on the marked location and press <i>CTRL+1</i> (or CMD+1 on a Mac) and select the option \"Add Xtend libs to the classpath\".");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("The library is also available from maven (see below) or as an OSGi bundle from the p2 update site above.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<h3>Have fun!</h3>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("Now you are ready to code. Within the class body (between the curly braces) type <i>main<i> and press <i>CTRL+space</i>. An empty main method will be generated for you.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("Now type in <code class=\"prettyprint lang-xtend\">println(\'Hello World\')</code>, save and run the application. To do so use the green arrow and choose <i>Run As -&gt; Java Application</i>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<img src=\"images/run as java application.png\" class=\"image_between_p\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<a href=\"documentation.html#GettingStarted\">Click here for the next steps and more examples.</a> ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</section>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<section id=\"MavenSupport\" style=\"padding-top: 68px; margin-top: -68px;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<h2 style=\"padding-top: 15px;\">Maven Plug-In</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("The <a href=\"#library\">runtime library</a> as well as a plug-in to run the compiler in a Maven build can be be obtained from");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("the Maven Central Repository: <a href=\"http://repo.maven.apache.org/maven2\">http://repo.maven.apache.org/maven2</a>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("Here is the XML for the repository:");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<pre class=\"prettyprint lang-xml linenums\">");
    _builder.newLine();
    _builder.append("&lt;repositories&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;repository&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;id&gt;xtend&lt;/id&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;url&gt;http://repo.maven.apache.org/maven2&lt;/url&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;/repository&gt;");
    _builder.newLine();
    _builder.append("&lt;/repositories&gt;");
    _builder.newLine();
    _builder.append("&lt;pluginRepositories&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;pluginRepository&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;id&gt;xtend&lt;/id&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;url&gt;http://repo.maven.apache.org/maven2&lt;/url&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;/pluginRepository&gt;");
    _builder.newLine();
    _builder.append("&lt;/pluginRepositories&gt;</pre>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("And this is the XML for the plug-in:");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<pre class=\"prettyprint lang-xml linenums\">");
    _builder.newLine();
    _builder.append("&lt;plugin&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;groupId&gt;org.eclipse.xtend&lt;/groupId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;artifactId&gt;xtend-maven-plugin&lt;/artifactId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;version&gt;2.4.2&lt;/version&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;executions&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;execution&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;goals&gt;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("&lt;goal&gt;compile&lt;/goal&gt;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("&lt;!-- &lt;goal&gt;testCompile&lt;/goal&gt; --&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;/goals&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;!-- optionally you can configure a different target folder --&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;!--");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;configuration&gt;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("&lt;outputDirectory&gt;xtend-gen&lt;/outputDirectory&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;/configuration&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("--&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;/execution&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;/executions&gt;");
    _builder.newLine();
    _builder.append("&lt;/plugin&gt;</pre>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("As you see the <strong>outputDirectory</strong> can be specified to match the default of the Eclipse plug-in (<strong>xtend-gen</strong>). Of course you can also change the configuration");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("in Eclipse to match the Maven default (<strong>generated-sources</strong>). To do so right-click on the project and select <strong>Properties</strong> or if you prefer a global setting choose <strong>Eclipse-&gt;Preferences</strong>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("In the category <strong>Xtend/Compiler</strong> enter the directory name (see screenshot). It is interpreted as a relative path to the parent of the source folder, which includes the to-be-compiled Xtend file.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<div class=\"thumbnail\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("<img src=\"images/configure-compiler-in-eclipse.png\" alt=\"Configuring the compiler in Eclipse\" width=\"680\" height=\"330\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</section>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<section>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<h2 style=\"padding-top: 15px;\">Getting the runtime library via Maven</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("The <a href=\"api/2.4.0/index.html\">runtime library</a> is available from Maven Central, too: <a href=\"http://repo.maven.apache.org/maven2\">http://repo.maven.apache.org/maven2</a>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("The XML for the dependency is :");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<pre class=\"prettyprint lang-xml linenums\">");
    _builder.newLine();
    _builder.append("&lt;dependency&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;groupId&gt;org.eclipse.xtend&lt;/groupId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;artifactId&gt;org.eclipse.xtend.lib&lt;/artifactId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;version&gt;2.4.2&lt;/version&gt;");
    _builder.newLine();
    _builder.append("&lt;/dependency&gt;</pre>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</section>");
    _builder.newLine();
    _builder.append("\t\t\t\t  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
}
