package generator.xtend;

import com.google.common.base.Objects;
import generator.xtend.AbstractXtendWebsite;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Download extends AbstractXtendWebsite {
  public String path() {
    return "download.html";
  }
  
  protected boolean isPrettyPrint() {
    return true;
  }
  
  public String getLink(final String platform) {
    String _fileExtension = this.fileExtension(platform);
    String _plus = (("http://www.eclipse.org/downloads/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-dsl-kepler-R-" + platform) + _fileExtension);
    String _plus_1 = (_plus + "&r=1");
    return _plus_1;
  }
  
  public String fileExtension(final String platform) {
    String _xifexpression = null;
    boolean _or = false;
    boolean _equals = Objects.equal(platform, Download.WIN_32);
    if (_equals) {
      _or = true;
    } else {
      boolean _equals_1 = Objects.equal(platform, Download.WIN_64);
      _or = (_equals || _equals_1);
    }
    if (_or) {
      _xifexpression = ".zip";
    } else {
      _xifexpression = ".tar.gz";
    }
    return _xifexpression;
  }
  
  public final static String OSX_64 = "macosx-cocoa-x86_64";
  
  public final static String OSX_32 = "macosx-cocoa";
  
  public final static String LINUX_64 = "linux-gtk-x86_64";
  
  public final static String LINUX_32 = "linux-gtk";
  
  public final static String WIN_64 = "win32-x86_64";
  
  public final static String WIN_32 = "win32";
  
  private final String currentVersion = "2.5.0";
  
  public CharSequence contents() {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _headline = this.headline("Download");
    _builder.append(_headline, "");
    _builder.newLineIfNotEmpty();
    _builder.append("<div id=\"page\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<div class=\"inner\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"container clearfix\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<h2>Download Options</h2>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t      ");
    _builder.append("<strong>Check the <a href=\"releasenotes.html\">release notes</a>.");
    _builder.newLine();
    _builder.append("\t\t      ");
    _builder.append("</strong>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<hr>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<!--table one starts-->");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<div class=\"span4\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"pricing\">");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<td></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<td class=\"focus\">Update Sites <span>Use Update Manager in Eclipse</span></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("<a");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("rel=\"popover\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("data-content=\"This is an Eclipse update site URL, which you need to paste into the update manager within Eclipse!\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("data-original-title=\"Right-click and \'Copy Link\'\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("class=\"has-popover btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Latest Release</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<a");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t  ");
    _builder.append("rel=\"popover\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("data-content=\"This is an Eclipse update site URL, which you need to paste into the update manager within Eclipse!\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("data-original-title=\"Right-click and \'Copy Link\'\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t  ");
    _builder.append("href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/milestones/\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("class=\"has-popover btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Latest Milestone</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<a");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("rel=\"popover\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("data-content=\"This is an Eclipse update site URL, which you need to paste into the update manager within Eclipse!\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("data-original-title=\"Right-click and \'Copy Link\'\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/latest/\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("class=\"has-popover btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Bleeding Edge!</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<div class=\"span4\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"pricing\">");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<td></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<td class=\"focus\">Full Eclipse <span>Just Download and Unzip</span></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"");
    String _link = this.getLink(Download.OSX_64);
    _builder.append(_link, "\t\t\t\t\t\t    \t");
    _builder.append("\"");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\" style=\"width: 45%;\">OS X 64 Bit</a>&nbsp;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"");
    String _link_1 = this.getLink(Download.OSX_32);
    _builder.append(_link_1, "\t\t\t\t\t\t    \t");
    _builder.append("\"");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"");
    String _link_2 = this.getLink(Download.LINUX_64);
    _builder.append(_link_2, "\t\t\t\t\t\t    \t");
    _builder.append("\"");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 45%;\">Linux 64 Bit</a>&nbsp;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"");
    String _link_3 = this.getLink(Download.LINUX_32);
    _builder.append(_link_3, "\t\t\t\t\t\t    \t");
    _builder.append("\"");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"");
    String _link_4 = this.getLink(Download.WIN_64);
    _builder.append(_link_4, "\t\t\t\t\t\t    \t");
    _builder.append("\"");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 45%;\">Windows 64 Bit</a>&nbsp;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"");
    String _link_5 = this.getLink(Download.WIN_32);
    _builder.append(_link_5, "\t\t\t\t\t\t    \t");
    _builder.append("\"");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<h2>Installation Instructions</h2>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<hr>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t  ");
    _builder.append("<div class=\"span9\">");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t      ");
    _builder.append("The Xtend IDE integration requires Eclipse 3.5 or higher and a Java SDK 5 or higher. Use one of the udpate sites from above to install the full SDK");
    _builder.newLine();
    _builder.append("\t\t      ");
    _builder.append("into your running Eclipse. If you do not yet have an Eclipse on your machine, you can download one of the pre-packaged distributions on the right.");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t      ");
    _builder.append("There are various options to compile Xtend sources. The most used way is using <a href=\"#MavenSupport\">the Maven plug-in</a>.");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<!--  section -->");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<section id=\"Update Site\" style=\"padding-top: 68px; margin-top: -68px;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<h2 style=\"padding-top: 15px;\">Install From Update Site</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("If you already have an Eclipse running you should install the <i>\"Xtend SDK\"</i>-Feature from one of the update sites listed above. To do so");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("within Eclipse choose <i>Help -&gt; Install New Software...</i>. In the upcoming dialog you should paste one of the update site URLS into the");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("field named <i>Work with</i>. Now search for the feature <e>Xtend SDK</e>, select it and click <i>Next</i> and on the next page <i>Finish</i>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<img src=\"images/screenshot-installation.png\" class=\"image_between_p\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("Now the features are being downloaded and installed. Eclipse will ask you for a restart when downloading and installation is done.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</section>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<section id=\"MavenSupport\" style=\"padding-top: 68px; margin-top: -68px;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<h2 style=\"padding-top: 15px;\">Maven Plug-In</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("The <a href=\"#library\">runtime library</a> as well as a plug-in to run the compiler in a Maven build can be be obtained from");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("the Maven Central Repository: <a href=\"http://repo.maven.apache.org/maven2\">http://repo.maven.apache.org/maven2</a>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("You can create a readily configured project using");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<pre class=\"prettyprint lang-xml linenums\">");
    _builder.newLine();
    _builder.append("mvn archetype:generate -DarchetypeGroupId=org.eclipse.xtend -DarchetypeArtifactId=xtend-archetype");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</pre>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("If you already have a project with a pom.xml, you need to add the plugin configuration:");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<pre class=\"prettyprint lang-xml linenums\">");
    _builder.newLine();
    _builder.append("&lt;plugin&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;groupId&gt;org.eclipse.xtend&lt;/groupId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;artifactId&gt;xtend-maven-plugin&lt;/artifactId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;version&gt;");
    _builder.append(this.currentVersion, "  ");
    _builder.append("&lt;/version&gt;");
    _builder.newLineIfNotEmpty();
    _builder.append("  ");
    _builder.append("&lt;executions&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;execution&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;goals&gt;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("&lt;goal&gt;compile&lt;/goal&gt;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("&lt;!-- &lt;goal&gt;testCompile&lt;/goal&gt; --&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;/goals&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;!-- By default the plugin will look for eclipse settings, and if non were found will generate to --&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;!-- ${basedir}/src/main/generated-sources/xtend --&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;!-- You can optionally configure a different target folder like so : --&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;!--");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;configuration&gt;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("&lt;outputDirectory&gt;${basedir}/src/main/xtend-gen&lt;/outputDirectory&gt;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("&lt;testOutputDirectory&gt;${basedir}/src/test/xtend-gen&lt;/testOutputDirectory&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("&lt;/configuration&gt;");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("--&gt;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("&lt;/execution&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;/executions&gt;");
    _builder.newLine();
    _builder.append("&lt;/plugin&gt;</pre>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("As you see the <strong>outputDirectory</strong> can be specified to match the default of the Eclipse plug-in (<strong>xtend-gen</strong>). Of course you can also change the configuration");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("in Eclipse to match the Maven default (<strong>generated-sources</strong>). To do so right-click on the project and select <strong>Properties</strong> or if you prefer a global setting choose <strong>Eclipse-&gt;Preferences</strong>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("In the category <strong>Xtend/Compiler</strong> enter the directory name (see screenshot). It is interpreted as a relative path to the parent of the source folder, which includes the to-be-compiled Xtend file.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<div class=\"thumbnail\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<img src=\"images/configure-compiler-in-eclipse.png\" alt=\"Configuring the compiler in Eclipse\" width=\"680\" height=\"330\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</section>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<section>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<h2 style=\"padding-top: 15px;\">Getting the runtime library via Maven</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("The <a href=\"api/2.4.0/index.html\">runtime library</a> is available from Maven Central, too: <a href=\"http://repo.maven.apache.org/maven2\">http://repo.maven.apache.org/maven2</a>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("The XML for the dependency is :");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<pre class=\"prettyprint lang-xml linenums\">");
    _builder.newLine();
    _builder.append("&lt;dependency&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;groupId&gt;org.eclipse.xtend&lt;/groupId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;artifactId&gt;org.eclipse.xtend.lib&lt;/artifactId&gt;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("&lt;version&gt;");
    _builder.append(this.currentVersion, "  ");
    _builder.append("&lt;/version&gt;");
    _builder.newLineIfNotEmpty();
    _builder.append("&lt;/dependency&gt;</pre>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</section>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<section id=\"Hello World\" style=\"padding-top: 68px; margin-top: -68px;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<h2 style=\"padding-top: 15px;\">Getting Started</h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<img src=\"images/java-perspective.png\" style=\"float : right; margin-left:10px;\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("When you\'ve started Eclipse for the first time, you should see an empty workspace. Switch to the \'Java perspective\'");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("if you are not already in it. Xtend integrates with Java, so you need to create a Java project to get started. In the menu choose");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<i>File -> New -> Java Project</i>. In the upcoming dialog choose any project name you want (e.g. <i>my.project</i>).");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("After clicking <i>Finish</i> Eclipse will create a fresh project with an empty source folder named <i>\'/src\'</i>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<h3>A first class</h3>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<img src=\"images/menu new xtend class.png\" class=\"image_between_p\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("To create your first Xtend class select the source folder and press the right mouse button. You should find the entry");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<i>Xtend class</i> in the category <i>New &gt;</i>. If you don\'t see it you might not be in the Java perspective or you need to reset the perspective. To do so right click");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("on the perspective icon on the top right and choose <i>reset</i>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<img src=\"images/new class wizard.png\" class=\"image_between_p\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("In the dialog you should give the class a name, for instance <i>HelloWorld</i>, and put it into some package (we chose <i>my.namespace</i>). Click <i>Finish</i> and");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("an empty class will be created for you.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<h3>The missing lib</h3>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<img src=\"images/xtend lib missing error.png\"  class=\"image_between_p\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("The newly created class will have an error marker, saying that you need to put the library on the classpath. There is a \"quickfix\" which does that for you.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("Put the cursor on the marked location and press <i>CTRL+1</i> (or CMD+1 on a Mac) and select the option \"Add Xtend libs to the classpath\".");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("The library is also available from maven (see below) or as an OSGi bundle from the p2 update site above.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<h3>Have fun!</h3>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("Now you are ready to code. Within the class body (between the curly braces) type <i>main<i> and press <i>CTRL+space</i>. An empty main method will be generated for you.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("Now type in <code class=\"prettyprint lang-xtend\">println(\'Hello World\')</code>, save and run the application. To do so use the green arrow and choose <i>Run As -&gt; Java Application</i>.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<img src=\"images/run as java application.png\" class=\"image_between_p\"/>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<a href=\"documentation.html#GettingStarted\">Click here for the next steps and more examples.</a>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</section>");
    _builder.newLine();
    _builder.append("\t\t  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
}
