/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.dummy.DummyTestLanguage with org.eclipse.xtext.common.Terminals

generate dummyLang "http://www.eclipse.org/2008/xtext/DummyLang"

Model :
	(elements+=Element)*;
	
Element :
	(optional?='optional')? "element" name=ID (descriptions+=STRING)* ';';
	
