<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xpect" nsURI="http://www.eclipse.org/xpect/XpectJavaModel" nsPrefix="xpect">
  <eClassifiers xsi:type="ecore:EClass" name="XpectJavaModel">
    <eOperations name="getContributions">
      <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//Iterable">
        <eTypeArguments eClassifier="#//XjmContribution"/>
      </eGenericType>
      <eParameters name="role">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments>
            <eUpperBound eClassifier="#//JavaAnnotation"/>
          </eTypeArguments>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getContributions">
      <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//Iterable">
        <eTypeArguments eClassifier="#//XjmContribution"/>
      </eGenericType>
      <eParameters name="role">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments>
            <eUpperBound eClassifier="#//JavaAnnotation"/>
          </eTypeArguments>
        </eGenericType>
      </eParameters>
      <eParameters name="environment" eType="#//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testOrSuite" eType="#//XjmTest"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributions" upperBound="-1"
        eType="#//XjmContribution" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="#//XjmTest" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//NameToMethodEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XjmElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//XjmClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XjmClass" abstract="true" eSuperTypes="#//XjmElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jvmClass" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmDeclaredType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaClass" derived="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XjmTest" eSuperTypes="#//XjmClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//XjmMethod" containment="true" resolveProxies="false" eOpposite="#//XjmMethod/test"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XjmContribution" eSuperTypes="#//XjmClass">
    <eOperations name="isActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roles" upperBound="-1"
        eType="#//JavaAnnotation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="environments" upperBound="-1"
        eType="#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deactivationReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replacedBy" eType="#//XjmContribution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XjmMethod" abstract="true" eSuperTypes="#//XjmElement">
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="test" eType="#//XjmTest"
        changeable="false" resolveProxies="false" eOpposite="#//XjmTest/methods"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jvmMethod" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmOperation"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaMethod" eType="#//JavaMethod"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XjmTestMethod" eSuperTypes="#//XjmMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="XjmXpectMethod" eSuperTypes="#//XjmMethod">
    <eOperations name="getParameterCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="singleParameterProviders"
        unique="false" upperBound="-1" eType="#//SingleParameterProvider" changeable="false"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiParameterProviders"
        upperBound="-1" eType="#//MultiParameterProvider" changeable="false" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameToMethodEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//XjmMethod"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JavaMethod" instanceClassName="java.lang.reflect.Method"/>
  <eClassifiers xsi:type="ecore:EDataType" name="JavaAnnotation" instanceClassName="java.lang.annotation.Annotation"/>
  <eClassifiers xsi:type="ecore:EDataType" name="SingleParameterProvider" instanceClassName="org.xpect.parameter.IParameterParser$ISingleParameterParser"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MultiParameterProvider" instanceClassName="org.xpect.parameter.IParameterParser$IMultiParameterParser"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Environment">
    <eLiterals name="STANDALONE_TEST"/>
    <eLiterals name="PLUGIN_TEST" value="1"/>
    <eLiterals name="WORKBENCH" value="2"/>
  </eClassifiers>
</ecore:EPackage>
