/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.transientvalues.TransientValuesTest with org.eclipse.xtext.common.Terminals

generate transientvaluestest "http://simple/transientvaluestest"

Root:
	"test" (TestRequired | TestOptional | TestList);
	
TestRequired: 
	{TestRequired} "required" required1=INT required2=INT;
	
TestOptional:
	{TestOptional} "optional" opt1=INT? (":" opt2=INT)?;
	
TestList:
	{TestList} "list" item+=INT*;
