/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
 
 generate ActionLang "http://www.eclipse.org/2008/tmf/xtext/ActionLang" 
 
 Model:
 	(children+=Element)*;
 	
 Element returns Type:
 	Item ( { Item.items+=current } items+=Item );
 	
 Item returns Type: 
 	{ Thing.content=current } name=ID;
  
 