/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
 
generate LexerLang "http://www.eclipse.org/2008/xtext/LexerLang"

Model :
	(children+=Element)*;
	
Element:
	name=ID f=EXPLICITTOKENTYPE g=IMPLICITTOKENTYPE h=STRING i=(EXPLICITTOKENTYPE | IMPLICITTOKENTYPE);
	
lexing:
	EXPLICITTOKENTYPE tokentype X : <# '#' ('A')+ #>
	IMPLICITTOKENTYPE : <# '#' ('C')+ #>
	STRING : <# '#' ('B')+ #> 
