/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.testlanguages.LookaheadTestLanguage with org.eclipse.xtext.common.Terminals

generate lookaheadLang "http://www.eclipse.org/2008/xtext/LookaheadLang"

Entry: (contents+=Alts)*;

Alts: LookAhead0 | LookAhead1 | LookAhead3;

LookAhead0: 'bar' x='a';

LookAhead1: 'foo' y=LookAhead2 x='b' x='d';

LookAhead2: 
	(z='foo' | z='bar') 'c';

LookAhead3: 'foo' 'bar' x='b' z=LookAhead4;

LookAhead4: 
	x='c' | x='d';

