/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
language org.eclipse.xtext.testlanguages.LookaheadLang
generate LookaheadLang "http://www.eclipse.org/2008/xtext/LookaheadLang"

A: x=(B);

B: D | E |C;

C: y=D 'bar' x='c';

D: 'foo' 'bar' x='d';

E: 'foo' 'bar' x='e';