/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
language org.eclipse.xtext.testlanguages.PartialParserTestLanguage
generate partialParserTestLanguage "http://example.xtext.org/PartialParserTestLanguage"

Container :
  'container' name=ID '{'
     ( nested+=Nested | content+=Content )*
  '}';

Nested:
	'nested' '{' 
     	(nested+=Container)+ 
    '}'; 

Content:
	Children | AbstractChildren;

Children:
	'children' '{'
     	children += Child (',' children += Child )*
    '}';
    
Child :
  '->' 'C' '(' value=Named ')';
  
AbstractChildren :
	'abstract children' '{'
   		( abstractChildren += AbstractChild )+
  	'}'; 
     	
AbstractChild :
  FirstConcrete | SecondConcrete;
  
FirstConcrete :
  '->' 'F' '(' value=Named referencedContainer=[Container]? ')';
  
SecondConcrete :
  '->' 'F' 'S' '(' value=Named referencedChildren+=[Child]? ')';
  
Named:
  name=ID;
  