/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
 
generate simpleExpressions "http://www.eclipse.org/xtext/test/simpleExpressions"

Multiplication returns Expression: 
	Addition ({Op.values+=current} operator=('+'|'-') values+=Addition)*;

Addition returns Expression: 
	Term ({Op.values+=current} operator=('*'|'/') values+=Term)*;
	
Term returns Expression:
	Atom | Parens;
	
Atom: 
	name=ID;

Parens returns Expression: 
	'(' Multiplication ')';
	



