/*
* generated by Xtext
*/
package org.eclipse.xtext.testlanguages.backtracking.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.*;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;

/**
 * Represents a generated, default implementation of superclass {@link org.eclipse.xtext.testlanguages.backtracking.ui.contentassist.BeeLangTestLanguageProposalProvider}.
 * Methods are dynamically dispatched on the first parameter, i.e., you can override them 
 * with a more concrete subtype. 
 */
@SuppressWarnings("all")
public class AbstractSimpleBeeLangTestLanguageProposalProvider extends org.eclipse.xtext.testlanguages.backtracking.ui.contentassist.BeeLangTestLanguageProposalProvider {
		
    
	public void complete_DelegateModel(EObject model, RuleCall ruleCall, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		// subclasses may override
	}
}
