<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bug289524ExTest" nsURI="http://eclipse.org/xtext/Bug289524ExTestLanguage"
    nsPrefix="bug289524ExTest">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refs" upperBound="-1" eType="#//ModelElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containments" upperBound="-1"
        eType="#//Contained" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refs" unique="false" upperBound="-1"
        eType="#//Contained"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contained">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
