grammar org.eclipse.xtext.xtext.ecoreInference.Test with org.eclipse.xtext.common.Terminals
generate root "http://root"
import "classpath:/org/eclipse/xtext/xtext/ecoreInference/test.ecore" as test

Root :
	optional=Optional
	","
	mandatory=Mandatory
	","
	objecttypes=ObjectTypes
;

Optional returns test::Optional :
	optionalString=ID
	optionalInt=INT
	optionalBoolean?="foo"
	optionalReference=[test::Mandatory]
	optionalMultivaluedReference+=[test::Mandatory]
;

Mandatory returns test::Mandatory :
	mandatoryString=ID
	mandatoryInt=INT
	mandatoryBoolean?="foo"
	mandatoryReference=[test::Optional]
	mandatoryMultivaluedReference+=[test::Optional]
;

ObjectTypes returns test::ObjectTypes :
	integerObject=INT
	booleanObject?="foo"
;