language org.eclipse.xtext.grammarinheritance.ConcreteTestLanguage extends org.eclipse.xtext.grammarinheritance.AbstractTestLanguage

generate foo "http://holla"

//import "classpath:/org/eclipse/xtext/grammarinheritance/ametamodel.ecore" as mm


RootRule:
//	ConcreteParserRule | CallOverridenParserRule | CallExtendedParserRule;
	ConcreteParserRule;

// call InheritedParserRule
ConcreteParserRule :
	'model' magicNumber=REAL ':' (elements+=InheritedParserRule)*;
	


// override OverridableParserRule and call it

/* TODO: make me work! (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=263651)
OverridableParserRule returns mm::AType:
	'overriddenelement' name=ID;
	
CallOverridenParserRule:
	call=AbstractCallOverridenParserRule;
*/

	
// override and extend ExtendableParserRule and call it

/* TODO: make me work! (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=263651)
ExtendableParserRule returns mm::AType:
	Subrule1 | Subrule2 | Subrule3;
	
Subrule1:
	'subrule1' name=ID sub1=ID;

Subrule2:
	'subrule3' name=ID sub2=STRING;

Subrule3:
	'subrule3' name=ID sub1=INT;
	
CallExtendedParserRule:
	call=AbstractCallExtendedParserRule;
*/