/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.grammarinheritance.InheritanceTest2Language
	with org.eclipse.xtext.grammarinheritance.InheritanceTestLanguage
 	
generate inheritanceTest2 "http://www.eclipse.org/2009/tmf/xtext/InheritanceTest2Language"

Element returns ModelX:
	"model" name=ID "{"
		elements2+=Element*
		ids+=FQN
	"}"
;