grammar org.eclipse.xtext.index.IndexTestLanguage with org.eclipse.xtext.common.Terminals

generate indexTestLanguage "http://www.eclipse.org/xtext/indexTestLanguage"

File :
	(elements+=Element)*;
	
Import :
	'import' importedNamespace=QualifiedNameWithWildCard;
	
QualifiedNameWithWildCard :
	QualifiedName '.*'?;
	
QualifiedName :
	ID ('.' ID)*;
	
Namespace :
	name=QualifiedName '{'
		(elements+=Element)*
	'}';
	
Element :
	Namespace | Type | Import;
	
Type :
	Entity | Datatype;
	
Entity :
	'entity' name=ID '{'
		(properties+=Property)*
	'}';
	
Datatype :
	'datatype' name=ID;
	
Property :
	type=[Type|QualifiedName] name=ID; 
