/*
 * Copyright (c) 2017 itemis AG (http://www.itemis.de) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
grammar org.eclipse.xtext.ide.tests.testlanguage.IndentationAwareUiTestLanguage with org.eclipse.xtext.common.Terminals

generate indentationAwareUiTestLanguage "http://www.eclipse.org/xtext/ide/tests/testlanguage/IndentationAwareUiTestLanguage"

Tree: {Tree}
	nodes+=TreeNode*
	moreNodes+=OtherTreeNode*
;

TreeNode:
	name=ID
	(INDENT
		children+=TreeNode*
	DEDENT)?
;

OtherTreeNode:
	name=STRING
	childList = ChildList?
;

ChildList: {ChildList}
	INDENT
		children+=OtherTreeNode+
	DEDENT
;

@Override 
terminal SL_COMMENT: '//' !('\n'|'\r')*;

terminal INDENT: 'synthetic:INDENT';
terminal DEDENT: 'synthetic:DEDENT';
