/*
 * Copyright (c) 2017 itemis AG (http://www.itemis.de) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 */
grammar org.eclipse.xtext.ide.tests.testlanguage.IndentationAwareUiTestLanguage with org.eclipse.xtext.common.Terminals

generate indentationAwareUiTestLanguage "http://www.eclipse.org/xtext/ide/tests/testlanguage/IndentationAwareUiTestLanguage"

Tree: {Tree}
	nodes+=TreeNode*
	moreNodes+=OtherTreeNode*
;

TreeNode:
	name=ID
	(INDENT
		children+=TreeNode*
	DEDENT)?
;

OtherTreeNode:
	name=STRING
	childList = ChildList?
;

ChildList: {ChildList}
	INDENT
		children+=OtherTreeNode+
	DEDENT
;

@Override 
terminal SL_COMMENT: '//' !('\n'|'\r')*;

terminal INDENT: 'synthetic:INDENT';
terminal DEDENT: 'synthetic:DEDENT';
