/*
 * Copyright (c) 2016 TypeFox GmbH (http://www.typefox.io) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
grammar org.eclipse.xtext.ide.tests.testlanguage.PartialContentAssistTestLanguage with org.eclipse.xtext.common.Terminals

generate partialContentAssistTestLanguage "http://www.eclipse.org/xtext/ide/tests/testlanguage/PartialContentAssistTestLanguage"

TypeDeclaration:
	'type' name=ID ('extends' superType=[TypeDeclaration])? '{'
	   properties+=Property*
	'}';

Property:
    type=("int" | "bool") name=ID
;
