/*
 * Copyright (c) 2016 TypeFox GmbH (http://www.typefox.io) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 */
grammar org.eclipse.xtext.ide.tests.testlanguage.PartialContentAssistTestLanguage with org.eclipse.xtext.common.Terminals

generate partialContentAssistTestLanguage "http://www.eclipse.org/xtext/ide/tests/testlanguage/PartialContentAssistTestLanguage"

TypeDeclaration:
	'type' name=ID ('extends' superType=[TypeDeclaration])? '{'
	   properties+=Property*
	'}';

Property:
    type=("int" | "bool") name=ID
;
