/*
 * Copyright (c) 2019 TypeFox GmbH (http://www.typefox.io) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
grammar org.eclipse.xtext.ide.tests.testlanguage.RenameTestLanguage
   with org.eclipse.xtext.common.Terminals

generate renameTestLanguage "http://www.eclipse.org/xtext/ide/tests/testlanguage/rename/RenameTestLanguage"

Model:
    types+=TypeDeclaration*;
    
TypeDeclaration:
    'type' name=ID ('extends' superType=[TypeDeclaration])? ('{'
    '}')?;

