/*
 * Copyright (c) 2019 TypeFox GmbH (http://www.typefox.io) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 */
grammar org.eclipse.xtext.ide.tests.testlanguage.RenameTestLanguage
   with org.eclipse.xtext.common.Terminals

generate renameTestLanguage "http://www.eclipse.org/xtext/ide/tests/testlanguage/rename/RenameTestLanguage"

Model:
    types+=TypeDeclaration*;
    
TypeDeclaration:
    'type' name=ID ('extends' superType=[TypeDeclaration])? ('{'
    '}')?;

