<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fragmentTestLanguage" nsURI="http://www.eclipse.org/2015/tmf/xtext/fragments"
    nsPrefix="fragmentTestLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="ParserRuleFragments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//PRFNamed"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//PRFNamed"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PRFNamed">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//PRFNamed"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PRFNamedWithAction" eSuperTypes="#//PRFNamed">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prev" eType="#//PRFNamed"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref2" eType="#//PRFNamed"/>
  </eClassifiers>
</ecore:EPackage>
