/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.unassignedtext.UnassignedTextTestLanguage with org.eclipse.xtext.common.Terminals

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

generate unassignedtext "http://simple/unassignedtext"

Model:
	CaseInsensitiveKeywordRule | PluralRule | MultiRule | DatatypeRule | CommonTerminalsRule | GroupRule; 

CaseInsensitiveKeywordRule:
	CaseInsensitiveKeyword val=INT;

/* SuppressWarnings[InvalidTerminalruleName] */
terminal CaseInsensitiveKeyword: 
	('k'|'K')('e'|'E')('y'|'Y')('w'|'W')('o'|'O')('r'|'R')('d'|'D');
	
	
PluralRule:
	'contents:' count=INT Plural;
	
/* SuppressWarnings[InvalidTerminalruleName] */
terminal Plural:
	'item' | 'items';


MultiRule:
	'multi' val=INT Multi Multi Multi;

/* SuppressWarnings[InvalidTerminalruleName] */
terminal Multi:
	'a' 'b'? 'c'+ 'd'* ('e' | 'f') (('g'|'h') | 'i'+) Multi2 '0'..'9' '0'..'9'+;
	
/* SuppressWarnings[InvalidTerminalruleName] */
terminal Multi2:
	'j';


DatatypeRule:
	'datatype' val=INT Datatype;

Datatype returns ecore::EString:
	'str' | INT | Datatype2;
	
Datatype2 returns ecore::EString:
	STRING;
	

CommonTerminalsRule:
	'terminals' ID INT STRING val=ID;
	
GroupRule: {GroupRule}'group' GroupDataTypeRule;

GroupDataTypeRule:
	('this' 'is' 'a' 'test')
;
