/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parser.assignments.Bug287184TestLanguage with org.eclipse.xtext.common.Terminals

generate bug287184Test "http://www.eclipse.org/2008/tmf/xtext/Bug287184Test"

Model:
   "model" name=FQN detail+=(Detail|AssociatedDetail)+;

AbstractDetail:
        Detail | AssociatedDetail;

Detail:
        "detail" visibility=("private"|"protected"|"public")? detailClass=[Model|FQN];

AssociatedDetail:
        "associated" detailClass=[Model|FQN] ";";        

FQN: ID ("." ID)*;