<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bug307519TestLanguage"
    nsURI="http://www.eclipse.org/xtext/ui/common/tests/2010/bug307519TestLanguage"
    nsPrefix="bug307519TestLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e1" upperBound="-1" eType="#//Elem1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="e2" upperBound="-1" eType="#//Elem2"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumT">
    <eLiterals name="T1" literal="T1"/>
    <eLiterals name="T2" value="1" literal="T2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Elem1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//EnumT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Elem2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//EnumT"/>
  </eClassifiers>
</ecore:EPackage>
