<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datatypeRuleTest"
    nsURI="http://www.eclipse.org/xtext/ui/common/tests/2009/datatypeRuleTest" nsPrefix="datatypeRuleTest">
  <eClassifiers xsi:type="ecore:EClass" name="Model"/>
  <eClassifiers xsi:type="ecore:EClass" name="Types" eSuperTypes="platform:/resource/org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/DatatypeRuleTestLanguage.ecore#//Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/DatatypeRuleTestLanguage.ecore#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType" eSuperTypes="platform:/resource/org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/DatatypeRuleTestLanguage.ecore#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeType" eSuperTypes="platform:/resource/org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/DatatypeRuleTestLanguage.ecore#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseType" eType="ecore:EClass platform:/resource/org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/DatatypeRuleTestLanguage.ecore#//CompositeTypeEntry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeTypeEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" eType="ecore:EClass platform:/resource/org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/DatatypeRuleTestLanguage.ecore#//Type"/>
  </eClassifiers>
</ecore:EPackage>
