package org.eclipse.xtext.resource.idea.highlighting;

public class LiveContainerBuilderIntegerationTestLanguageColorSettingsPage extends LiveContainerBuilderIntegerationTestLanguageBaseColorSettingsPage {
}