/*******************************************************************************
 * Copyright (c) 2010 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parser.unorderedGroups.UnorderedGroupsTestLanguage with org.eclipse.xtext.common.Terminals

generate unorderedGroupsTestLanguage "http://www.eclipse.org/2010/tmf/xtext/UnorderedGroupsTestLanguage"
 
Model: {Model} (
	'1' (first?='a'  & second?='b'  )
  | '2' (first?='a'  & second?='b' & third?='c' & forth?='d')
  | '3' (first?='a'? & second?='b'? )
  | '4' (first?='a'  & second?='b'? )
  | '5' (first?='a'? & second?='b'  )
  | '6' (firstAsList+='a'+ & secondAsList+='b'* )
  | '7' (firstAsList+='a'* & secondAsList+='b'+ )
  | '8' ('a' 'b' first?='c' & 'a' 'b' second?='d' )
  | '9' (firstAsList+='a' & secondAsList+='b' )+
  | '10' (firstAsList+='a' & secondAsList+='b' )*
  | '11' (first?='a' & second?='b' )?
  | '12' (firstAsList+='a' & secondAsList+='b' ) (firstAsList+='a' & secondAsList+='b' )
  | '13' (firstAsList+='a' & secondAsList+='b' )? firstAsList+='a' secondAsList+='b'
  | '14' ((firstAsList+='a' & secondAsList+='b') & (thirdAsList+='c' & forthAsList+='d'))+
  | 'datatypes' value=UnorderedDatatype
  | 'serialization' serialized=UnorderedSerialization
  )
;

UnorderedDatatype:
	'1' ('a'  & 'b'  )
  | '2' ('a'  & 'b' & 'c' & 'd')
  | '3' ('a'? & 'b'? )
  | '4' ('a'  & 'b'? )
  | '5' ('a'? & 'b'  )
  | '6' ('a'+ & 'b'* )
  | '7' ('a'* & 'b'+ )
  | '8' ('a' 'b' 'c' & 'a' 'b' 'd' )
  | '9' ('a' & 'b' )+
  | '10' ('a' & 'b' )*
  | '11' ('a' & 'b' )?
  | '12' ('a' & 'b' ) ('a' & 'b' )
  | '13' ('a' & 'b' )? 'a' 'b'
  | '14' (('a' & 'b') & ('c' & 'd'))+
;

UnorderedSerialization: {UnorderedSerialization} (
    '1' first?='a'?  & second?='b'? & third?='c'? & forth?='d'?
  | '2' (firstAsList+='a' & secondAsList+='b')*
  | '3' (firstAsList+='a'+ & second?='b')*
  )
;