/*******************************************************************************
 * Copyright (c) 2010 itemis AG and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.common.types.xtext.ui.RefactoringTestLanguage2 with org.eclipse.xtext.common.types.xtext.ui.RefactoringTestLanguage

import "http://www.eclipse.org/2011/xtext/ui/common/types/xtext/ui/Refactoring" 

Entry returns Model:
	Model;
  

