<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lazyLinking"
    nsURI="http://eclipse.org/xtext/lazyLinkingTestLanguage" nsPrefix="lazyLinking">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/LazyLinkingTestLanguage.ecore#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/LazyLinkingTestLanguage.ecore#//Type"
        eOpposite="platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/LazyLinkingTestLanguage.ecore#//Type/subtypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentId" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/LazyLinkingTestLanguage.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/LazyLinkingTestLanguage.ecore#//Property"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unresolvedProxyProperty"
        upperBound="-1" eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/LazyLinkingTestLanguage.ecore#//UnresolvedProxyProperty"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtypes" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/LazyLinkingTestLanguage.ecore#//Type"
        eOpposite="platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/LazyLinkingTestLanguage.ecore#//Type/extends"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" unique="false" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/LazyLinkingTestLanguage.ecore#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnresolvedProxyProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" unique="false" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/LazyLinkingTestLanguage.ecore#//Type"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
