/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.reconstr.Bug299395TestLanguage with org.eclipse.xtext.common.Terminals

generate bug299395 "http://www.eclipse.org/2010/tmf/xtext/Bug299395"
 
Model: {Model}
	( 
	  	'{' 
		strings += STRING ?
	   	'}'
	)*
	(
		'['
		(	keys += STRING
			values += STRING
		)*
		']'
	)*
	('subModel' subModel=SubModel)?
;
	
SubModel: {SubModel}
		(
			 '1' 
			 '2' 
			 strings += STRING? 
		)*
	;
	