/*******************************************************************************
 * Copyright (c) 2008, 2016 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.reconstr.Bug302128TestLanguage with org.eclipse.xtext.common.Terminals

generate bug302128 "http://www.eclipse.org/2009/tmf/xtext/tests/bug302123"

Model :
    (elements+=Element)*;

Element: name=Variable (value=Value)?;

Variable: ID (('.'|'-') ID)*;

/* SuppressWarnings[InvalidTerminalruleName] */
terminal Value: ('='|'+='|'-=') -> '\n';
@Override 
terminal SL_COMMENT: '#' !('\n'|'\r')* ('\r'? '\n')?;
