/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.parsetree.reconstr.SerializationErrorTestLanguage with org.eclipse.xtext.common.Terminals

generate serializationerror "http://www.eclipse.org/2009/tmf/xtext/serializationerror"

Model:
	test=Test | test=Parenthesis;
	
Parenthesis returns Test:
	"(" Test ")";

Test:
	TwoRequired | TwoOptions | Indent;

TwoRequired:
	"tworequired" one=ID two=ID;

TwoOptions:
	"twooptions" ("one" one=ID | "two" two=ID);

/* SuppressWarnings[noInstantiation] */
Indent:
	"{" req=TwoRequired? opt=TwoOptions? indent+=Indent* "}";