package bootstrap;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class MainSite {
  public CharSequence header(final String bootstrapPath) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("<html lang=\"en\">");
    _builder.newLine();
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<meta charset=\"utf-8\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<title>Eclipse Xtend</title>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<meta name=\"description\" content=\"\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<meta name=\"author\" content=\"\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!-- Le styles -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<link href=\"");
    _builder.append(bootstrapPath, "\t");
    _builder.append("/css/bootstrap.min.css\" rel=\"stylesheet\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<style type=\"text/css\">");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("code.prettyprint {");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("padding: 0px;");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("background-color: white;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("border: none;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("body {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("padding-top: 20px;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("section {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("padding-top: 40px;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("div#maincontainer>section {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("padding-top: 90px;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</style>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<link href=\"");
    _builder.append(bootstrapPath, "\t");
    _builder.append("/css/bootstrap-responsive.min.css\" rel=\"stylesheet\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<link href=\"");
    _builder.append(bootstrapPath, "\t");
    _builder.append("/../google-code-prettify/prettify.css\" type=\"text/css\" rel=\"stylesheet\" />");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<script type=\"text/javascript\" src=\"");
    _builder.append(bootstrapPath, "\t");
    _builder.append("/../google-code-prettify/prettify.js\"></script>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<script type=\"text/javascript\" src=\"");
    _builder.append(bootstrapPath, "\t");
    _builder.append("/../google-code-prettify/lang-xtend.js\"></script>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<script type=\"text/javascript\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("var _gaq = _gaq || [];\t");
    _builder.newLine();
    _builder.append("\t  \t");
    _builder.append("_gaq.push([ \'_setAccount\', \'UA-2429174-4\' ]);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("_gaq.push([ \'_trackPageview\' ]);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("(function() {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("var ga = document.createElement(\'script\');");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("ga.type = \'text/javascript\';");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("ga.async = true;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\'");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append(": \'http://www\')");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("+ \'.google-analytics.com/ga.js\';");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("var s = document.getElementsByTagName(\'script\')[0];");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("s.parentNode.insertBefore(ga, s);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("})();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--[if lt IE 9]>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<![endif]-->");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!-- Le fav and touch icons -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<link rel=\"shortcut icon\" href=\"");
    _builder.append(bootstrapPath, "\t");
    _builder.append("/ico/favicon.ico\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"");
    _builder.append(bootstrapPath, "\t");
    _builder.append("/ico/apple-touch-icon-144-precomposed.png\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"");
    _builder.append(bootstrapPath, "\t");
    _builder.append("/ico/apple-touch-icon-114-precomposed.png\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"");
    _builder.append(bootstrapPath, "\t");
    _builder.append("/ico/apple-touch-icon-72-precomposed.png\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<link rel=\"apple-touch-icon-precomposed\" href=\"");
    _builder.append(bootstrapPath, "\t");
    _builder.append("/ico/apple-touch-icon-57-precomposed.png\">");
    _builder.newLineIfNotEmpty();
    _builder.append("</head>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<body data-spy=\"scroll\" data-target=\".subnav\" data-offset=\"50\"  onload=\"prettyPrint()\">");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence footer(final String bootstrapPath) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t\t\t");
    _builder.append("<!-- Le javascript");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("================================================== -->");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<!-- Placed at the end of the document so the pages load faster -->");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<script src=\"");
    _builder.append(bootstrapPath, "\t\t\t");
    _builder.append("/js/jquery.min.js\"></script>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("<script src=\"");
    _builder.append(bootstrapPath, "\t\t\t");
    _builder.append("/js/bootstrap.min.js\"></script>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</html>");
    _builder.newLine();
    return _builder;
  }
}
