pipeline {
  agent {
    label "external"
  }

  options {
    buildDiscarder(logRotator(numToKeepStr:'25'))
    disableConcurrentBuilds()
    timeout(time: 15, unit: 'MINUTES')
    timestamps()
  }

  stages {
    stage('Copy WAR') {
      steps {
        script {
          step ([$class: 'CopyArtifact',
            projectName: 'xtext-web/cd_issue165experiments',
            filter: "build/maven-repository/org/eclipse/xtext/org.eclipse.xtext.web.example.jetty/*/org.eclipse.xtext.web.example.jetty-*.war",
            target: 'releng/docker/xtext-web-deploy/xtext-web',
            flatten: true
          ]);
          step ([$class: 'CopyArtifact',
            projectName: 'xtext-web/cd_issue165experiments',
            filter: "org.eclipse.xtext.web.example.jetty/build/libs/test-files.zip",
            target: 'releng/docker/xtext-web-deploy/xtext-web',
            flatten: true
          ]);
        }
        dir("releng/docker/xtext-web-deploy/xtext-web") {
          sh "unzip test-files.zip"
        }
        sh "ls -lah releng/docker/xtext-web-deploy/xtext-web"
      }
    }

    stage('Build Docker') {
      steps {
        dir("releng/docker/xtext-web-deploy/xtext-web") {
          sh """
            docker build --no-cache -t xtext/xtext-web:latest .
            docker push xtext/xtext-web:latest
          """
        }
      }
    }
  }
}