<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="contentAssistTestLanguage"
    nsURI="http://www.eclipse.org/2008/xtext/ui/common/tests/ContentAssist" nsPrefix="contentAssistTestLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="Start">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//AbstractRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FirstAbstractRuleChild" eSuperTypes="#//AbstractRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//AbstractRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecondAbstractRuleChild" eSuperTypes="#//AbstractRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//AbstractRuleCall"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRuleCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//AbstractRule"/>
  </eClassifiers>
</ecore:EPackage>
