<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="epatchTestLanguage" nsURI="http://www.eclipse.org/2008/tmf/xtext/EpatchTestLanguage"
    nsPrefix="epatchTestLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="EPatch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//NamedResource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//ObjectRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelImport" eSuperTypes="#//Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceImport" eSuperTypes="#//ModelImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EPackageImport" eSuperTypes="#//ModelImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsURI" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaImport" eSuperTypes="#//Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" unique="false" upperBound="-1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionImport" eSuperTypes="#//Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" unique="false" upperBound="-1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leftUri" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftRoot" eType="#//CreatedObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rightUri" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightRoot" eType="#//CreatedObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//Assignment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftMig" eType="#//Migration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectRef" eSuperTypes="#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftRes" eType="#//NamedResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leftFrag" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightRes" eType="#//NamedResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rightFrag" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightMig" eType="#//Migration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleAssignment" eSuperTypes="#//Assignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftValue" eType="#//AssignmentValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightValue" eType="#//AssignmentValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListAssignment" eSuperTypes="#//Assignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftValues" upperBound="-1"
        eType="#//AssignmentValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightValues" upperBound="-1"
        eType="#//AssignmentValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refObject" eType="#//NamedObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refFeature" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refIndex" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newObject" eType="#//CreatedObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="import" eType="#//Import"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impFrag" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreatedObject" eSuperTypes="#//NamedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectNew" eSuperTypes="#//CreatedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="import" eType="#//Import"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impFrag" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectCopy" eSuperTypes="#//CreatedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//NamedResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fragment" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Migration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="#//Executable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asOp" eType="#//Executable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eachOp" eType="#//Executable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Executable"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavaExecutable" eSuperTypes="#//Executable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionExecutable" eSuperTypes="#//Executable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exprstr" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
