/*
* generated by Xtext
*/
package org.eclipse.xtext.idea.sdomain;

import org.eclipse.xtext.idea.sdomain.SDomainStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SDomainStandaloneSetup extends SDomainStandaloneSetupGenerated{

	public static void doSetup() {
		new SDomainStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

