/*******************************************************************************
* Copyright (c) 2010 itemis AG and others.
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*******************************************************************************/
grammar org.eclipse.xtext.common.types.xtext.ui.ContentAssistTestLanguage with org.eclipse.xtext.common.Terminals

generate contentAssistTestLanguage "http://www.eclipse.org/2010/xtext/ui/common/types/tests/ContentAssist"
import "http://www.eclipse.org/xtext/common/JavaVMTypes" as types

Model:
  imports+=Import*
  referenceHolder=ReferenceHolder;
  
ReferenceHolder:
  (
    'default' defaultReference=[types::JvmType|FQN]
  | 'custom' customizedReference=[types::JvmType|FQN]
  | 'subtype' subtypeReference=[types::JvmType|FQN]
  )
;
  
Import:
	'import' importedNamespace=ImportedFQN
;

ImportedFQN: FQN '.*'?;

FQN: ID ('.' ID)*;

