/*******************************************************************************
* Copyright (c) 2010 itemis AG and others.
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*******************************************************************************/
grammar org.eclipse.xtext.common.types.xtext.ui.RefactoringTestLanguage with org.eclipse.xtext.common.Terminals

generate refactoringTestLanguage "http://www.eclipse.org/2011/xtext/ui/common/types/xtext/ui/Refactoring"
import "http://www.eclipse.org/xtext/common/JavaVMTypes" as types

Model:
   	referenceHolder+=ReferenceHolder*;
  
ReferenceHolder:
    name=ID defaultReference=[types::JvmType|FQN]
;
  
FQN: ID ('.' ID)* ('$' ID)*;

