/*******************************************************************************
 * Copyright (c) 2020 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.testlanguages.ActionTestLanguage3 with org.eclipse.xtext.common.Terminals

generate actionLang3 "http://www.eclipse.org/2008/tmf/xtext/ActionLang3" 

ProductionRules:
	ProductionRule1 | ProductionRule2
;

ProductionRule1:
  {P1} id=ID? {P2.p=current} string=STRING? {P3.p=current} i=INT;

ProductionRule2:
	STRING /* unassigned */ {Entry} name=ID
;