/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.testlanguages.ActionTestLanguage with org.eclipse.xtext.common.Terminals
 
generate actionLang "http://www.eclipse.org/2008/tmf/xtext/ActionLang" 
 
Model:
	Child ({Parent.left=current} right=Child)?;
 		
Child: 
	name=ID;
  
 