/*******************************************************************************
 * Copyright (c) 2008, 2020 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *******************************************************************************/
grammar org.eclipse.xtext.testlanguages.LookaheadTestLanguage with org.eclipse.xtext.common.Terminals

generate lookaheadLang "http://www.eclipse.org/2008/xtext/LookaheadLang"

Entry: (contents+=Alts)*;

Alts: LookAhead0 | LookAhead1 | LookAhead3 | LookAheadPredicate | LookBeyond;

LookAhead0: 'bar' x='a';

LookAhead1: 'foo' y=LookAhead2 x='b' z='d';

LookAhead2: 
	(z='foo' | z='bar') 'c';

LookAhead3: 'foo' 'bar' x='b' z=LookAhead4;

LookAhead4: 
	x='c' | x='d';
	
LookAheadPredicate:
	=>({LookAheadPredicate} 'zonk' 'a' 'b') 'd'
;

LookBeyond:
	left=LookAheadStrings? right=FewerLookAheadStrings
;

LookAheadStrings:
	values += STRING+
;

FewerLookAheadStrings:
	values+=STRING values+=STRING values+=ID
;