/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.testlanguages.TestLanguage with org.eclipse.xtext.common.Terminals

generate testLang "http://www.eclipse.org/2008/xtext/TestLang"

EntryRule returns Model :
	(multiFeature+=AbstractRule)*;
	
AbstractRule returns AbstractElement :
	ChoiceRule | ReducibleRule;
	
ChoiceRule returns ChoiceElement :
	"choice" (optionalKeyword?='optional')? name=ID;
	
ReducibleRule returns ReducibleElement :
	"reducible" TerminalRule ( {ReducibleComposite.actionFeature+=current} actionFeature+=TerminalRule )?;

TerminalRule returns TerminalElement :
	stringFeature=STRING;
