/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.parser.antlr.Bug296889TestLanguage with org.eclipse.xtext.common.Terminals

generate bug296889Test "http://eclipse.org/xtext/Bug296889TestLanguage"

/* SuppressWarnings[noInstantiation] */
Model: "Model" expressions += Expression* | "DataType" values += DataTypeExpression* ;

Expression: Postop | Preop ; 

Preop returns Expression: {Preop} functionName="--" expr=Variable;

Postop returns Expression: Variable ({Postop.expr=current} functionName = "--")? ;

Variable returns Expression: {Variable} name = ID ;

DataTypeExpression: DataTypePostop | DataTypePreop ; 

DataTypePreop: "--" DataTypeVariable;

DataTypePostop: DataTypeVariable ("--")? ;

DataTypeVariable: ID ;
