/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.parser.antlr.Bug289524ExTestLanguage with org.eclipse.xtext.common.Terminals

generate bug289524ExTest "http://eclipse.org/xtext/Bug289524ExTestLanguage"

Model: {Model} "Model" (refs+=ModelElement)*;
ModelElement: {ModelElement} ( containments+=Contained | "reference" refs+=[Contained]  ("$" refs+=[Contained])* )+;
Contained: "containment" name=ID;