/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.parser.antlr.Bug378967TestLanguage  with org.eclipse.xtext.common.Terminals

generate bug378967Test "http://eclipse.org/xtext/Bug378967TestLanguage"

Root:
    ('1' element=Rule1 | '2' element=Rule2 | '3' element=Rule3| '4' element=Rule4);

Rule1:
	type=FirstEnum value=INT unit=SecondEnum
;

Rule2:
	'after' value =INT 's'
;

Rule3:
	 After value=INT S
;

Rule4:
	after= AfterObj value=INT s=SObj
;

enum FirstEnum:
    value='after';

enum SecondEnum:
    value='s';

AfterObj:
	value='after'
;
SObj:
	value='s'
;

After:
	'after'
;

S:
	's'
;
