/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.parser.antlr.Bug301935TestLanguage 

generate bug301935Test "http://eclipse.org/xtext/Bug301935TestLanguage"
import "http://www.eclipse.org/emf/2002/Ecore"

Model: 
    name=ID WS value=ID NL
    value2=ID WS 
;

NL:
	WS* ('\r'? '\n') WS*;

terminal ID  		: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

terminal WS			: (' '|'\t')+;

terminal ANY_OTHER: .;