/*******************************************************************************
 * Copyright (c) 2014 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.parser.antlr.Bug443221TestLanguage with org.eclipse.xtext.common.Terminals

generate bug443221Test "http://eclipse.org/xtext/Bug443221TestLanguage"

Model: {Model} 
	'dummy' name=ID
	'_'
	'_dummy_'
	'__dummy__'
	'$__dummy__'
	'$'
	'DollarSign'
;