/*******************************************************************************
 * Copyright (c) 2016 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.parser.antlr.Bug406914TestLanguage 

generate bug406914Test "http://eclipse.org/xtext/Bug406914TestLanguage"
import "http://www.eclipse.org/emf/2002/Ecore"

Model: 
    name=ID BS_ESCAPE
;

/* SuppressWarnings[SpacesInKeyword] */
BS_ESCAPE:
	'\b' | '\f' | '\n' | 'lineFeed' | '\r' | '\t' | '\\'
;

terminal ID			: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

terminal WS			: (' '|'\t')+;

terminal ANY_OTHER:	.;