/*******************************************************************************
 * Copyright (c) 2016, 2017 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.parser.antlr.Bug406914TestLanguage 

generate bug406914Test "http://eclipse.org/xtext/Bug406914TestLanguage"
import "http://www.eclipse.org/emf/2002/Ecore"

Model: 
    name=ID BS_ESCAPE
;

/* SuppressWarnings[SpacesInKeyword] */
BS_ESCAPE:
	'\b' | '\f' | '\n' | 'lineFeed' | '\r' | '\t' | '\\'
;

terminal ID			: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

terminal WS			: (' '|'\t')+;

terminal ANY_OTHER:	.;
