/*******************************************************************************
 * Copyright (c) 2008, 2017 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.grammarinheritance.AbstractTestLanguage with org.eclipse.xtext.common.Terminals

import "http://www.eclipse.org/xtext/tests/grammarinheritance" as mm

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

InheritedParserRule returns mm::AType:
	'element' name=ID;
	
/* SuppressWarnings[noInstantiation] */
AbstractCallOverridenParserRule returns mm::AModel:
	'overridemodel' (elements+=OverridableParserRule)*;
	
OverridableParserRule returns mm::AType :
	'element' name=ID;
	
/* SuppressWarnings[SpacesInKeyword] */
OverridableParserRule2 returns mm::AType :
	'other element' name=STRING;

/* SuppressWarnings[noInstantiation] */
AbstractCallExtendedParserRule returns mm::AModel:
	'extendedmodel' (elements+=ExtendableParserRule)*;

ExtendableParserRule returns mm::AType :
	'element' name=ID;

terminal REAL returns ecore::EDouble : INT '.' INT;

@Override 
terminal ID		: ('^')?('a'..'z'|'A'..'Z'|'ö'|'ä'|'ü'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
