/*******************************************************************************
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
 grammar org.eclipse.xtext.grammarinheritance.BaseInheritanceTestLanguage with org.eclipse.xtext.common.Terminals
 
 generate baseInheritanceTest "http://www.eclipse.org/2009/tmf/xtext/BaseInheritanceTestLanguage"
 
 Model : "model" name=ID;
 
 FQN: ID ('.' ID)*;