/*******************************************************************************
 * Copyright (c) 2009, 2016 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.grammarinheritance.InheritanceTest2Language
	with org.eclipse.xtext.grammarinheritance.InheritanceTestLanguage
 	
generate inheritanceTest2 "http://www.eclipse.org/2009/tmf/xtext/InheritanceTest2Language"

@Override 
Model:
	"model" name=ID "{"
		elements+=Element*
		ids+=FQN
	"}"
;
