/*******************************************************************************
 * Copyright (c) 2015, 2016 itemis AG (http://www.itemis.eu) and others.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
grammar org.eclipse.xtext.grammarinheritance.InheritanceTest3Language
	with org.eclipse.xtext.grammarinheritance.InheritanceTestLanguage
 	
import "http://www.eclipse.org/2009/tmf/xtext/InheritanceTestLanguage"

@Override 
Model:
	super::Model
;

@Override 
Element :
	  super::Element
	| {Element} "element" name=super::ID
	| {Element} "element" name=Terminals::ID
	| {Element} "element" name=super::STRING
;

@Override 
terminal ID: 'id';
