package generator;

import com.google.common.base.Charsets;
import com.google.common.base.Objects;
import com.google.common.io.CharStreams;
import com.google.common.io.Files;
import com.google.common.io.OutputSupplier;
import generator.Resource;
import java.io.File;
import java.io.OutputStreamWriter;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.InputOutput;

@SuppressWarnings("all")
public abstract class AbstractWebsite implements Resource {
  public void generateTo(final File targetDir) {
    try {
      String _path = this.path();
      File _file = new File(targetDir, _path);
      final File file = _file;
      boolean _exists = file.exists();
      if (_exists) {
        InputOutput.<String>print("overwriting ");
      }
      CharSequence _website = this.website();
      OutputSupplier<OutputStreamWriter> _newWriterSupplier = Files.newWriterSupplier(file, Charsets.UTF_8);
      CharStreams.<OutputStreamWriter>write(_website, _newWriterSupplier);
      String _plus = ("generated \'" + file);
      String _plus_1 = (_plus + "\'");
      InputOutput.<String>println(_plus_1);
    } catch (Exception _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  /**
   * the path relative the website root
   */
  public abstract String path();
  
  public abstract CharSequence contents();
  
  public CharSequence website() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("<html lang=\"en\">");
    _builder.newLine();
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<meta charset=\"utf-8\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<title>Xtext - Language Development Made Easy!</title>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<meta name=\"description\"");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("content=\"The website of Eclipse Xtext, an open-source framework for development of programming langauges and domain-specific languages\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<meta name=\"author\" content=\"Sven Efftinge\">");
    _builder.newLine();
    _builder.append("\t");
    CharSequence _stylesheets = this.stylesheets();
    _builder.append(_stylesheets, "	");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _javaScriptDocumentStart = this.javaScriptDocumentStart();
    _builder.append(_javaScriptDocumentStart, "	");
    _builder.newLineIfNotEmpty();
    _builder.append("</head>");
    _builder.newLine();
    _builder.append("<body onload=\"prettyPrint()\">");
    _builder.newLine();
    _builder.append("\t");
    CharSequence _navBar = this.navBar();
    _builder.append(_navBar, "	");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _contents = this.contents();
    _builder.append(_contents, "	");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _quickLinksAndTweets = this.quickLinksAndTweets();
    _builder.append(_quickLinksAndTweets, "	");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _javaScriptAtTheEnd = this.javaScriptAtTheEnd();
    _builder.append(_javaScriptAtTheEnd, "	");
    _builder.newLineIfNotEmpty();
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence javaScriptDocumentStart() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<script");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("src=\"js/twitter.js\"");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("type=\"text/javascript\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</script>");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("getTwitters(\'tweet\', { ");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("id: \'xtext\', ");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("count: 5,");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("includeRT: true,");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("enableLinks: true, ");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("clearContents: true,");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("template: \'\"%text%\" <a href=\"http://twitter.com/%user_screen_name%/statuses/%id_str%/\">%time%</a><br/><br/>\'");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</script>");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("<script src=\"js/jquery-1.7.1.min.js\"></script>");
    _builder.newLine();
    _builder.append("<link rel=\"stylesheet\" media=\"screen\" href=\"css/prettyPhoto.css\" />");
    _builder.newLine();
    _builder.append("<script src=\"js/jquery.prettyPhoto.js\" type=\"text/javascript\"></script>");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$(document).ready(function() {");
    _builder.newLine();
    _builder.append("           ");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("$(\'a[data-rel]\').each(function() {");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("$(this).attr(\'rel\', $(this).data(\'rel\'));");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("$(\"a[rel^=\'prettyPhoto\']\").prettyPhoto({");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("animation_speed: \'fast\',");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("slideshow: 5000,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("autoplay_slideshow: false,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("opacity: 0.80,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("show_title: true,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("theme: \'ligh_square\',");
    _builder.newLine();
    _builder.append("//                     \'pp_default\', /* light_rounded / dark_rounded / light_square / dark_square / facebook */");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("overlay_gallery: false,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("social_tools: false");
    _builder.newLine();
    _builder.append("              ");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("            ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$(function() {      ");
    _builder.newLine();
    _builder.append("    \t");
    _builder.append("$(\'#outline > li > a\').live(\'click\', function() {        ");
    _builder.newLine();
    _builder.append("    \t\t");
    _builder.append("$(this).parent().find(\'ul\').slideToggle();      ");
    _builder.newLine();
    _builder.append("    \t");
    _builder.append("});    ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</script>");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("<link href=\"google-code-prettify/prettify.css\" type=\"text/css\" rel=\"stylesheet\" />");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\" src=\"google-code-prettify/prettify.js\"></script>");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\" src=\"google-code-prettify/lang-xtend.js\"></script>");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("var _gaq = _gaq || [];\t");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("_gaq.push([ \'_setAccount\', \'UA-2429174-4\' ]);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("_gaq.push([ \'_trackPageview\' ]);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("(function() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("var ga = document.createElement(\'script\');");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ga.type = \'text/javascript\';");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ga.async = true;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\'");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append(": \'http://www\')");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("+ \'.google-analytics.com/ga.js\';");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("var s = document.getElementsByTagName(\'script\')[0];");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("s.parentNode.insertBefore(ga, s);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("})();");
    _builder.newLine();
    _builder.append("</script>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence navBar() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!-- Navbar -->");
    _builder.newLine();
    _builder.append("<div class=\"navbar navbar-fixed-top\"");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("style=\"border-bottom: 1px solid #000;\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<div class=\"navbar-inner\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<a class=\"btn btn-navbar\" data-toggle=\"collapse\"");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("data-target=\".nav-collapse\"> <span class=\"icon-bar\"></span> <span");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</a> <a class=\"brand\" href=\"index.html\"></a>");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"nav-collapse collapse\" style=\"height: 0px;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<ul class=\"nav\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<li ");
    {
      String _path = this.path();
      boolean _equals = Objects.equal(_path, "download.html");
      if (_equals) {
        _builder.append("class=\"active\"");
      }
    }
    _builder.append("><a href=\"download.html\">Download</a></li>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("<li ");
    {
      String _path_1 = this.path();
      boolean _equals_1 = Objects.equal(_path_1, "examples.html");
      if (_equals_1) {
        _builder.append("class=\"active\"");
      }
    }
    _builder.append("><a href=\"examples.html\">Examples</a></li>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("<li ");
    {
      String _path_2 = this.path();
      boolean _equals_2 = Objects.equal(_path_2, "documentation.html");
      if (_equals_2) {
        _builder.append("class=\"active\"");
      }
    }
    _builder.append("><a href=\"documentation.html\">Documentation</a></li>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("<li ");
    {
      String _path_3 = this.path();
      boolean _equals_3 = Objects.equal(_path_3, "community.html");
      if (_equals_3) {
        _builder.append("class=\"active\"");
      }
    }
    _builder.append("><a href=\"community.html\">Community</a></li>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("<li><a href=\"http://www.eclipse.org\">Eclipse.org</a></li>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<!--/.nav-collapse -->");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("<!-- Navbar End -->");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence quickLinksAndTweets() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<div id=\"extra\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<div class=\"inner\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"row\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"span6\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<h3>Quick Links</h3>");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<ul class=\"footer-links clearfix\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<li><a href=\"#\">Support</a></li>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<li><a href=\"#\">License</a></li>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<li><a href=\"#\">Terms of Use</a></li>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<li><a href=\"#\">Privacy Policy</a></li>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<ul class=\"footer-links clearfix\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<li><a href=\"http://www.eclipse.org\">Eclipse.org</a></li>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<li><a href=\"http://marketplace.eclipse.org/\">Eclipse Market Place</a></li>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<li><a href=\"http://live.eclipse.org/\">Eclipse Live</a></li>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<li><a href=\"http://www.planeteclipse.org/\">Eclipse Planet</a></li>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"span6\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<h3><a href=\"https://twitter.com/#!/xtext\" style=\"color: white;\">@Xtext</a> Tweets</h3>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<br />");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<div id=\"tweet\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<p>Please wait while my tweets load</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<a href=\"http://twitter.com/rem\">If you can\'t wait - check");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("out what I\'ve been twittering</a>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence javaScriptAtTheEnd() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!-- Le javascript");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("================================================== -->");
    _builder.newLine();
    _builder.append("<!-- Placed at the end of the document so the pages load faster -->");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-transition.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-alert.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-modal.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-dropdown.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-scrollspy.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-tab.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-tooltip.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-popover.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-button.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-collapse.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-carousel.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"js/bootstrap-typeahead.js\"></script>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<!-- Include the plug-in -->");
    _builder.newLine();
    _builder.append("<script src=\"js/jquery.easing.1.3.js\" type=\"text/javascript\"></script>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<script src=\"js/custom.js\" type=\"text/javascript\"></script>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence stylesheets() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<style>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#header_wrapper {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("padding-top: 10px;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("/* 60px to make the container go all the way to the bottom of the topbar */");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("code.prettyprint {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("padding: 0px;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("background-color: white;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("border: none;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("</style>");
    _builder.newLine();
    _builder.append("<!--  styles -->");
    _builder.newLine();
    _builder.append("<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->");
    _builder.newLine();
    _builder.append("<!--[if lt IE 9]>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>");
    _builder.newLine();
    _builder.append("<![endif]-->");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<!-- Le fav and touch icons -->");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<link rel=\"shortcut icon\" href=\"images/favicon.png\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<link href=\"css/bootstrap.css\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("<link href=\"css/bootstrap-responsive.css\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("<link rel=\"stylesheet\" href=\"css/style.css\">");
    _builder.newLine();
    _builder.append("<link rel=\"stylesheet\" href=\"css/shield-responsive.css\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<link");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("href=\'http://fonts.googleapis.com/css?family=Vollkorn:400italic,400\'");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("rel=\'stylesheet\' type=\'text/css\'>");
    _builder.newLine();
    _builder.append("<link");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("href=\'http://fonts.googleapis.com/css?family=Lato:400,400italic,900italic\'");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("rel=\'stylesheet\' type=\'text/css\'>");
    _builder.newLine();
    return _builder;
  }
}
