package generator;

import generator.AbstractWebsite;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Download extends AbstractWebsite {
  public String path() {
    return "download.html";
  }
  
  public CharSequence contents() {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _headline = this.headline("Download");
    _builder.append(_headline, "");
    _builder.newLineIfNotEmpty();
    _builder.append("<div id=\"page\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<div class=\"inner\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"container clearfix\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<h2>Download Options</h2>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<hr>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<!--table one starts-->");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<div class=\"span4\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"pricing\">");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<td></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<td class=\"focus\">Update Sites <span>Use Update Manager in Eclipse</span></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Latest Release</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<a href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/milestones/\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Latest Milestone</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<td style=\"text-align: center;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<a href=\"http://download.eclipse.org/modeling/tmf/xtext/updates/composite/stable/\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 70%;\">Bleeding Edge!</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("<div class=\"span4\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"pricing\">");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("<table>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<td></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</tfoot>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<td class=\"focus\">Full Eclipse <span>Just Download and Unzip</span></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-macosx-cocoa-x86_64.tar.gz\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\" style=\"width: 45%;\">OS X 64 Bit</a>&nbsp;<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-macosx-cocoa.tar.gz\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-linux-gtk-x86_64.tar.gz\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 45%;\">Linux 64 Bit</a>&nbsp;<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-linux-gtk.tar.gz\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<td style=\"text-align: center; white-space: nowrap;\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-win32-x86_64.zip\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width: 45%;\">Windows 64 Bit</a>&nbsp;<a href=\"http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/distros/eclipse-SDK-3.7.1-Xtext-2.2.1-linux-gtk.tar.gz\" ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("class=\"btn btn-primary btn-large\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    \t");
    _builder.append("style=\"width:20%;\">32 Bit</a></td>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<h2>FAQs</h2>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<hr />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span9\" id=\"faq\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"accordion\" id=\"accordion2\">");
    _builder.newLine();
    _builder.append("\t\t\t\t    ");
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("Eclipse comes with a built-in update manager, that understands so called update sites.");
    _builder_1.newLine();
    _builder_1.append("When in Eclipse open the <i>\"Help\"</i> menu and click on <i>\"Install new Software...\"</i>.");
    _builder_1.newLine();
    CharSequence _faqEntry = this.faqEntry("What is an update site?", _builder_1);
    _builder.append(_faqEntry, "				    ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t    ");
    StringConcatenation _builder_2 = new StringConcatenation();
    _builder_2.append("<p>Xtext is freely available under the <a href=\"http://www.eclipse.org/legal/epl-v10.html\">Eclipse Public License</a>.</p>");
    _builder_2.newLine();
    _builder_2.append("<p>");
    _builder_2.newLine();
    _builder_2.append("\t");
    _builder_2.append("The license allows to use Xtext for development and even for developing and selling commercial products based on Xtext.");
    _builder_2.newLine();
    _builder_2.append("</p>");
    _builder_2.newLine();
    CharSequence _faqEntry_1 = this.faqEntry("What is the license of Xtext?", _builder_2);
    _builder.append(_faqEntry_1, "				    ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t    ");
    StringConcatenation _builder_3 = new StringConcatenation();
    _builder_3.append("<p>Software systems built from open source components requires manpower that understands the internal dependencies of ");
    _builder_3.newLine();
    _builder_3.append("these components and can quickly and efficiently eliminate problems, should an error occur. </p>");
    _builder_3.newLine();
    _builder_3.append("<p><b>itemis</b> is the leading consulting company for Eclipse-based development tools and is the main");
    _builder_3.newLine();
    _builder_3.append("supporter for the Xtext project. Xtext experts are available for consulting.</p>");
    _builder_3.newLine();
    _builder_3.append("See <a target=\"_blank\" href=\"http://xtext.itemis.com\">xtext.itemis.com</a> for more details.");
    _builder_3.newLine();
    CharSequence _faqEntry_2 = this.faqEntry("If Xtext is open-source how can I get professional support?", _builder_3);
    _builder.append(_faqEntry_2, "				    ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t    ");
    StringConcatenation _builder_4 = new StringConcatenation();
    _builder_4.append("<p>If you instead prefer a downloadable updatesite or an SDK zip, ");
    _builder_4.newLine();
    _builder_4.append("please have a look at the following site : <a href=\"http://www.eclipse.org/modeling/tmf/downloads/\">http://www.eclipse.org/modeling/tmf/downloads/</a></p>");
    _builder_4.newLine();
    CharSequence _faqEntry_3 = this.faqEntry("Can I download the update site as a zip?", _builder_4);
    _builder.append(_faqEntry_3, "				    ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t  \t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span1\">&nbsp;</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence faqEntry(final String question, final CharSequence answer) {
    StringConcatenation _builder = new StringConcatenation();
    final String key = question.replaceAll("\\W", "_");
    _builder.newLineIfNotEmpty();
    _builder.append("<div class=\"accordion-group\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<div class=\"accordion-heading\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<a class=\"accordion-toggle\" data-toggle=\"collapse\" data-parent=\"#accordion2\" href=\"#");
    _builder.append(key, "	");
    _builder.append("\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append(question, "	  ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<div id=\"");
    _builder.append(key, "  ");
    _builder.append("\" class=\"accordion-body collapse\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<div class=\"accordion-inner\">");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append(answer, "	  ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
}
