<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bug288432Test" nsURI="http://www.eclipse.org/2008/tmf/xtext/Bug288432Test"
    nsPrefix="bug288432Test">
  <eClassifiers xsi:type="ecore:EClass" name="Body">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//ParameterObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foo" upperBound="-1" eType="#//Foo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fooValue" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content" eSuperTypes="#//ParameterObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="MyElement" eSuperTypes="#//Content">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bar" eType="#//ParameterObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ParameterObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterRef" eSuperTypes="#//ParameterObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyInt" eSuperTypes="#//ParameterObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="int" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
