/*******************************************************************************
 * Copyright (c) 2008 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.ui.tests.quickfix.QuickfixCrossrefTestLanguage with org.eclipse.xtext.common.Terminals

generate importUriUi "http://eclipse.org/xtext/quickfixCrossrefTestLanguage"

Main : 
	elements+=Element*;

Element:
	name=ID '{' contained+=Element* ('ref' referenced+=[Element])* '}'
;